# XpgAnalyzer - vue IHM (format 19)
vue id=176 nom="Vue_Armoires" description="Les deux armoires, une popup parametree" largeur=1280 hauteur=800 fond="#20242B" calque_actif=177
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=177 nom="Calque 1" visible=1 verrou=0
objet id=178 type=Text nom="Titre_Armoires" calque=177 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="20"
prop cle=w valeur="900"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoires de gaz  -  une popup pour les deux"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="28"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=179 type=Text nom="Seuils_Armoires" calque=177 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="80"
prop cle=w valeur="900"
prop cle=h valeur="30"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Seuils enregistrés :  A = {Armoires[0].seuil_poids_saisi:0.0} kg    B = {Armoires[1].seuil_poids_saisi:0.0} kg"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="18"
prop cle=textColor valeur="#9CC3E6"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=180 type=Button nom="Btn_Armoire_A" calque=177 parent=0 verrou=0 cache=0
prop cle=x valeur="60"
prop cle=y valeur="140"
prop cle=w valeur="200"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoire A"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=181 type=Button nom="Btn_Armoire_B" calque=177 parent=0 verrou=0 cache=0
prop cle=x valeur="300"
prop cle=y valeur="140"
prop cle=w valeur="200"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoire B"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=182 type=Button nom="Btn_Fermer_Popups" calque=177 parent=0 verrou=0 cache=0
prop cle=x valeur="540"
prop cle=y valeur="140"
prop cle=w valeur="220"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Fermer les popups"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=183 type=Button nom="Btn_Aide_Armoires" calque=177 parent=0 verrou=0 cache=0
prop cle=x valeur="1080"
prop cle=y valeur="20"
prop cle=w valeur="160"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Aide"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=184 type=Text nom="Libelle_Saisie_A" calque=177 parent=0 verrou=0 cache=0
prop cle=x valeur="60"
prop cle=y valeur="640"
prop cle=w valeur="400"
prop cle=h valeur="30"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Seuil de l'armoire A, au clavier :"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=185 type=InputField nom="Saisie_Seuil_A" calque=177 parent=0 verrou=0 cache=0
prop cle=x valeur="60"
prop cle=y valeur="680"
prop cle=w valeur="220"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="droite"
prop cle=mode valeur="numérique"
prop cle=format valeur="0.0"
prop cle=min valeur="0"
prop cle=max valeur="60"
prop cle=unit valeur="kg"
prop cle=maxLength valeur="32"
prop cle=placeholder valeur=""
prop cle=keyboard valeur="aucun"
prop cle=validateOnExit valeur="FALSE"
prop cle=fill valeur="#141820"
prop cle=stroke valeur="#4A5568"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="3"
prop cle=variable valeur="Armoires[0].seuil_poids_saisi"
prop cle=refresh valeur="500"
prop cle=access valeur="0"
action objet=180 declencheur="Clic" operation="Ouvrir une popup" cible="Popup_Armoire" valeur="Armoire := Armoires[0]; Nom := 'A'" position="objet" transition="Fondu" duree=300 direction="gauche" courbe="douce"
action objet=181 declencheur="Clic" operation="Ouvrir une popup" cible="Popup_Armoire" valeur="Armoire := Armoires[1]; Nom := 'B'" transition="Fondu" duree=300 direction="gauche" courbe="douce"
action objet=182 declencheur="Clic" operation="Fermer toutes les popups"
action objet=183 declencheur="Clic" operation="Ouvrir une popup" cible="Popup_Aide" transition="Fondu" duree=300 direction="gauche" courbe="douce"
fin
