// =============================================================================
//  help/TutorialTexts.cpp - les tutoriels ecrits, embarques dans l'appli
// -----------------------------------------------------------------------------
//  GENERE par tools/tutoriels/generer_tutoriels.py depuis tools/tutoriels/*.tuto :
//  NE PAS MODIFIER A LA MAIN. Changer le fichier .tuto, puis :
//      python3 tools/tutoriels/generer_tutoriels.py --cpp src/help/TutorialTexts.cpp
// =============================================================================
#include "TutorialLaunch.hpp"

namespace help {

const std::vector<EmbeddedTutorial>& embeddedTutorials() {
    static const std::vector<EmbeddedTutorial> all = {
        {"expression-couleur.tuto",
         "# L'expression (maquette 1.11, sc\xC3\xA8ne 4) : la couleur de la cuve suit V[0].Pos.\n"
         "# Une couleur dans une expression est une cha\xC3\xAEne ('#E53935') ; SEL(G, si FAUX, si VRAI) suit la\n"
         "# norme CEI (sim/Runtime.cpp) : la maquette en fait l'erreur que le tutoriel montre et corrige.\n"
         "# Bac : Armoire_Gaz (V : ARRAY[0..3] OF T_VANNE). Format : v111/agents/CONCEPTION-T1.md, section 1.\n"
         "= expression-couleur | Une expression : la couleur de la cuve\n"
         "@sujet champs-expressions\n"
         "@sujet expression-couleur\n"
         "@bac Armoire_Gaz | Vue_Tuto\n"
         "\n"
         "# La tuyauterie, la vanne V_201, la cuve Cuve_T1 et le texte au-dessus de la vanne.\n"
         "@avant\n"
         "type T_VANNE \"Pos : REAL; Defaut : BOOL; Bouge : BOOL; Cmd : BOOL\"\n"
         "variable V \"ARRAY[0..3] OF T_VANNE\"\n"
         "vue Vue_Tuto\n"
         "poser Tuyauterie 120,262 Tuyauterie_1\n"
         "regler Tuyauterie_1 Largeur 520\n"
         "poser Vanne 400,262 V_201\n"
         "poser Cuve 660,180 Cuve_T1\n"
         "poser Texte 370,200 Txt_Ouverture\n"
         "\n"
         "== 1 | Choisis la cuve et sa couleur\n"
         ": Un clic sur la cuve : l'inspecteur. **Couleur du contenu** a la pastille **fx** en creux : elle accepte une expression ; son type, \xC2\xAB couleur \xC2\xBB, est \xC3\xA9" "crit au bout.\n"
         "clic vue:Cuve_T1\n"
         "encadrer \"propriete:Couleur du contenu\"\n"
         "dire \"Vide, elle montre en gris ce qu'elle attend : \xC2\xAB couleur \xC2\xBB. Plus de \xC2\xAB ou = expression \xC2\xBB : la pastille le dit (1.10.1).\"\n"
         "attendre 800ms\n"
         "@atoi Clique la cuve dans la vue (ou Cuve_T1 dans la liste des objets).\n"
         "@cible vue:Cuve_T1\n"
         "@verifier selection = Cuve_T1\n"
         "\n"
         "== 2 | Clic droit : une expression\n"
         ": Un clic sur une case couleur ouvre la palette. Pour une expression : **clic droit** sur la case, puis **\xC3\x89" "crire une expression\xE2\x80\xA6**. La case s'ouvre sur **=**, qui reste affich\xC3\xA9 devant l'expression. D\xC3\xA8s la premi\xC3\xA8re lettre, l'aide \xC3\xA0 la saisie s'ouvre.\n"
         "# Tranche 8 (decision du chef, 02/10 18 h 51) : la pastille fx n'est pas un bouton (un clic sur\n"
         "# elle ouvre la palette, comme le reste de la case). Le clic droit \"Ecrire une expression...\"\n"
         "# ouvre un champ \"=\". Sur \"=\" seul, l'aide a la saisie ne propose rien, meme par Ctrl+Espace\n"
         "# (HmiAssist.cpp, fieldAssist : une liste des la premiere lettre, apres un point ou dans une\n"
         "# accolade) : on tape S. Le clic sur la case donne le clavier au champ (apres le menu, la\n"
         "# grille reprend le focus). L'ecart avec la maquette (scene 4 : \"les couleurs d'abord\") est accepte.\n"
         "clic \"propriete:Couleur du contenu\" droit\n"
         "clic \"menu:\xC3\x89" "crire une expression\xE2\x80\xA6\"\n"
         "texte \"propriete:Couleur du contenu\" \"=S\"\n"
         "encadrer aide-saisie\n"
         "dire \"Ce qui commence par S : les fonctions (SEL\xE2\x80\xA6) et les variables. \xE2\x86\x93 choisit, Entr\xC3\xA9" "e ins\xC3\xA8re, \xC3\x89" "chap ferme la liste.\"\n"
         "attendre 1.5s\n"
         "@atoi Clic droit sur la case Couleur du contenu, \xC3\x89" "crire une expression\xE2\x80\xA6, puis tape S : l'aide \xC3\xA0 la saisie s'ouvre.\n"
         "@cible \"propriete:Couleur du contenu\"\n"
         "@verifier saisie.ouverte = oui\n"
         "\n"
         "== 3 | SEL, V[0].Pos\xE2\x80\xA6 et une erreur\n"
         ": **SEL(condition, si FAUX, si VRAI)**. Apr\xC3\xA8s `V[0].`, les membres. Puis j'\xC3\xA9" "cris les couleurs **sans apostrophes**, comme dans la case d'une couleur fixe.\n"
         "# Tranche 8 : la case est deja ouverte sur \"=\" (etape 2) : un clic droit sur le champ ouvert\n"
         "# n'ouvre pas le menu de la grille (verificateur). On ecrit dans le champ.\n"
         "texte \"propriete:Couleur du contenu\" \"=SEL(V[0].\"\n"
         "encadrer saisie:Pos\n"
         "attendre 1s\n"
         "touche Return\n"
         "texte \" > 80, #E53935, #43A047)\"\n"
         "touche Return\n"
         "encadrer \"propriete:Couleur du contenu\"\n"
         "dire \"La ligne passe en rouge, la pastille aussi, et la raison est dessous : \xC2\xAB caract\xC3\xA8re inattendu : '#' \xC2\xBB. Dans une expression, une couleur s'\xC3\xA9" "crit entre apostrophes.\"\n"
         "# Tranche 8 : plus d'\"A toi\" ici. Les gestes de l'etape font l'erreur expr\xC3\xA8s : le verificateur\n"
         "# (\"Montre-moi\" puis la verification) ne pouvait pas la trouver juste. L'\"A toi\" est a l'etape 4.\n"
         "\n"
         "== 4 | Corrige la faute\n"
         ": Un clic sur la case rouge la rouvre sur son expression. Les deux couleurs entre **apostrophes**, puis Entr\xC3\xA9" "e : la pastille redevient bleue ; la couleur se calcule.\n"
         "# Tranche 8 : la maquette corrigeait d'un clic, par le lien \"Remplacer par\". L'appli ne montre ce\n"
         "# lien que pour un nom inconnu (\"X n'existe pas : veux-tu dire Y ?\", DataViews.cpp, noteFix) ;\n"
         "# pour \"caractere inattendu : '#'\", il n'y en a pas : on corrige dans la case.\n"
         "texte \"propriete:Couleur du contenu\" \"=SEL(V[0].Pos > 80, '#E53935', '#43A047')\"\n"
         "touche Return\n"
         "encadrer \"propriete:Couleur du contenu\"\n"
         "dire \"=SEL(V[0].Pos > 80, '#E53935', '#43A047'). Avec V[0].Pos = 42 (la valeur d'essai), la condition est fausse : SEL rend le premier choix, le rouge.\"\n"
         "attendre 600ms\n"
         "encadrer vue:Cuve_T1\n"
         "attendre 1.2s\n"
         "dire \"SEL suit la norme CEI : SEL(condition, si FAUX, si VRAI). Pour du rouge au-dessus de 80 %, \xC3\xA9" "change les deux couleurs.\"\n"
         "@atoi La ligne est rouge : corrige l'expression. \xC3\x89" "cris =SEL(V[0].Pos > 80, '#E53935', '#43A047') puis Entr\xC3\xA9" "e.\n"
         "@cible \"propriete:Couleur du contenu\"\n"
         "@verifier objet(Cuve_T1).fillColor = \"=SEL(V[0].Pos > 80, '#E53935', '#43A047')\"\n"
         "@presque objet(Cuve_T1).fillColor ~ #E53935, | Dans une expression, une couleur s'\xC3\xA9" "crit entre apostrophes : '#E53935'.\n"
         "\n"
         "== 5 | Un texte \xC3\xA0 trous\n"
         ": Le texte au-dessus de la vanne : `Ouverture : {V[0].Pos} %`. Entre accolades, une variable : elle s'\xC3\xA9" "crit avec sa valeur.\n"
         "clic vue:Txt_Ouverture\n"
         "clic propriete:Texte\n"
         "texte propriete:Texte \"Ouverture : {V[0].\"\n"
         "touche Return\n"
         "texte \"} %\"\n"
         "touche Return\n"
         "encadrer vue:Txt_Ouverture\n"
         "dire \"Dans la vue : \xC2\xAB Ouverture : 42 % \xC2\xBB. Pas de = : un texte \xC3\xA0 trous n'est pas une expression ; {V[0].Pos:0.0} donnerait 42,0.\"\n"
         "@atoi Choisis le texte (au-dessus de la vanne) et \xC3\xA9" "cris Ouverture : {V[0].Pos} % dans sa case Texte.\n"
         "@cible vue:Txt_Ouverture\n"
         "@verifier objet(Txt_Ouverture).text = \"Ouverture : {V[0].Pos} %\"\n"
         "\n"
         "== 6 | Essaie : V[0].Pos passe 80\n"
         ": L'IHM en marche : au-del\xC3\xA0 de 80, la condition est vraie et la cuve passe au second choix, le vert. Le texte suit.\n"
         "touche F8\n"
         "encadrer vue:Cuve_T1\n"
         "simuler 7s\n"
         "dire \"42 \xE2\x86\x92 94 \xE2\x86\x92 42 : la cuve change de couleur quand V[0].Pos franchit 80, le texte suit en direct.\"\n"
         "@atoi D\xC3\xA9marre l'IHM avec F8 : la cuve change de couleur quand V[0].Pos passe 80.\n"
         "@cible vue:Cuve_T1\n"
         "@verifier simulation.ihm = marche\n"
         "\n"
         "== 7 | Plus loin : la page des expressions\n"
         ": Chaque type a sa page : la syntaxe, les op\xC3\xA9rateurs, les fonctions, des exemples et un champ d'essai. Reviens \xC3\xA0 l'onglet **Vue_Tuto** (l'IHM continue de tourner), **clic droit** sur la case, puis **La page des expressions\xE2\x80\xA6** : elle s'ouvre sur le type \xC2\xAB couleur \xC2\xBB.\n"
         "# Integration I111 (lien 5) : l'entree du menu de la case (ui::propertygrid::kExpressionPageItem) ouvre\n"
         "# HmiExprScreen (T3) sur le type de la case ; le bouton du type est l'ancre stable de la page.\n"
         "# Session 89 : l'IHM lancee a l'etape 6 montre l'onglet Simulation \xC2\xB7 IHM (le volet Expressions),\n"
         "# sans l'inspecteur : on revient d'abord a l'onglet de la vue, et on y reprend la cuve.\n"
         "clic \"onglet:Vue_Tuto\"\n"
         "clic vue:Cuve_T1\n"
         "clic \"propriete:Couleur du contenu\" droit\n"
         "survol \"menu:La page des expressions\xE2\x80\xA6\"\n"
         "clic \"menu:La page des expressions\xE2\x80\xA6\"\n"
         "encadrer \"bouton:#   Couleur\"\n"
         "attendre 1.8s\n"},
        {"objet-vanne.tuto",
         "# La vanne et ses variantes (maquette 1.11, sc\xC3\xA8ne 2). Bac : Armoire_Gaz, vue Vue_Tuto\n"
         "# (la ligne d'azote, la cuve T1). V : ARRAY[0..3] OF T_VANNE (Pos, Defaut, Bouge, Cmd).\n"
         "# Format : v111/agents/CONCEPTION-T1.md, section 1. Une cible dont le nom a des\n"
         "# espaces s'\xC3\xA9" "crit entre guillemets : \"propriete:Couleur allum\xC3\xA9\". Les cibles propriete: portent\n"
         "# le libell\xC3\xA9 exact de l'inspecteur (HmiPanels.cpp) ; les conditions lisent la cl\xC3\xA9 (objet[Vanne].opening).\n"
         "= objet-vanne | Vanne, avec ses variantes\n"
         "@sujet objet-vanne\n"
         "@bac Armoire_Gaz | Vue_Tuto\n"
         "@variantes manuelle, motoris\xC3\xA9" "e, pneumatique, r\xC3\xA9glante\n"
         "@variante r\xC3\xA9glante\n"
         "\n"
         "# Le bac \xC3\xA0 sable (tranche 2) : une copie neuve d'Armoire_Gaz n'a ni Vue_Tuto ni\n"
         "# Tuyauterie_1 ; @avant les cr\xC3\xA9" "e \xC3\xA0 chaque remise \xC3\xA0 neuf, sans animation, avant l'\xC3\xA9tape 1.\n"
         "@avant\n"
         "type T_VANNE \"Pos : REAL; Defaut : BOOL; Bouge : BOOL; Cmd : BOOL\"\n"
         "variable V \"ARRAY[0..3] OF T_VANNE\"\n"
         "vue Vue_Tuto\n"
         "poser Tuyauterie 120,262 Tuyauterie_1\n"
         "regler Tuyauterie_1 Largeur 520\n"
         "poser Cuve 660,180 T1\n"
         "\n"
         "== 1 | Choisis la variante\n"
         ": Dans la biblioth\xC3\xA8que, la tuile **Vanne**. La vanne a quatre **variantes** : leurs noms sont en haut, dans le bandeau, \xC3\xA0 droite d'\xC2\xAB Aller \xC3\xA0 \xC2\xBB, et celle que montre le tutoriel y est en orange.\n"
         "clic biblio:Vanne\n"
         "encadrer variantes\n"
         "dire \"Manuelle : un volant. Motoris\xC3\xA9" "e : un moteur M. Pneumatique : une membrane. R\xC3\xA9glante : ouverture de 0 \xC3\xA0 100 %.\"\n"
         "attendre 1.5s\n"
         "clic variante:{variante}\n"
         "encadrer variante:{variante}\n"
         "[!r\xC3\xA9glante] dire \"La vanne {variante} est ouverte ou ferm\xC3\xA9" "e.\"\n"
         "[r\xC3\xA9glante] dire \"La vanne r\xC3\xA9glante est ouverte \xC3\xA0 35 %, pas seulement ouverte ou ferm\xC3\xA9" "e.\"\n"
         "@atoi Clique Vanne dans la biblioth\xC3\xA8que, puis choisis la variante.\n"
         "@cible variantes\n"
         "@verifier biblio.variante <> \"\"\n"
         "@bravo Bien : la vanne {valeur}.\n"
         "@onok variante=biblio.variante\n"
         "\n"
         "== 2 | Pose l'instance\n"
         ": Glisse la vanne sur la tuyauterie : elle s'y pose et prend son sens.\n"
         "encadrer vue:Tuyauterie_1\n"
         "glisser variante:{variante} vue:400,262\n"
         "dire \"Pos\xC3\xA9" "e sur la tuyauterie. L'inspecteur, \xC3\xA0 droite, montre ses propri\xC3\xA9t\xC3\xA9s : Commande de la vanne vaut d\xC3\xA9j\xC3\xA0 \xC2\xAB {variante} \xC2\xBB.\"\n"
         "@atoi Glisse la vanne sur la tuyauterie.\n"
         "@cible vue:Tuyauterie_1\n"
         "@verifier objets[Vanne] >= 1\n"
         "@presque objet[Vanne].sur-tuyauterie = non | Elle est pos\xC3\xA9" "e, mais pas sur la tuyauterie.\n"
         "\n"
         "== 3 | Nomme-la\n"
         ": Le **Nom** sert aux scripts et aux alarmes ; le **Libell\xC3\xA9** est \xC3\xA9" "crit sous la vanne.\n"
         "clic propriete:Nom\n"
         "texte propriete:Nom \"V_201\"\n"
         "touche Return\n"
         "encadrer propriete:Nom\n"
         "attendre 500ms\n"
         "clic propriete:Libell\xC3\xA9\n"
         "texte propriete:Libell\xC3\xA9 \"V-201\"\n"
         "touche Return\n"
         "dire \"Le libell\xC3\xA9 V-201 est sous la vanne ; les alarmes parleront de \xC2\xAB V-201 \xC2\xBB.\"\n"
         "@atoi Nomme la vanne V_201, avec le libell\xC3\xA9 V-201.\n"
         "@cible propriete:Nom\n"
         "@verifier objet[Vanne].nom = V_201\n"
         "@presque objet[Vanne].nom = V201 | Le tutoriel attend V_201, tu as \xC3\xA9" "crit {valeur}.\n"
         "\n"
         "== 4 | Lie l'ouverture\n"
         "[r\xC3\xA9glante] : L'**Ouverture (%)** suit une variable : `=V[0].Pos`. Apr\xC3\xA8s `V[0].`, l'aide \xC3\xA0 la saisie propose les membres de T_VANNE.\n"
         "[!r\xC3\xA9glante] : La **Valeur** dit si la vanne est ouverte : `=V[0].Pos > 0`.\n"
         "[r\xC3\xA9glante] clic \"propriete:Ouverture (%)\"\n"
         "[r\xC3\xA9glante] texte \"propriete:Ouverture (%)\" \"=\"\n"
         "[!r\xC3\xA9glante] clic propriete:Valeur\n"
         "[!r\xC3\xA9glante] texte propriete:Valeur \"=\"\n"
         "[r\xC3\xA9glante] dire \"Le = ouvre une expression et reste affich\xC3\xA9. L'aide \xC3\xA0 la saisie propose d'abord ce qui convient : les nombres.\"\n"
         "[!r\xC3\xA9glante] dire \"Le = ouvre une expression et reste affich\xC3\xA9. L'aide \xC3\xA0 la saisie propose d'abord ce qui convient : les BOOL.\"\n"
         "attendre 1.1s\n"
         "texte \"V[0].\"\n"
         "encadrer saisie:Pos\n"
         "dire \"Les membres de T_VANNE, avec leur type : Pos REAL, Defaut BOOL, Bouge BOOL, Cmd BOOL.\"\n"
         "attendre 1.2s\n"
         "[r\xC3\xA9glante] texte \"Pos\"\n"
         "[!r\xC3\xA9glante] texte \"Pos > 0\"\n"
         "touche Return\n"
         "[r\xC3\xA9glante] dire \"La pastille fx est pleine, la ligne teint\xC3\xA9" "e, l'expression gard\xC3\xA9" "e avec son =. En simulation, la jauge suivra V[0].Pos.\"\n"
         "[!r\xC3\xA9glante] dire \"La pastille fx est pleine, la ligne teint\xC3\xA9" "e, l'expression gard\xC3\xA9" "e avec son =.\"\n"
         "@atoi Lie la vanne \xC3\xA0 V[0].Pos.\n"
         "[r\xC3\xA9glante] @verifier objet[Vanne].opening = \"=V[0].Pos\"\n"
         "[!r\xC3\xA9glante] @verifier objet[Vanne].value = \"=V[0].Pos > 0\"\n"
         "[r\xC3\xA9glante] @presque objet[Vanne].opening = \"V[0].Pos\" | Sans \xC2\xAB = \xC2\xBB, c'est une valeur fixe.\n"
         "\n"
         "== 5 | Ses couleurs et ses \xC3\xA9tats\n"
         ": La **Couleur allum\xC3\xA9**, et le **D\xC3\xA9" "faut** reli\xC3\xA9 \xC3\xA0 `=V[0].Defaut` : l'aper\xC3\xA7u montre les trois \xC3\xA9tats.\n"
         "clic \"propriete:Couleur allum\xC3\xA9\"\n"
         "texte \"propriete:Couleur allum\xC3\xA9\" \"'#2ECC71'\"\n"
         "touche Return\n"
         "clic \"propriete:D\xC3\xA9" "faut (expression)\"\n"
         "texte \"propriete:D\xC3\xA9" "faut (expression)\" \"=V[0].Defaut\"\n"
         "touche Return\n"
         "encadrer apercu-etats\n"
         "dire \"Ouverte, ferm\xC3\xA9" "e, en d\xC3\xA9" "faut : le D\xC3\xA9" "faut arme l'alarme Defaut de la vanne.\"\n"
         "attendre 1s\n"
         "dire \"Le D\xC3\xA9" "faut est reli\xC3\xA9 : en marche, la vanne passera en rouge et clignotera quand V[0].Defaut sera vrai.\"\n"
         "@atoi Relie le D\xC3\xA9" "faut \xC3\xA0 V[0].Defaut.\n"
         "@verifier objet[Vanne].fault = \"=V[0].Defaut\"\n"
         "\n"
         "== 6 | Ses alarmes par d\xC3\xA9" "faut\n"
         ": Les alarmes par d\xC3\xA9" "faut s'arment quand leur propri\xC3\xA9t\xC3\xA9 est reli\xC3\xA9" "e.\n"
         "encadrer alarmes-objet\n"
         "[motoris\xC3\xA9" "e, r\xC3\xA9glante] attendre 1.3s\n"
         "[manuelle, pneumatique] attendre 900ms\n"
         "[motoris\xC3\xA9" "e, r\xC3\xA9glante] clic \"propriete:En mouvement (expression)\"\n"
         "[motoris\xC3\xA9" "e, r\xC3\xA9glante] texte \"propriete:En mouvement (expression)\" \"=V[0].Bouge\"\n"
         "[motoris\xC3\xA9" "e, r\xC3\xA9glante] touche Return\n"
         "[motoris\xC3\xA9" "e, r\xC3\xA9glante] dire \"Course_Trop_Longue s'arme : \xC2\xAB V-201 : ne finit pas sa course \xC2\xBB si elle bouge plus de 30 s (priorit\xC3\xA9 3).\"\n"
         "[motoris\xC3\xA9" "e, r\xC3\xA9glante] clic alarme:Course_Trop_Longue\n"
         "[motoris\xC3\xA9" "e, r\xC3\xA9glante] attendre 600ms\n"
         "[manuelle, pneumatique] clic alarme:Defaut\n"
         "[manuelle, pneumatique] dire \"Sa condition, son message (\xC2\xAB V-201 : d\xC3\xA9" "faut \xC2\xBB), sa priorit\xC3\xA9 (2, Haute). D\xC3\xA9" "cochable sur cet objet seulement.\"\n"
         "attendre 1s\n"
         "\n"
         "== 7 | Essaie en simulation\n"
         ": **F8** d\xC3\xA9marre l'IHM : la vanne suit `V[0].Pos` en direct. Quand `V[0].Defaut` passe \xC3\xA0 TRUE, elle clignote en rouge.\n"
         "touche F8\n"
         "simuler 1s\n"
         "encadrer vue:V_201\n"
         "simuler 6.6s\n"
         "[r\xC3\xA9glante] dire \"La jauge et le pourcentage suivent V[0].Pos (acc\xC3\xA9l\xC3\xA9r\xC3\xA9 \xC3\x97" "10). Quand V[0].Defaut passe \xC3\xA0 TRUE, elle clignote en rouge et l'alarme s'affiche.\"\n"
         "[!r\xC3\xA9glante] dire \"Ouverte d\xC3\xA8s que V[0].Pos quitte 0 (acc\xC3\xA9l\xC3\xA9r\xC3\xA9 \xC3\x97" "10). Quand V[0].Defaut passe \xC3\xA0 TRUE, elle clignote en rouge et l'alarme s'affiche.\"\n"
         "@atoi D\xC3\xA9marre l'IHM avec F8.\n"
         "@verifier simulation.ihm = marche\n"},
        {"page-raccourcis.tuto",
         "# La page des raccourcis du centre d'aide (sujet page-raccourcis). \xC3\x89" "crit \xC3\xA0 la main (T1, tranche 19) :\n"
         "# une page sp\xC3\xA9" "ciale n'a pas de tutoriel d\xC3\xA9" "duit (d\xC3\xA9" "cision du chef du 03/10, 12).\n"
         "# Ce que le centre en dit : \xC2\xAB Toutes les touches, group\xC3\xA9" "es par contexte ; la fiche A4 \xC3\xA0 imprimer. \xC2\xBB\n"
         "# Les notes de la 1.11 : \xC2\xAB group\xC3\xA9" "e par contexte, elle se cherche et s'imprime en A4. Ctrl+H reste \xC3\xA0\n"
         "# l'Historique ; l'import de la configuration mat\xC3\xA9rielle (.XHW), qui le portait aussi, passe \xC3\xA0 Ctrl+Maj+O. \xC2\xBB\n"
         "# Les touches cit\xC3\xA9" "es viennent de la table (src/help/Shortcuts.cpp). La bande de la page (HelpCenterScreen,\n"
         "# id help) : le champ help.keys.search, les boutons Aper\xC3\xA7u A4 (puis Les tables) et Imprimer\xE2\x80\xA6 ; on ne clique\n"
         "# pas Imprimer\xE2\x80\xA6 (il ouvre le navigateur). @avant aide : le centre s'ouvre sur la page, par-dessus le bac.\n"
         "= page-raccourcis | La page des raccourcis\n"
         "@sujet page-raccourcis\n"
         "@bac Armoire_Gaz\n"
         "\n"
         "@avant\n"
         "aide page-raccourcis\n"
         "\n"
         "== 1 | Toutes les touches, par contexte\n"
         ": Chaque touche de l'appli, rang\xC3\xA9" "e par contexte : G\xC3\xA9n\xC3\xA9ral, \xC3\x89" "diteur IHM, Scripts, Simulation, Grafcet et Aide. Les pastilles du haut n'en gardent qu'un.\n"
         "encadrer \"champ:help.keys.search\"\n"
         "dire \"Au-dessus des tables : la recherche de la page, l'aper\xC3\xA7u de la fiche A4 et Imprimer\xE2\x80\xA6\"\n"
         "attendre 1.5s\n"
         "\n"
         "== 2 | Cherche une touche\n"
         ": Dans **Chercher un raccourci**, tape une touche ou un mot. Avec F8, la page montre d'abord F8 et Maj+F8, puis les lignes qui citent F8.\n"
         "texte \"champ:help.keys.search\" \"F8\"\n"
         "attendre 1s\n"
         "dire \"F8 d\xC3\xA9marre l'IHM simul\xC3\xA9" "e, sans l'API. Maj+F8 l'arr\xC3\xAAte, et l'API continue.\"\n"
         "attendre 1s\n"
         "\n"
         "== 3 | Ctrl+H et Ctrl+Maj+O\n"
         ": Ctrl+H reste \xC3\xA0 l'Historique. L'import de la configuration mat\xC3\xA9rielle (.XHW), qui le portait aussi, passe \xC3\xA0 **Ctrl+Maj+O** en 1.11.\n"
         "texte \"champ:help.keys.search\" \"Ctrl+Maj+O\"\n"
         "attendre 1s\n"
         "dire \"Ctrl+Maj+O importe la configuration mat\xC3\xA9rielle (.XHW) dans le projet ouvert.\"\n"
         "attendre 1s\n"
         "\n"
         "== 4 | La fiche A4\n"
         ": **Aper\xC3\xA7u A4** montre la fiche : toutes les touches, par contexte. **Imprimer\xE2\x80\xA6** l'\xC3\xA9" "crit en page HTML au format A4 et l'ouvre dans ton navigateur, qui l'imprime ou l'enregistre en PDF.\n"
         "clic \"bouton:Aper\xC3\xA7u A4\"\n"
         "encadrer \"bouton:Imprimer\xE2\x80\xA6\"\n"
         "attendre 1.5s\n"
         "clic \"bouton:Les tables\"\n"
         "\n"
         "== 5 | Sers-toi de la touche trouv\xC3\xA9" "e\n"
         ": \xC3\x89" "chap ferme l'aide : te voil\xC3\xA0 dans le projet. Puis F8 : l'IHM d\xC3\xA9marre.\n"
         "touche Escape\n"
         "touche F8\n"
         "attendre 1.5s\n"
         "dire \"L'IHM tourne. Maj+F8 l'arr\xC3\xAAte.\"\n"
         "@atoi Ferme l'aide avec \xC3\x89" "chap, puis appuie sur F8 : l'IHM d\xC3\xA9marre.\n"
         "@verifier simulation.ihm = marche\n"},
        {"page-signaler.tuto",
         "# La page Signaler un probl\xC3\xA8me du centre d'aide (sujet page-signaler). \xC3\x89" "crit \xC3\xA0 la main (T1, tranche 19) :\n"
         "# une page sp\xC3\xA9" "ciale n'a pas de tutoriel d\xC3\xA9" "duit (d\xC3\xA9" "cision du chef du 03/10, 12).\n"
         "# Ce que le centre en dit : \xC2\xAB Ce qui s'est pass\xC3\xA9, comment le refaire, ce que tu attendais : un zip pr\xC3\xAAt\n"
         "# \xC3\xA0 envoyer. \xC2\xBB Les notes de la 1.11 : \xC2\xAB trois questions, une capture, les pi\xC3\xA8" "ces jointes au choix, un zip\n"
         "# pr\xC3\xAAt \xC3\xA0 envoyer ; rien ne part par le r\xC3\xA9seau. \xC2\xBB\n"
         "# Le formulaire (HelpCenterScreen, id help) : les champs help.report.quoi, .attendu et .refaire, quatre\n"
         "# cases coch\xC3\xA9" "es, puis Joindre une capture, Pr\xC3\xA9parer le zip, Ouvrir le dossier, Copier le chemin et Copier\n"
         "# le texte. On ne clique aucun de ces boutons : ils \xC3\xA9" "criraient dans le dossier signalements du client, ou\n"
         "# dans son presse-papiers. @avant aide : le centre s'ouvre sur la page, par-dessus le bac.\n"
         "= page-signaler | Signaler un probl\xC3\xA8me\n"
         "@sujet page-signaler\n"
         "@bac Armoire_Gaz\n"
         "\n"
         "@avant\n"
         "aide page-signaler\n"
         "\n"
         "== 1 | Rien ne part par le r\xC3\xA9seau\n"
         ": Cette page pr\xC3\xA9pare un zip, et c'est toi qui l'envoies : l'appli n'envoie rien. Trois questions, une capture, les pi\xC3\xA8" "ces jointes au choix.\n"
         "encadrer \"bouton:Signaler un probl\xC3\xA8me  \xC2\xB7  rien n'est envoy\xC3\xA9 par le r\xC3\xA9seau\"\n"
         "dire \"Le zip part avec ton message, par le moyen que tu choisis.\"\n"
         "attendre 1.5s\n"
         "\n"
         "== 2 | Les trois questions\n"
         ": Ce qui s'est pass\xC3\xA9 (obligatoire pour le zip), ce que tu attendais, et comment le refaire, \xC3\xA9tape par \xC3\xA9tape. L'aper\xC3\xA7u, dessous, suit ce que tu \xC3\xA9" "cris : c'est le texte du zip.\n"
         "texte \"champ:help.report.quoi\" \"La vanne V_201 reste ferm\xC3\xA9" "e\"\n"
         "texte \"champ:help.report.attendu\" \"Qu'elle s'ouvre sur sa commande\"\n"
         "texte \"champ:help.report.refaire\" \"Ouvrir Vue_Tuto, F8, clic sur V_201\"\n"
         "attendre 1s\n"
         "@atoi Dans la premi\xC3\xA8re case, \xC3\xA9" "cris ce qui s'est pass\xC3\xA9 : La vanne V_201 reste ferm\xC3\xA9" "e.\n"
         "@cible \"champ:help.report.quoi\"\n"
         "@verifier champ(help.report.quoi) ~ V_201\n"
         "\n"
         "== 3 | Les pi\xC3\xA8" "ces jointes\n"
         ": Quatre cases, coch\xC3\xA9" "es : la version, le syst\xC3\xA8me, le r\xC3\xA9sum\xC3\xA9 du projet (sans ses donn\xC3\xA9" "es) et le journal. D\xC3\xA9" "coche ce que tu ne veux pas joindre.\n"
         "encadrer \"champ:help.report.refaire\"\n"
         "dire \"Les cases sont sous les trois questions. L'aper\xC3\xA7u dit tout de suite ce que le zip contiendra.\"\n"
         "attendre 1.5s\n"
         "\n"
         "== 4 | Une capture\n"
         ": **Joindre une capture** prend la fen\xC3\xAAtre telle qu'elle est, au prochain dessin. Le zip la garde sous le nom capture.png.\n"
         "encadrer \"bouton:Joindre une capture\"\n"
         "dire \"Montre d'abord l'endroit du probl\xC3\xA8me, puis joins la capture.\"\n"
         "attendre 1.5s\n"
         "\n"
         "== 5 | Le zip\n"
         ": **Pr\xC3\xA9parer le zip** l'\xC3\xA9" "crit dans le dossier signalements de tes donn\xC3\xA9" "es. **Ouvrir le dossier** ou **Copier le chemin** : tu le joins \xC3\xA0 ton message.\n"
         "encadrer \"bouton:Pr\xC3\xA9parer le zip\"\n"
         "attendre 1s\n"
         "encadrer \"bouton:Copier le chemin\"\n"
         "dire \"Copier le texte met le signalement dans le presse-papiers, sans zip.\"\n"
         "attendre 1.5s\n"},
        {"script-rampe.tuto",
         "# Le script (maquette 1.11, sc\xC3\xA8ne 3) : le script du client, sans un mot chang\xC3\xA9.\n"
         "#   IF V[0].Pos < 100 THEN V[0].Pos := V[0].Pos + 1; ELSE V[0].Pos := 0; END_IF;\n"
         "# Bac : Armoire_Gaz (V : ARRAY[0..3] OF T_VANNE). Format : v111/agents/CONCEPTION-T1.md, section 1.\n"
         "# Les dur\xC3\xA9" "es suivent la maquette : 120 ms apr\xC3\xA8s chaque geste, 900 ms apr\xC3\xA8s dire, 1,8 s en fin d'\xC3\xA9tape.\n"
         "= script-rampe | Un script : la rampe de V[0].Pos\n"
         "@sujet scripts\n"
         "@sujet script-rampe\n"
         "@bac Armoire_Gaz | Vue_Tuto\n"
         "\n"
         "# La vanne V_201 sur sa tuyauterie, pour la voir s'ouvrir \xC3\xA0 l'\xC3\xA9tape 7.\n"
         "@avant\n"
         "type T_VANNE \"Pos : REAL; Defaut : BOOL; Bouge : BOOL; Cmd : BOOL\"\n"
         "variable V \"ARRAY[0..3] OF T_VANNE\"\n"
         "vue Vue_Tuto\n"
         "poser Tuyauterie 120,262 Tuyauterie_1\n"
         "regler Tuyauterie_1 Largeur 520\n"
         "poser Vanne 400,262 V_201\n"
         "# Tranche 8 : la vanne suit V[0].Pos (l'Ouverture, cle opening) : a l'etape 7, elle s'ouvre en direct.\n"
         "regler V_201 opening \"=V[0].Pos\"\n"
         "\n"
         "== 1 | Cr\xC3\xA9" "e le script\n"
         ": Programmation g\xC3\xA9n\xC3\xA9rale \xE2\x80\xBA Scripts : **Nouveau script**. Le nom, le langage (ST : c'est lui qui s'ex\xC3\xA9" "cute), le d\xC3\xA9" "clencheur.\n"
         "clic \"arbre:IHM/Programmation g\xC3\xA9n\xC3\xA9rale\" double\n"
         "clic \"sous-onglet:Scripts g\xC3\xA9n\xC3\xA9raux\"\n"
         "clic \"outil:Nouveau script ST\"\n"
         "clic champ:1\n"
         "texte champ:1 \"Rampe_Vanne\"\n"
         "clic \"bouton:Cr\xC3\xA9" "er\"\n"
         "encadrer ligne:Rampe_Vanne\n"
         "dire \"Rampe_Vanne est dans la liste, ouvert dans l'\xC3\xA9" "diteur. Il est \xC2\xAB Appel\xC3\xA9 \xC2\xBB pour l'instant : il ne tourne pas seul.\"\n"
         "@atoi Clique Nouveau script ST, puis nomme-le Rampe_Vanne.\n"
         "@cible \"outil:Nouveau script ST\"\n"
         "@verifier script(Rampe_Vanne).declencheur <> \"\"\n"
         "\n"
         "== 2 | \xC3\x89" "cris-le, avec l'aide \xC3\xA0 la saisie\n"
         ": Le script du client. Apr\xC3\xA8s `V[0].`, l'aide \xC3\xA0 la saisie propose les membres de T_VANNE : on choisit **Pos** au clavier.\n"
         "# Tranche 8 : un script neuf commence par \"(* Rampe_Vanne *)\". Le clic a 1:1 (colonne estimee)\n"
         "# tombait apres la \"(\" : le commentaire etait coupe en deux (verificateur). Ctrl+A : on remplace tout.\n"
         "clic editeur:1:1\n"
         "touche ctrl+a\n"
         "texte \"(* Pos *)\"\n"
         "touche Return\n"
         "texte \"IF V[0].\"\n"
         "encadrer saisie:Pos\n"
         "dire \"V[0]. : V est un ARRAY[0..3] OF T_VANNE ; ses membres arrivent avec leur type. \xE2\x86\x93 choisit, Entr\xC3\xA9" "e ins\xC3\xA8re.\"\n"
         "attendre 1.4s\n"
         "touche Return\n"
         "texte \" < 100 THEN\"\n"
         "touche Return\n"
         "texte \"V[0].Pos := V[0].Pos + 1;\"\n"
         "touche Return\n"
         "texte \"ELSE\"\n"
         "touche Return\n"
         "dire \"La coloration, les num\xC3\xA9ros de ligne : le m\xC3\xAAme \xC3\xA9" "diteur que les autres scripts.\"\n"
         "@atoi \xC3\x89" "cris les quatre premi\xC3\xA8res lignes du script (jusqu'\xC3\xA0 ELSE). Tape V[0]. : l'aide \xC3\xA0 la saisie s'ouvre ; Ctrl+Espace la rouvre.\n"
         "@cible editeur:1:1\n"
         "@verifier script(Rampe_Vanne).texte ~ \"V[0].Pos := V[0].Pos + 1;\"\n"
         "\n"
         "== 3 | Une faute, expr\xC3\xA8s\n"
         ": J'\xC3\xA9" "cris **Position** au lieu de **Pos** : l'\xC3\xA9" "diteur la souligne en rouge pendant la frappe, le num\xC3\xA9ro de ligne se teinte.\n"
         "texte \"V[0].Position := 0;\"\n"
         "touche Return\n"
         "texte \"END_IF;\"\n"
         "encadrer editeur:5:10\n"
         "dire \"Ligne 5 : V[0].Position est soulign\xC3\xA9" "e. Le message est en infobulle ; Compiler le dira aussi.\"\n"
         "attendre 900ms\n"
         "\n"
         "== 4 | Compiler (F7) la trouve\n"
         ": **Compiler (F7)** contr\xC3\xB4le le script affich\xC3\xA9 : la ligne, la colonne, et le nom le plus proche (le projet entier : IHM \xE2\x80\xBA Compiler).\n"
         "survol outil:Compiler\n"
         "touche F7\n"
         "encadrer resultats-compiler\n"
         "dire \"\xC2\xAB Rampe_Vanne \xC2\xB7 5:10 \xC2\xB7 le membre Position n'existe pas dans T_VANNE : veux-tu dire Pos ? \xC2\xBB\"\n"
         "attendre 900ms\n"
         "@atoi Lance Compiler : la touche F7, ou le bouton de la barre d'outils.\n"
         "@cible outil:Compiler\n"
         "# Tranche 21 (lot final) : script(Rampe_Vanne).erreurs compte les fautes soulignees pendant la\n"
         "# frappe, deja vraies avant F7. compiler.resultats n'a de valeur qu'apres Compiler.\n"
         "@verifier compiler.resultats >= 1\n"
         "@verifier script(Rampe_Vanne).erreurs >= 1\n"
         "@bravo Compiler a trouv\xC3\xA9 la faute, avec sa ligne et sa colonne, et propose Pos.\n"
         "\n"
         "== 5 | Corrige\n"
         ": Un clic sur le r\xC3\xA9sultat place le curseur sur la faute ; on r\xC3\xA9\xC3\xA9" "crit la ligne avec **Pos**. Compiler confirme : aucune erreur.\n"
         "# Tranche 8 : le double clic de l'editeur ne choisit pas le mot (verificateur : \"PosPosition\").\n"
         "# On choisit la ligne au clavier (Debut, puis Maj+Fin) et on la reecrit.\n"
         "clic resultats-compiler\n"
         "clic editeur:5:1\n"
         "touche home\n"
         "touche maj+end\n"
         "texte \"V[0].Pos := 0;\"\n"
         "touche F7\n"
         "encadrer resultats-compiler\n"
         "dire \"Compil\xC3\xA9 : aucune erreur. Le soulignement a disparu.\"\n"
         "@atoi Corrige la faute : \xC3\xA9" "cris Pos \xC3\xA0 la place de Position, puis F7.\n"
         "@cible editeur:5:10\n"
         "@verifier script(Rampe_Vanne).erreurs = 0\n"
         "@presque script(Rampe_Vanne).texte ~ Position | Il reste Position, ligne 5.\n"
         "\n"
         "== 6 | Une minuterie de 500 ms\n"
         ": Le **D\xC3\xA9" "clencheur** : Cyclique, toutes les 500 ms. Le script tourne seul d\xC3\xA8s que l'IHM d\xC3\xA9marre.\n"
         "encadrer propriete:D\xC3\xA9" "clencheur\n"
         "clic propriete:D\xC3\xA9" "clencheur\n"
         "clic menu:Cyclique\n"
         "clic \"propriete:P\xC3\xA9riode (ms)\"\n"
         "texte \"propriete:P\xC3\xA9riode (ms)\" \"500\"\n"
         "touche Return\n"
         "dire \"\xC2\xAB Cyclique \xC2\xB7 toutes les 500 ms \xC2\xBB. Dans la liste aussi.\"\n"
         "@atoi Mets le D\xC3\xA9" "clencheur sur Cyclique et la P\xC3\xA9riode \xC3\xA0 500 ms.\n"
         "@cible propriete:D\xC3\xA9" "clencheur\n"
         "@verifier script(Rampe_Vanne).declencheur = Cyclique\n"
         "@verifier script(Rampe_Vanne).periode = 500\n"
         "\n"
         "== 7 | Simulation \xC2\xB7 IHM : la vanne s'ouvre en direct\n"
         ": D\xC3\xA9marre l'IHM (**F8**) : toutes les 500 ms, `V[0].Pos` monte de 1 ; \xC3\xA0 100, elle revient \xC3\xA0 0. La vanne de la vue suit, en direct.\n"
         "touche F8\n"
         "encadrer vue:V_201\n"
         "simuler 9s\n"
         "dire \"De 0 \xC3\xA0 100 %, puis 0. C'est le d\xC3\xA9" "faut que tu as signal\xC3\xA9 : en 1.10.0, la vue restait \xC3\xA0 12 % jusqu'au changement de page. Corrig\xC3\xA9 en 1.10.1 : chaque \xC3\xA9" "criture d'un script pr\xC3\xA9vient la vue.\"\n"
         "@atoi D\xC3\xA9marre l'IHM : F8.\n"
         "@cible vue:V_201\n"
         "@verifier simulation.ihm = marche\n"
         "@bravo La vanne suit V[0].Pos en direct. Le tutoriel suivant colore la cuve avec une expression.\n"},
        {"variables-api.tuto",
         "# API. : les variables de l'automate, par leur nom complet (1.11.1, d\xC3\xA9" "cisions 104, 115 et 119).\n"
         "# Bac : Armoire_Gaz. Son programme : les Globales, puis les unit\xC3\xA9s Gestion_armoires, Logigrammes_A et\n"
         "# Logigrammes_B ; index_armoire_utilisee est une E/S (InOut) de Gestion_armoires.\n"
         "# Il remplace le tutoriel d\xC3\xA9" "duit du sujet variables-api (T2, 7bf387b).\n"
         "# Il demande la 1.11.1 enti\xC3\xA8re : API. dans un texte \xC3\xA0 trous (API-M), API propos\xC3\xA9 par l'aide \xC3\xA0 la\n"
         "# saisie (API-V) et l'arbre des variables du programme (API-V : une ui::TableView, la cible ligne:).\n"
         "# Sur une branche qui ne les a pas, le v\xC3\xA9rificateur le dit en \xC3\xA9" "chec.\n"
         "# Format : v111/agents/CONCEPTION-T1.md, section 1.\n"
         "= variables-api | API. : les variables de l'automate\n"
         "@sujet variables-api\n"
         "@bac Armoire_Gaz | Vue_Tuto\n"
         "\n"
         "@avant\n"
         "vue Vue_Tuto\n"
         "poser Texte 370,200 Txt_Armoire\n"
         "\n"
         "== 1 | API. dans un texte \xC3\xA0 trous\n"
         ": Toute variable de l'automate s'\xC3\xA9" "crit aussi **API.** suivi de son chemin : `API.<Unit\xC3\xA9>.<variable>` pour une variable d'une unit\xC3\xA9 de programme. D\xC3\xA8s **AP**, l'aide \xC3\xA0 la saisie propose **API** en t\xC3\xAAte.\n"
         "clic vue:Txt_Armoire\n"
         "clic propriete:Texte\n"
         "texte propriete:Texte \"Armoire : {AP\"\n"
         "encadrer saisie:API\n"
         "dire \"API, en t\xC3\xAAte de la liste. Apr\xC3\xA8s API., les unit\xC3\xA9s et les globales ; apr\xC3\xA8s l'unit\xC3\xA9, ses variables.\"\n"
         "attendre 1s\n"
         "# Le nom entier, tap\xC3\xA9 : Entr\xC3\xA9" "e prendrait la premi\xC3\xA8re ligne de la liste (index_armoire_non_utilisee\n"
         "# peut passer avant). Apr\xC3\xA8s \xC2\xAB } \xC2\xBB, la liste se ferme et Entr\xC3\xA9" "e valide la case.\n"
         "texte \"I.Gestion_armoires.index_armoire_utilise\"\n"
         "encadrer saisie:index_armoire_utilisee\n"
         "attendre 1s\n"
         "texte \"e}\"\n"
         "touche Return\n"
         "encadrer vue:Txt_Armoire\n"
         "dire \"Le nom sans API. marche toujours : API. dit seulement que c'est une variable de l'automate.\"\n"
         "@atoi Choisis le texte et \xC3\xA9" "cris Armoire : {API.Gestion_armoires.index_armoire_utilisee} dans sa case Texte.\n"
         "@cible vue:Txt_Armoire\n"
         "@verifier objet(Txt_Armoire).text = \"Armoire : {API.Gestion_armoires.index_armoire_utilisee}\"\n"
         "\n"
         "== 2 | L'arbre des variables du programme\n"
         ": IHM \xE2\x80\xBA **Configuration** \xE2\x80\xBA **Variables du programme** : d'abord les **Globales**, puis une branche par **unit\xC3\xA9 de programme**, ses variables rang\xC3\xA9" "es en **Publiques**, **Priv\xC3\xA9" "es** et **E/S**. La recherche trouve un nom dans tout l'arbre.\n"
         "clic \"arbre:IHM/Configuration\"\n"
         "encadrer \"ligne:Globales\"\n"
         "dire \"Le cadenas : un nom de l'automate ne se renomme pas ici ; il se renomme dans Control Expert.\"\n"
         "attendre 1s\n"
         "# Les Globales (251) et les unit\xC3\xA9s sont d\xC3\xA9pli\xC3\xA9" "es \xC3\xA0 l'ouverture, Logigrammes_A d'abord : Gestion_armoires est\n"
         "# sous l'\xC3\xA9" "cran (vu au v\xC3\xA9rificateur, binaire d'API-V, 13 h 04 et 13 h 09). La recherche d\xC3\xA9plie ce qui y m\xC3\xA8ne.\n"
         "texte \"champ:hmi.config.vars.search\" \"index_armoire_utilisee\"\n"
         "attendre 1s\n"
         "# Deux lignes de ce nom : la globale (la premiere, ligne: la prendrait) et l'E/S de Gestion_armoires\n"
         "# (vu au verificateur, 13 h 11) : j'encadre E/S, la seule visible apres la recherche.\n"
         "encadrer \"ligne:E/S\"\n"
         "dire \"Deux index_armoire_utilisee : la globale (API.index_armoire_utilisee) et l'E/S de Gestion_armoires, employ\xC3\xA9" "e une fois : par le texte de l'\xC3\xA9tape 1. Accessible : L/\xC3\x89, L, ou sans adresse (simulation seulement).\"\n"
         "attendre 1s\n"},
        {"variables-instances.tuto",
         "# Variables d'instances : le groupe d'alarmes et les alarmes d'un objet (1.11.1, d\xC3\xA9" "cisions 108 et 115).\n"
         "# Bac : Armoire_Gaz. Une pompe dont le d\xC3\xA9" "faut suit Pompe_Defaut : son alarme Defaut, son groupe\n"
         "# d'alarmes Vue_Tuto.Pompe_1. Il remplace le tutoriel d\xC3\xA9" "duit du sujet variables-instances.\n"
         "# Format : v111/agents/CONCEPTION-T1.md, section 1.\n"
         "= variables-instances | Variables d'instances : les alarmes d'un objet\n"
         "@sujet variables-instances\n"
         "@bac Armoire_Gaz | Vue_Tuto\n"
         "\n"
         "@avant\n"
         "variable Pompe_Defaut BOOL\n"
         "vue Vue_Tuto\n"
         "poser Pompe 400,262 Pompe_1\n"
         "regler Pompe_1 fault \"=Pompe_Defaut\"\n"
         "\n"
         "== 1 | Ouvre Variables d'instances\n"
         ": IHM \xE2\x80\xBA Programmation g\xC3\xA9n\xC3\xA9rale \xE2\x80\xBA **Variables d'instances** : chaque vue, puis chaque objet, et tout ce qu'il publie.\n"
         "clic \"arbre:IHM/Programmation\" double\n"
         "clic \"arbre:IHM/Programmation/Variables d'instances\" double\n"
         "clic \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto\" double\n"
         "clic \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1\" double\n"
         "encadrer \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1\"\n"
         "dire \"Sous Pompe_1 : ses variables (Visible, Value\xE2\x80\xA6), puis son groupe d'alarmes et ses alarmes.\"\n"
         "\n"
         "== 2 | Son groupe d'alarmes\n"
         ": **Groupe d'alarmes Vue_Tuto.Pompe_1** : ce que le moteur sait de ses alarmes (AlarmActive, AlarmCount\xE2\x80\xA6) et **AlarmLinkedGroup**, le groupe de l'IHM auquel il est li\xC3\xA9.\n"
         "clic \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1/Groupe d'alarmes\" double\n"
         "encadrer \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1/Groupe d'alarmes/AlarmLinkedGroup\"\n"
         "dire \"Toutes en lecture (R) : Vue_Tuto.Pompe_1.AlarmActive, .AlarmCount, .AlarmLinkedGroup\xE2\x80\xA6\"\n"
         "\n"
         "== 3 | Ses alarmes\n"
         ": **Alarmes \xE2\x80\xBA Defaut** : chaque alarme de l'objet a ses variables. **Acked** et **Shelved** s'\xC3\xA9" "crivent (R/W) : acquitter, mettre de c\xC3\xB4t\xC3\xA9 ; le reste se lit.\n"
         "clic \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1/Alarmes\" double\n"
         "clic \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1/Alarmes/Defaut\" double\n"
         "clic \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1/Alarmes/Defaut/Acked\"\n"
         "encadrer \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1/Alarmes/Defaut/Acked\"\n"
         "dire \"Vue_Tuto.Pompe_1.Alarmes.Defaut.Acked := TRUE acquitte l'alarme, dans un script ou une action.\"\n"
         "# Tranche 34 : la demonstration finit sur Shelved, ce que verifie l'\xC2\xAB A toi \xC2\xBB (le verificateur joue les gestes de\n"
         "# l'etape, puis la verification : finir sur Acked laissait volet.variable a ...Defaut.Acked).\n"
         "clic \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1/Alarmes/Defaut/Shelved\"\n"
         "encadrer \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1/Alarmes/Defaut/Shelved\"\n"
         "dire \"Vue_Tuto.Pompe_1.Alarmes.Defaut.Shelved := TRUE la met de c\xC3\xB4t\xC3\xA9 : elle quitte la liste des alarmes.\"\n"
         "# Au debut de l'\xC2\xAB A toi \xC2\xBB, l'arbre est tel qu'apres l'etape 2 : Alarmes est encore replie.\n"
         "@atoi Dans l'arbre, d\xC3\xA9plie Alarmes \xE2\x80\xBA Defaut, puis choisis la variable Shelved : le volet la montre.\n"
         "@cible \"arbre:IHM/Programmation/Variables d'instances/Vue_Tuto/Pompe_1/Alarmes\"\n"
         "@verifier volet.variable = \"Vue_Tuto.Pompe_1.Alarmes.Defaut.Shelved\"\n"},
    };
    return all;
}

} // namespace help
