# XpgAnalyzer - vue IHM (format 19)
vue id=1 nom="Vue_Accueil" description="" largeur=1920 hauteur=1080 fond="#20242B" calque_actif=2 modele=24 entete=1 entete_vue=26 pied=1 pied_vue=28
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=2 nom="Calque 1" visible=1 verrou=0
objet id=3 type=Text nom="Text_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="130"
prop cle=y valeur="190"
prop cle=w valeur="160"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Voiture de course"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=5 type=Button nom="Button_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="100"
prop cle=y valeur="240"
prop cle=w valeur="140"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Bouton"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
prop cle=blink valeur=""
objet id=6 type=Trend nom="Trend_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="522"
prop cle=y valeur="368"
prop cle=w valeur="520"
prop cle=h valeur="260"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=variables valeur="0"
prop cle=duration valeur="60"
prop cle=ymin valeur="0"
prop cle=ymax valeur="100"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
prop cle=blink valeur=""
prop cle=names valeur="Plume 1"
prop cle=colors valeur="#4FA3FF;#F2994A"
objet id=7 type=Container nom="Container_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="1042"
prop cle=y valeur="90"
prop cle=w valeur="400"
prop cle=h valeur="300"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=strokeWidth valeur="1"
prop cle=clip valeur="TRUE"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=8 type=Table nom="Table_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="522"
prop cle=y valeur="670"
prop cle=w valeur="420"
prop cle=h valeur="219.803"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=columns valeur="Nom;Valeur;Unité"
prop cle=rows valeur="6"
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
prop cle=cells valeur="\t\t\n\t\t\n\t\t\n\t\t\n\t\t\n\t\t"
prop cle=widths valeur=""
objet id=9 type=Indicator nom="Indicator_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="290"
prop cle=y valeur="190"
prop cle=w valeur="32"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="FALSE"
prop cle=colorOn valeur="#2ECC71"
prop cle=colorOff valeur="#4A5261"
prop cle=stroke valeur="#1B1F26"
prop cle=strokeWidth valeur="1"
prop cle=shape valeur="rond"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=15 type=Image nom="Image_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="1220"
prop cle=y valeur="620"
prop cle=w valeur="128"
prop cle=h valeur="128"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="logo"
prop cle=stretch valeur="ajuster"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=30 type=AnimatedImage nom="AnimatedImage_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="1470"
prop cle=y valeur="370"
prop cle=w valeur="128"
prop cle=h valeur="128"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=states valeur="TRUE => "
prop cle=image valeur=""
prop cle=period valeur="500"
prop cle=stretch valeur="ajuster"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=39 type=Rectangle nom="Rectangle_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="210"
prop cle=y valeur="767.901"
prop cle=w valeur="160"
prop cle=h valeur="100"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#3A4556"
prop cle=stroke valeur="#8A9BB0"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="0"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=40 type=LoginPanel nom="LoginPanel_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="1534"
prop cle=y valeur="699.901"
prop cle=w valeur="340"
prop cle=h valeur="236"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Connexion"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#E6EAF0"
prop cle=userList valeur="TRUE"
prop cle=buttonText valeur="Se connecter"
prop cle=afterLogin valeur=""
prop cle=keyboard valeur="aucun"
prop cle=fill valeur="#1F252E"
prop cle=stroke valeur="#3A4556"
prop cle=accent valeur="#2F6FD6"
prop cle=radius valeur="6"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=41 type=UserInfo nom="UserInfo_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="1590"
prop cle=y valeur="100"
prop cle=w valeur="300"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=display valeur="{nom}  ({groupe}, niveau {niveau})"
prop cle=empty valeur="Aucun utilisateur connecté"
prop cle=icon valeur="TRUE"
prop cle=fill valeur="#1F252E"
prop cle=stroke valeur="#3A4556"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=42 type=WeeklySchedule nom="WeeklySchedule_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="350"
prop cle=y valeur="90"
prop cle=w valeur="580"
prop cle=h valeur="236"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=schedule valeur="Lu-Ve=07:00-12:00,13:30-17:00"
prop cle=resolution valeur="30 min"
prop cle=output valeur=""
prop cle=font valeur="Sans"
prop cle=fontSize valeur="12"
prop cle=textColor valeur="#C8D0DC"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=accent valeur="#2ECC71"
prop cle=nowColor valeur="#F2994A"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=45 type=SymbolInstance nom="Symbole_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="1464"
prop cle=y valeur="524"
prop cle=w valeur="240"
prop cle=h valeur="160"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=symbol valeur="Symbole"
prop cle=params valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=115 type=ThemeSelector nom="ThemeSelector_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="1180"
prop cle=y valeur="860"
prop cle=w valeur="240"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=themeLabels valeur="Jour;Nuit"
prop cle=icon valeur="TRUE"
prop cle=orientation valeur="horizontale"
prop cle=gap valeur="4"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#C8D0DC"
prop cle=activeTextColor valeur="#FFFFFF"
prop cle=buttonColor valeur="#2A313C"
prop cle=activeColor valeur="#2F6FD6"
prop cle=fill valeur=""
prop cle=stroke valeur="#3A4556"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="5"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=135 type=AnimatedGif nom="AnimatedGif_1" calque=2 parent=0 verrou=0 cache=0
prop cle=x valeur="1670"
prop cle=y valeur="180"
prop cle=w valeur="128"
prop cle=h valeur="128"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur=""
prop cle=play valeur="en boucle"
prop cle=count valeur="3"
prop cle=speed valeur="100"
prop cle=start valeur="à l'affichage"
prop cle=condition valeur=""
prop cle=end valeur="dernière image"
prop cle=stretch valeur="ajuster"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
script id=16 nom="Vue_Accueil_OnOpen" langage=ST evenement=OnOpen corps="IF Vue.Indicator_1.Enabled THEN\n test := test + 1;\nEND_IF"
action objet=5 declencheur="Clic" operation="Paramètres système"
action objet=9 declencheur="Clic" operation="Mettre à 1" cible="Variable"
action objet=39 declencheur="Appui long" delai=800 operation="Paramètres système"
action objet=42 declencheur="Clic" operation="Mettre à 1"
fin
