# XpgAnalyzer - vue IHM (format 19)
vue id=626 nom="Vue_GIF" description="Les GIF animes : sur action, sur condition, a l'affichage" largeur=1280 hauteur=800 fond="#20242B" calque_actif=627
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=627 nom="Calque 1" visible=1 verrou=0
objet id=628 type=AnimatedGif nom="Ventilo" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="60"
prop cle=y valeur="110"
prop cle=w valeur="220"
prop cle=h valeur="220"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="ventilateur.gif"
prop cle=play valeur="en boucle"
prop cle=count valeur="3"
prop cle=speed valeur="100"
prop cle=start valeur="sur action"
prop cle=condition valeur=""
prop cle=end valeur="dernière image"
prop cle=stretch valeur="ajuster"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=629 type=AnimatedGif nom="Convoyeur_Anim" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="360"
prop cle=y valeur="150"
prop cle=w valeur="480"
prop cle=h valeur="192"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="convoyeur.gif"
prop cle=play valeur="en boucle"
prop cle=count valeur="3"
prop cle=speed valeur="100"
prop cle=start valeur="sur condition"
prop cle=condition valeur="Marche_Ligne"
prop cle=end valeur="dernière image"
prop cle=stretch valeur="ajuster"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=630 type=AnimatedGif nom="Chargement" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="960"
prop cle=y valeur="150"
prop cle=w valeur="160"
prop cle=h valeur="160"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="chargement.gif"
prop cle=play valeur="N fois"
prop cle=count valeur="3"
prop cle=speed valeur="100"
prop cle=start valeur="à l'affichage"
prop cle=condition valeur=""
prop cle=end valeur="caché"
prop cle=stretch valeur="ajuster"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=631 type=Image nom="Image_Gif" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="960"
prop cle=y valeur="420"
prop cle=w valeur="160"
prop cle=h valeur="160"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="ventilateur.gif"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur=""
prop cle=recolorMode valeur="tout"
prop cle=recolorFrom valeur="#000000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=632 type=Text nom="Titre_GIF" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="60"
prop cle=y valeur="30"
prop cle=w valeur="1100"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Les GIF animés : sur action, sur condition (Marche_Ligne), 3 fois à l'affichage ; une Image qui boucle"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="24"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=633 type=Text nom="Etat_Ventilo" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="60"
prop cle=y valeur="360"
prop cle=w valeur="700"
prop cle=h valeur="40"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Ventilo : {Vue_GIF.Ventilo.Playing:joue|arrêté} · image {Vue_GIF.Ventilo.Frame} / {Vue_GIF.Ventilo.FrameCount} · tours {Vue_GIF.Ventilo.Loops}"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="18"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=634 type=Text nom="Etat_Convoyeur" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="360"
prop cle=y valeur="400"
prop cle=w valeur="480"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Convoyeur : {Marche_Ligne:en marche|arrêté} · tours {Vue_GIF.Convoyeur_Anim.Loops}"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=635 type=Button nom="Btn_Jouer" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="60"
prop cle=y valeur="440"
prop cle=w valeur="150"
prop cle=h valeur="50"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Jouer"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=636 type=Button nom="Btn_Pause" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="230"
prop cle=y valeur="440"
prop cle=w valeur="150"
prop cle=h valeur="50"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Pause"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=637 type=Button nom="Btn_Arreter" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="400"
prop cle=y valeur="440"
prop cle=w valeur="150"
prop cle=h valeur="50"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Arrêter"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=638 type=Button nom="Btn_Rejouer" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="570"
prop cle=y valeur="440"
prop cle=w valeur="190"
prop cle=h valeur="50"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Rejouer 2 fois"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=639 type=Button nom="Btn_Ligne" calque=627 parent=0 verrou=0 cache=0
prop cle=x valeur="360"
prop cle=y valeur="520"
prop cle=w valeur="240"
prop cle=h valeur="50"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="{Marche_Ligne:Arrêter la ligne|Démarrer la ligne}"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
action objet=635 declencheur="Clic" operation="Jouer le GIF" cible="Ventilo"
action objet=636 declencheur="Clic" operation="Mettre le GIF en pause" cible="Ventilo"
action objet=637 declencheur="Clic" operation="Arrêter le GIF" cible="Ventilo"
action objet=638 declencheur="Clic" operation="Rejouer le GIF N fois" cible="Ventilo" valeur="2"
action objet=639 declencheur="Clic" operation="Basculer" cible="Marche_Ligne"
fin
