# XpgAnalyzer - vue IHM (format 19)
vue id=158 nom="Popup_Armoire" description="Le detail d'une armoire : celle que donne l'appelant" largeur=480 hauteur=320 fond="#20242B" calque_actif=159 role=popup popup_titre=1 popup_libelle="Armoire {Nom}  -  {Armoire.ana.PT1.mes:0.0} bar" popup_modale=0 popup_deplacable=1 popup_fermer=1 popup_dehors=0 popup_position="centre"
parametre nom="Armoire" defaut="Armoires[0]" description=""
parametre nom="Nom" defaut="'A'" description=""
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=159 nom="Calque 1" visible=1 verrou=0
objet id=160 type=Text nom="Titre" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="12"
prop cle=w valeur="440"
prop cle=h valeur="34"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Équipement"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="20"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=161 type=Indicator nom="Voyant_Marche" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="24"
prop cle=y valeur="70"
prop cle=w valeur="32"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="FALSE" expr="Equipement.Marche"
prop cle=colorOn valeur="#2ECC71"
prop cle=colorOff valeur="#4A5261"
prop cle=stroke valeur="#1B1F26"
prop cle=strokeWidth valeur="1"
prop cle=shape valeur="rond"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=162 type=Text nom="Etat" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="68"
prop cle=y valeur="70"
prop cle=w valeur="200"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="{Equipement.Marche:En marche|À l'arrêt}"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=163 type=NumericDisplay nom="Mesure" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="24"
prop cle=y valeur="120"
prop cle=w valeur="432"
prop cle=h valeur="56"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="0" expr="Equipement.Mesure"
prop cle=format valeur="0.0"
prop cle=unit valeur=""
prop cle=label valeur="Mesure"
prop cle=lowAlarm valeur=""
prop cle=low valeur=""
prop cle=high valeur=""
prop cle=highAlarm valeur=""
prop cle=font valeur="Sans"
prop cle=fontSize valeur="24"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="droite"
prop cle=colorWarning valeur="#F2C94C"
prop cle=colorAlarm valeur="#E5534B"
prop cle=fill valeur="#141820"
prop cle=stroke valeur="#3A4556"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=164 type=Button nom="Btn_Marche" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="24"
prop cle=y valeur="200"
prop cle=w valeur="210"
prop cle=h valeur="48"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Marche"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=165 type=Button nom="Btn_Arret" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="246"
prop cle=y valeur="200"
prop cle=w valeur="210"
prop cle=h valeur="48"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Arrêt"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=166 type=Rectangle nom="Fond_Armoire" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="0"
prop cle=y valeur="0"
prop cle=w valeur="560"
prop cle=h valeur="380"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#243044"
prop cle=stroke valeur="#3A6EA5"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="0"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=167 type=Text nom="Titre_Armoire" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="10"
prop cle=w valeur="510"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoire {Nom} : {Armoire.ana.PT1.mes:0.0} bar"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="22"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=168 type=Gauge nom="Jauge_Armoire" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="60"
prop cle=w valeur="180"
prop cle=h valeur="180"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="40" expr="Armoire.ana.PT1.mes"
prop cle=min valeur="0"
prop cle=max valeur="40"
prop cle=unit valeur="bar"
prop cle=fill valeur="#2F6FD6"
prop cle=background valeur="#2A313C"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=169 type=Text nom="Libelle_Seuil" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="280"
prop cle=y valeur="70"
prop cle=w valeur="250"
prop cle=h valeur="30"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Seuil de poids :"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=170 type=InputField nom="Saisie_Seuil" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="280"
prop cle=y valeur="110"
prop cle=w valeur="180"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="droite"
prop cle=mode valeur="numérique"
prop cle=format valeur="0.0"
prop cle=min valeur="0"
prop cle=max valeur="60"
prop cle=unit valeur="kg"
prop cle=maxLength valeur="32"
prop cle=placeholder valeur=""
prop cle=keyboard valeur="numérique"
prop cle=validateOnExit valeur="FALSE"
prop cle=fill valeur="#141820"
prop cle=stroke valeur="#4A5568"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="3"
prop cle=variable valeur="Armoire.seuil_poids_saisi"
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=171 type=Text nom="Seuil_Enregistre" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="280"
prop cle=y valeur="160"
prop cle=w valeur="250"
prop cle=h valeur="30"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Enregistré : {Armoire.seuil_poids_saisi:0.0} kg"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#9CC3E6"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=172 type=Button nom="Btn_Vers_B" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="320"
prop cle=w valeur="170"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Voir l'armoire B"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=173 type=Button nom="Btn_Precedente" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="200"
prop cle=y valeur="320"
prop cle=w valeur="120"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Précédente"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=174 type=Button nom="Btn_Centrer" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="330"
prop cle=y valeur="320"
prop cle=w valeur="100"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Centrer"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=175 type=Button nom="Btn_Fermer_Armoire" calque=159 parent=0 verrou=0 cache=0
prop cle=x valeur="440"
prop cle=y valeur="320"
prop cle=w valeur="100"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Fermer"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
action objet=164 declencheur="Clic" operation="Mettre à 1" cible="Equipement.Marche"
action objet=165 declencheur="Clic" operation="Mettre à 0" cible="Equipement.Marche"
action objet=172 declencheur="Clic" operation="Changer de popup" cible="Popup_Armoire" valeur="Armoire := Armoires[1]; Nom := 'B'" transition="Fondu" duree=300 direction="gauche" courbe="douce"
action objet=173 declencheur="Clic" operation="Popup précédente"
action objet=174 declencheur="Clic" operation="Centrer la popup"
action objet=175 declencheur="Clic" operation="Fermer la popup" transition="Instantanée" duree=400 direction="gauche" courbe="douce"
fin
