# XpgAnalyzer - vue IHM (format 19)
vue id=186 nom="Vue_Utilisateurs" description="Connexion, mot de passe et comptes" largeur=1280 hauteur=800 fond="#20242B" calque_actif=187
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=187 nom="Calque 1" visible=1 verrou=0
objet id=188 type=Text nom="Titre_Utilisateurs" calque=187 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="20"
prop cle=w valeur="700"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Utilisateurs et droits"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="28"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=189 type=UserInfo nom="Info_Utilisateur" calque=187 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="80"
prop cle=w valeur="560"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=display valeur="{nom}  ({groupe}, niveau {niveau})  -  depuis {depuis}"
prop cle=empty valeur="Aucun utilisateur connecté"
prop cle=icon valeur="TRUE"
prop cle=fill valeur="#1F252E"
prop cle=stroke valeur="#3A4556"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=190 type=Text nom="Texte_Fonctions" calque=187 parent=0 verrou=0 cache=0
prop cle=x valeur="640"
prop cle=y valeur="90"
prop cle=w valeur="600"
prop cle=h valeur="30"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="IHM_UTILISATEUR() = {IHM_UTILISATEUR()}    IHM_NIVEAU() = {IHM_NIVEAU()}"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#9CC3E6"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=191 type=LogoutButton nom="Btn_Deconnexion" calque=187 parent=0 verrou=0 cache=0
prop cle=x valeur="1050"
prop cle=y valeur="20"
prop cle=w valeur="190"
prop cle=h valeur="40"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Se déconnecter"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=showUser valeur="TRUE"
prop cle=confirm valeur="TRUE"
prop cle=fill valeur="#8A3A3A"
prop cle=stroke valeur="#5E2626"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=192 type=LoginPanel nom="Panneau_Connexion" calque=187 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="150"
prop cle=w valeur="340"
prop cle=h valeur="236"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Connexion"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#E6EAF0"
prop cle=userList valeur="TRUE"
prop cle=buttonText valeur="Se connecter"
prop cle=afterLogin valeur=""
prop cle=keyboard valeur="complet"
prop cle=fill valeur="#1F252E"
prop cle=stroke valeur="#3A4556"
prop cle=accent valeur="#2F6FD6"
prop cle=radius valeur="6"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=193 type=PasswordChange nom="Panneau_Mot_De_Passe" calque=187 parent=0 verrou=0 cache=0
prop cle=x valeur="420"
prop cle=y valeur="150"
prop cle=w valeur="340"
prop cle=h valeur="290"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Changer le mot de passe"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#E6EAF0"
prop cle=minLength valeur="6"
prop cle=requireDigit valeur="TRUE"
prop cle=buttonText valeur="Changer"
prop cle=keyboard valeur="aucun"
prop cle=fill valeur="#1F252E"
prop cle=stroke valeur="#3A4556"
prop cle=accent valeur="#2F6FD6"
prop cle=radius valeur="6"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=194 type=UserManager nom="Gestion_Utilisateurs" calque=187 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="470"
prop cle=w valeur="1200"
prop cle=h valeur="300"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=buttons valeur="Ajouter;Modifier;Supprimer;Activer;Mot de passe"
prop cle=fontSize valeur="13"
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=textColor valeur="#DDE3EA"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
fin
