# XpgAnalyzer - vue IHM (format 19)
vue id=125 nom="Entete_Conduite" description="Bandeau commun" largeur=1280 hauteur=80 fond="#20242B" calque_actif=126 role=entete
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=126 nom="Calque 1" visible=1 verrou=0
objet id=127 type=Rectangle nom="Bande_Entete" calque=126 parent=0 verrou=0 cache=0
prop cle=x valeur="0"
prop cle=y valeur="0"
prop cle=w valeur="1280"
prop cle=h valeur="80"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#16324F"
prop cle=stroke valeur="#8A9BB0"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="0"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=128 type=Text nom="Titre_Entete" calque=126 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="20"
prop cle=w valeur="760"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="ARMOIRES DE GAZ  -  {Message_Operateur}"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="26"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=129 type=Text nom="Clics_Entete" calque=126 parent=0 verrou=0 cache=0
prop cle=x valeur="880"
prop cle=y valeur="20"
prop cle=w valeur="260"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Clics : {Compteur_Clics:000}"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="18"
prop cle=textColor valeur="#9CC3E6"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=130 type=Indicator nom="Voyant_Maintenance" calque=126 parent=0 verrou=0 cache=0
prop cle=x valeur="1210"
prop cle=y valeur="20"
prop cle=w valeur="32"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="FALSE" expr="Mode_Maintenance"
prop cle=colorOn valeur="#2ECC71"
prop cle=colorOff valeur="#4A5261"
prop cle=stroke valeur="#1B1F26"
prop cle=strokeWidth valeur="1"
prop cle=shape valeur="rond"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
fin
