# XpgAnalyzer - vue IHM (format 19)
vue id=119 nom="Modele_Conduite" description="Cadre et navigation des vues de conduite" largeur=1280 hauteur=800 fond="#20242B" calque_actif=120 role=modele
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=120 nom="Calque 1" visible=1 verrou=0
objet id=121 type=Rectangle nom="Cadre_Modele" calque=120 parent=0 verrou=0 cache=0
prop cle=x valeur="0"
prop cle=y valeur="0"
prop cle=w valeur="1280"
prop cle=h valeur="800"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#1A2029"
prop cle=stroke valeur="#3A6EA5"
prop cle=strokeWidth valeur="3"
prop cle=radius valeur="0"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=122 type=Rectangle nom="Barre_Navigation" calque=120 parent=0 verrou=0 cache=0
prop cle=x valeur="1160"
prop cle=y valeur="100"
prop cle=w valeur="110"
prop cle=h valeur="620"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#243044"
prop cle=stroke valeur="#3A6EA5"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="8"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=123 type=Button nom="Btn_Modele_Accueil" calque=120 parent=0 verrou=0 cache=0
prop cle=x valeur="1170"
prop cle=y valeur="120"
prop cle=w valeur="90"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Accueil"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=124 type=Button nom="Btn_Modele_Aide" calque=120 parent=0 verrou=0 cache=0
prop cle=x valeur="1170"
prop cle=y valeur="190"
prop cle=w valeur="90"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Aide"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
action objet=0 declencheur="Ouverture de la vue" operation="Journaliser" valeur="Écran modèle : cadre et navigation en place"
action objet=123 declencheur="Clic" operation="Naviguer" cible="Vue_Supervision" transition="Glissement" duree=400 direction="gauche" courbe="douce"
action objet=124 declencheur="Clic" operation="Ouvrir une popup" cible="Popup_Aide" transition="Fondu" duree=300 direction="gauche" courbe="douce"
fin
