# XpgAnalyzer - vue IHM (format 19)
vue id=350 nom="Vue_Graphiques" description="Barres, courbe XY, chronogramme, camembert, radar, histogramme" largeur=1280 hauteur=800 fond="#20242B" calque_actif=351
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=351 nom="Calque 1" visible=1 verrou=0
objet id=352 type=Text nom="Titre_Graphiques" calque=351 parent=0 verrou=0 cache=0
prop cle=x valeur="30"
prop cle=y valeur="14"
prop cle=w valeur="1100"
prop cle=h valeur="40"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Graphiques : niveaux, énergie, santé de la pompe, essai, états, pesées"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="22"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=353 type=BarChart nom="Barres_Niveaux" calque=351 parent=0 verrou=0 cache=0
prop cle=x valeur="30"
prop cle=y valeur="66"
prop cle=w valeur="400"
prop cle=h valeur="310"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Niveaux à {SYS.Time}"
prop cle=fontSize valeur="12"
prop cle=textColor valeur="#9AA6B8"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=variables valeur="Niveau_Cuve;Niveau_Silo;Charge_Tremie;Position_Verin"
prop cle=names valeur="Cuve T1;Silo S1;Trémie 3;Vérin V3"
prop cle=colors valeur="#4FA3FF;#F2994A;#2ECC71;#B98CFF;#B98CFF;#F1C40F"
prop cle=orientation valeur="verticale"
prop cle=scale valeur="fixe"
prop cle=min valeur="0"
prop cle=max valeur="100"
prop cle=format valeur="0.0"
prop cle=unit valeur="%"
prop cle=showValue valeur="TRUE"
prop cle=low valeur="20"
prop cle=high valeur="85"
prop cle=colorAlarm valeur="#E5534B"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=354 type=PieChart nom="Anneau_Energie" calque=351 parent=0 verrou=0 cache=0
prop cle=x valeur="450"
prop cle=y valeur="66"
prop cle=w valeur="370"
prop cle=h valeur="310"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Énergie par poste (kW)"
prop cle=fontSize valeur="12"
prop cle=textColor valeur="#9AA6B8"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=variables valeur="Debit_Ligne * 0.6; Pression_Ligne * 6.0; Temperature_Local * 2.0; 18.0"
prop cle=names valeur="Compresseur; Pompe P-101; Chauffage; Éclairage"
prop cle=colors valeur="#4FA3FF;#F2994A;#2ECC71;#E5534B;#B98CFF;#F1C40F"
prop cle=hole valeur="52"
prop cle=labelMode valeur="pourcentage"
prop cle=format valeur="0"
prop cle=unit valeur="kW"
prop cle=legend valeur="TRUE"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=355 type=RadarChart nom="Radar_Pompe" calque=351 parent=0 verrou=0 cache=0
prop cle=x valeur="840"
prop cle=y valeur="66"
prop cle=w valeur="410"
prop cle=h valeur="310"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Santé de la pompe P-101 (%)"
prop cle=fontSize valeur="12"
prop cle=textColor valeur="#9AA6B8"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=variables valeur="Pression_Ligne * 7.0; Temperature_Local * 3.0; Niveau_Cuve; Debit_Ligne / 1.6; Vitesse_Pompe; Vibration_Pompe"
prop cle=names valeur="Pression; Température; Niveau; Débit; Vitesse; Vibration"
prop cle=colors valeur="#4FA3FF"
prop cle=min valeur="0"
prop cle=max valeur="100"
prop cle=references valeur="70; 65; 60; 75; 45; 60"
prop cle=referenceColor valeur="#F2C94C"
prop cle=rings valeur="4"
prop cle=showValue valeur="TRUE"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=356 type=XYChart nom="Courbe_Pompe" calque=351 parent=0 verrou=0 cache=0
prop cle=x valeur="30"
prop cle=y valeur="396"
prop cle=w valeur="440"
prop cle=h valeur="380"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Essai de la pompe P-101"
prop cle=fontSize valeur="12"
prop cle=textColor valeur="#9AA6B8"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=xVariable valeur="Debit_Essai"
prop cle=variables valeur="Pression_Essai"
prop cle=names valeur="Pression mesurée"
prop cle=colors valeur="#4FA3FF;#F2994A;#2ECC71;#E5534B"
prop cle=xmin valeur="0"
prop cle=xmax valeur="100"
prop cle=ymin valeur="0"
prop cle=ymax valeur="10"
prop cle=scale valeur="fixe"
prop cle=xLabel valeur="Débit (m³/h)"
prop cle=yLabel valeur="Pression (bar)"
prop cle=reference valeur="0,9.2 20,8.9 40,8.1 60,6.8 80,5.0 100,2.6"
prop cle=referenceColor valeur="#9AA6B8"
prop cle=tolerance valeur="0.5"
prop cle=maxPoints valeur="240"
prop cle=interpolation valeur="linéaire"
prop cle=reset valeur=""
prop cle=legend valeur="TRUE"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=357 type=StateChart nom="Chronogramme" calque=351 parent=0 verrou=0 cache=0
prop cle=x valeur="490"
prop cle=y valeur="396"
prop cle=w valeur="400"
prop cle=h valeur="200"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="États de la ligne"
prop cle=fontSize valeur="12"
prop cle=textColor valeur="#9AA6B8"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=variables valeur="Etat_Pompe; Pompe_Marche; Marche_Ligne"
prop cle=names valeur="Pompe P-101; Commande; Ligne"
prop cle=duration valeur="40"
prop cle=stateList valeur="0 = Arrêt | #4A5261; 1 = Marche | #2ECC71; 2 = Défaut | #E5534B"
prop cle=showText valeur="TRUE"
prop cle=legend valeur="TRUE"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=358 type=Histogram nom="Pesees" calque=351 parent=0 verrou=0 cache=0
prop cle=x valeur="910"
prop cle=y valeur="396"
prop cle=w valeur="340"
prop cle=h valeur="380"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Pesées des sachets (g)"
prop cle=fontSize valeur="12"
prop cle=textColor valeur="#9AA6B8"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur="Poids_Sachet"
prop cle=min valeur="494"
prop cle=max valeur="507"
prop cle=bins valeur="13"
prop cle=window valeur="600"
prop cle=samplePeriod valeur="200"
prop cle=maxSamples valeur="5000"
prop cle=low valeur="495"
prop cle=high valeur="505"
prop cle=colors valeur="#4FA3FF"
prop cle=showStats valeur="TRUE"
prop cle=format valeur="0.00"
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=359 type=Text nom="Note_Graphiques" calque=351 parent=0 verrou=0 cache=0
prop cle=x valeur="490"
prop cle=y valeur="616"
prop cle=w valeur="400"
prop cle=h valeur="150"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Barres, anneau et radar suivent leurs expressions à chaque image ; la courbe XY, le chronogramme et l'histogramme ont une mémoire, mesurée à chaque cycle IHM."
prop cle=font valeur="Sans"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="TRUE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
fin
