# XpgAnalyzer - vue IHM (format 19)
vue id=107 nom="Vue_Supervision" description="Alarmes, courbes, recettes et utilisateurs" largeur=1280 hauteur=800 fond="#20242B" calque_actif=108
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=108 nom="Calque 1" visible=1 verrou=0
objet id=109 type=Text nom="Titre_Supervision" calque=108 parent=0 verrou=0 cache=0
prop cle=x valeur="30"
prop cle=y valeur="20"
prop cle=w valeur="820"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Supervision - alarmes, courbes, recettes"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="24"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=110 type=History nom="Hist_Alarmes" calque=108 parent=0 verrou=0 cache=0
prop cle=x valeur="30"
prop cle=y valeur="80"
prop cle=w valeur="820"
prop cle=h valeur="230"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=source valeur="historique"
prop cle=group valeur=""
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=111 type=Trend nom="Courbe_Pressions" calque=108 parent=0 verrou=0 cache=0
prop cle=x valeur="30"
prop cle=y valeur="320"
prop cle=w valeur="820"
prop cle=h valeur="260"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=variables valeur="Armoires[0].ana.PT1.mes; Armoires[1].ana.PT1.mes"
prop cle=mode valeur="temps réel"
prop cle=source valeur=""
prop cle=duration valeur="60"
prop cle=scale valeur="auto"
prop cle=ymin valeur="0"
prop cle=ymax valeur="100"
prop cle=colors valeur="#4FA3FF;#F2994A;#2ECC71;#E5534B"
prop cle=interpolation valeur="linéaire"
prop cle=legend valeur="TRUE"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=112 type=Trend nom="Courbe_Archive" calque=108 parent=0 verrou=0 cache=0
prop cle=x valeur="30"
prop cle=y valeur="600"
prop cle=w valeur="820"
prop cle=h valeur="182"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=variables valeur="Armoires[0].ana.PT1.mes"
prop cle=mode valeur="historique"
prop cle=source valeur=""
prop cle=duration valeur="120"
prop cle=scale valeur="fixe"
prop cle=ymin valeur="0"
prop cle=ymax valeur="40"
prop cle=colors valeur="#2ECC71"
prop cle=interpolation valeur="escalier"
prop cle=legend valeur="TRUE"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=113 type=History nom="Hist_Evenements" calque=108 parent=0 verrou=0 cache=0
prop cle=x valeur="880"
prop cle=y valeur="80"
prop cle=w valeur="380"
prop cle=h valeur="330"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=source valeur="événements"
prop cle=group valeur=""
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=114 type=Button nom="Btn_Acquitter" calque=108 parent=0 verrou=0 cache=0
prop cle=x valeur="880"
prop cle=y valeur="430"
prop cle=w valeur="380"
prop cle=h valeur="60"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Acquitter l'armoire A"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="20"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=115 type=Button nom="Btn_Recette_Argon" calque=108 parent=0 verrou=0 cache=0
prop cle=x valeur="880"
prop cle=y valeur="500"
prop cle=w valeur="380"
prop cle=h valeur="60"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Recette Argon"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="20"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="3"
objet id=116 type=Button nom="Btn_Utilisateur" calque=108 parent=0 verrou=0 cache=0
prop cle=x valeur="880"
prop cle=y valeur="570"
prop cle=w valeur="380"
prop cle=h valeur="60"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Changer d'utilisateur"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="20"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=117 type=Button nom="Btn_Cle_Maintenance" calque=108 parent=0 verrou=0 cache=0
prop cle=x valeur="880"
prop cle=y valeur="650"
prop cle=w valeur="184"
prop cle=h valeur="60"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Clé de maintenance"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="20"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=118 type=Button nom="Btn_Armoire_A" calque=108 parent=0 verrou=0 cache=0
prop cle=x valeur="1070"
prop cle=y valeur="650"
prop cle=w valeur="184"
prop cle=h valeur="60"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoire A"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="20"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
action objet=114 declencheur="Clic" operation="Acquitter une alarme" cible="groupe:Armoire A"
action objet=115 declencheur="Clic" operation="Charger une recette" cible="Reglages_Armoires" valeur="Argon"
action objet=116 declencheur="Clic" operation="Changer d'utilisateur"
action objet=117 declencheur="Clic" operation="Basculer" cible="Mode_Maintenance"
action objet=118 declencheur="Clic" operation="Naviguer" cible="Vue_Armoire_A" transition="Glissement" duree=400 direction="gauche" courbe="douce"
fin
