# XpgAnalyzer - vue IHM (format 19)
vue id=75 nom="Popup_Aide" description="Aide contextuelle (popup)" largeur=640 hauteur=360 fond="#20242B" calque_actif=76 role=popup popup_titre=1 popup_libelle="Aide de l'armoire" popup_modale=1 popup_deplacable=1 popup_fermer=1 popup_dehors=1 popup_position="haut-droite"
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=76 nom="Calque 1" visible=1 verrou=0
objet id=77 type=Rectangle nom="Fond_Aide" calque=76 parent=0 verrou=0 cache=0
prop cle=x valeur="0"
prop cle=y valeur="0"
prop cle=w valeur="640"
prop cle=h valeur="360"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#2B3444"
prop cle=stroke valeur="#5DADE2"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="12"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=78 type=Text nom="Titre_Aide" calque=76 parent=0 verrou=0 cache=0
prop cle=x valeur="30"
prop cle=y valeur="20"
prop cle=w valeur="580"
prop cle=h valeur="40"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Aide - armoire de gaz A"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="24"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=79 type=Text nom="Texte_Aide" calque=76 parent=0 verrou=0 cache=0
prop cle=x valeur="30"
prop cle=y valeur="80"
prop cle=w valeur="580"
prop cle=h valeur="180"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="État : {Message_Operateur}\\nClics de navigation : {Compteur_Clics:000}\\nIHM en marche depuis {Secondes_IHM:t}\\nMaintenance : {Mode_Maintenance:Oui|Non}\\nUn appui long sur Armoire B bascule le mode maintenance ; ce paragraphe passe à la ligne tout seul au bord de l'objet."
prop cle=font valeur="Sans"
prop cle=fontSize valeur="17"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="TRUE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=80 type=Button nom="Btn_Fermer" calque=76 parent=0 verrou=0 cache=0
prop cle=x valeur="470"
prop cle=y valeur="290"
prop cle=w valeur="140"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Fermer"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
action objet=80 declencheur="Clic" operation="Fermer la popup" transition="Fondu" duree=250 direction="gauche" courbe="douce"
fin
