# XpgAnalyzer - vue IHM (format 19)
vue id=135 nom="Vue_Production" description="Production de l'armoire A" largeur=1280 hauteur=800 fond="#20242B" calque_actif=136 modele=119 entete=1 entete_vue=0 pied=1 pied_vue=0
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=136 nom="Calque 1" visible=1 verrou=0
objet id=137 type=Text nom="Titre_Production" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="100"
prop cle=w valeur="700"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Production - armoire A"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="28"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=138 type=Gauge nom="Jauge_Pression" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="60"
prop cle=y valeur="180"
prop cle=w valeur="180"
prop cle=h valeur="180"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="40" expr="Armoires[0].ana.PT1.mes"
prop cle=min valeur="0"
prop cle=max valeur="40"
prop cle=unit valeur="bar"
prop cle=fill valeur="#2F6FD6"
prop cle=background valeur="#2A313C"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=139 type=Button nom="Btn_Maintenance" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="320"
prop cle=y valeur="250"
prop cle=w valeur="180"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Maintenance"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=140 type=Table nom="Table_Mesures" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="520"
prop cle=y valeur="100"
prop cle=w valeur="600"
prop cle=h valeur="200"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=columns valeur="Mesure;Valeur;Unité;État"
prop cle=rows valeur="4"
prop cle=source valeur=""
prop cle=fontSize valeur="14"
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
prop cle=cells valeur="Pression A\t{Armoires[0].ana.PT1.mes:0.0}\tbar\t{Armoires[0].ana.PT1.mes > 10:haute|normale}\nSeuil poids A\t=Armoires[0].seuil_poids_saisi\tkg\t\nMaintenance\t{Mode_Maintenance:en cours|non}\t\t\nMessage\t{Message_Operateur}\t\t"
prop cle=widths valeur="2;1.4;1;1"
objet id=141 type=Trend nom="Courbe_Pressions" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="400"
prop cle=w valeur="520"
prop cle=h valeur="330"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=variables valeur="Armoires[0].ana.PT1.mes;Armoires[1].ana.PT1.mes"
prop cle=mode valeur="temps réel"
prop cle=source valeur=""
prop cle=duration valeur="60"
prop cle=scale valeur="fixe"
prop cle=ymin valeur="0"
prop cle=ymax valeur="40"
prop cle=colors valeur="#4FA3FF;#E5534B;#2ECC71;#E5534B"
prop cle=interpolation valeur="linéaire"
prop cle=legend valeur="TRUE"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
prop cle=names valeur="Pression A;Pression B"
objet id=142 type=AnimatedImage nom="Anim_Vanne" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="600"
prop cle=y valeur="320"
prop cle=w valeur="120"
prop cle=h valeur="120"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=states valeur="Mode_Maintenance => alarme.ico, vanne_fermee.png @ 400\nArmoires[0].ana.PT1.mes > 10 => vanne_v1_ouverte.png"
prop cle=image valeur="vanne_fermee.png"
prop cle=period valeur="500"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur=""
prop cle=recolorMode valeur="tout"
prop cle=recolorFrom valeur="#000000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=143 type=RecipeManager nom="Gestion_Recettes" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="600"
prop cle=y valeur="460"
prop cle=w valeur="540"
prop cle=h valeur="280"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=recipe valeur="Reglages_Armoires"
prop cle=buttons valeur="Ajouter;Modifier;Supprimer;Appliquer;Lire"
prop cle=fontSize valeur="13"
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=textColor valeur="#DDE3EA"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=146 type=Image nom="Img_Choisie" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="760"
prop cle=y valeur="320"
prop cle=w valeur="120"
prop cle=h valeur="120"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="" expr="Image_Choisie"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur=""
prop cle=recolorMode valeur="tout"
prop cle=recolorFrom valeur="#000000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=147 type=Button nom="Btn_Photo" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="260"
prop cle=y valeur="310"
prop cle=w valeur="150"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Photo..."
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=148 type=Button nom="Btn_Base" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="420"
prop cle=y valeur="310"
prop cle=w valeur="150"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Historique (base)"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=149 type=Button nom="Btn_Son" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="260"
prop cle=y valeur="360"
prop cle=w valeur="150"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Bip"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=150 type=Button nom="Btn_Systeme" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="420"
prop cle=y valeur="360"
prop cle=w valeur="150"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Système"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=155 type=Text nom="Moyenne_AB" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="890"
prop cle=y valeur="330"
prop cle=w valeur="260"
prop cle=h valeur="40"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Moy. A/B : {Moyenne_Pression(Armoires[0].ana.PT1.mes, Armoires[1].ana.PT1.mes):0.0} bar"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="20"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=156 type=Button nom="Btn_Controle" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="890"
prop cle=y valeur="390"
prop cle=w valeur="200"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Contrôle fait"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=264 type=SystemButton nom="Btn_Parametres" calque=136 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="360"
prop cle=w valeur="190"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Paramètres"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=tab valeur="Réglages"
prop cle=icon valeur="TRUE"
prop cle=fill valeur="#3A4556"
prop cle=stroke valeur="#5B6B82"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
action objet=0 declencheur="Ouverture de la vue" operation="Journaliser" valeur="Vue_Production : ses objets par-dessus le modèle"
action objet=139 declencheur="Clic" operation="Basculer" cible="Mode_Maintenance"
action objet=147 declencheur="Clic" operation="Demander une ressource" cible="Image_Choisie" valeur="png;jpg"
action objet=148 declencheur="Clic" operation="Lier un tableau" cible="Table_Mesures" valeur="historique"
action objet=149 declencheur="Clic" operation="Jouer un son" cible="bip_alarme.wav"
action objet=150 declencheur="Clic" operation="Paramètres système"
action objet=156 declencheur="Clic" operation="Exécuter un script" valeur="Tracer_Evenement('Contrôle visuel fait', 2);"
fin
