# XpgAnalyzer - vue IHM (format 19)
vue id=307 nom="Vue_Pictogrammes" description="Un SVG net a toutes les tailles, recolorie par expression" largeur=1280 hauteur=800 fond="#20242B" calque_actif=308
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=308 nom="Calque 1" visible=1 verrou=0
objet id=309 type=Text nom="Titre_Pictogrammes" calque=308 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="20"
prop cle=w valeur="900"
prop cle=h valeur="40"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Un SVG : net à toutes les tailles, recolorié par expression"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="24"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=310 type=Image nom="Pompe_48" calque=308 parent=0 verrou=0 cache=0
prop cle=x valeur="60"
prop cle=y valeur="200"
prop cle=w valeur="48"
prop cle=h valeur="48"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="pompe.svg"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur=""
prop cle=recolorMode valeur="tout"
prop cle=recolorFrom valeur="#000000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=311 type=Image nom="Pompe_128" calque=308 parent=0 verrou=0 cache=0
prop cle=x valeur="150"
prop cle=y valeur="140"
prop cle=w valeur="128"
prop cle=h valeur="128"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="pompe.svg"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur=""
prop cle=recolorMode valeur="tout"
prop cle=recolorFrom valeur="#000000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=312 type=Image nom="Pompe_360" calque=308 parent=0 verrou=0 cache=0
prop cle=x valeur="320"
prop cle=y valeur="80"
prop cle=w valeur="360"
prop cle=h valeur="360"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="pompe.svg"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur=""
prop cle=recolorMode valeur="tout"
prop cle=recolorFrom valeur="#000000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=313 type=Image nom="Pompe_Marche_Svg" calque=308 parent=0 verrou=0 cache=0
prop cle=x valeur="760"
prop cle=y valeur="120"
prop cle=w valeur="140"
prop cle=h valeur="140"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="pompe.svg"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur="" expr="SEL(Marche_Ligne, '#8A94A3', '#2ECC71')"
prop cle=recolorMode valeur="une couleur"
prop cle=recolorFrom valeur="#2F6FD6"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=314 type=Image nom="Pompe_Defaut_Svg" calque=308 parent=0 verrou=0 cache=0
prop cle=x valeur="930"
prop cle=y valeur="120"
prop cle=w valeur="140"
prop cle=h valeur="140"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="pompe.svg"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur="" expr="SEL(Defaut_Filtre, '#2ECC71', '#E5534B')"
prop cle=recolorMode valeur="une couleur"
prop cle=recolorFrom valeur="#2F6FD6"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=315 type=Image nom="Pompe_Mono_Svg" calque=308 parent=0 verrou=0 cache=0
prop cle=x valeur="1100"
prop cle=y valeur="120"
prop cle=w valeur="140"
prop cle=h valeur="140"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="pompe.svg"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur="#F2C94C"
prop cle=recolorMode valeur="contours"
prop cle=recolorFrom valeur="#000000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=316 type=Text nom="Legende_Recolor" calque=308 parent=0 verrou=0 cache=0
prop cle=x valeur="760"
prop cle=y valeur="280"
prop cle=w valeur="480"
prop cle=h valeur="60"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Marche (expression)   ·   Défaut (expression)   ·   Contour recolorié"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=317 type=Switch nom="Inter_Ligne_2" calque=308 parent=0 verrou=0 cache=0
prop cle=x valeur="760"
prop cle=y valeur="380"
prop cle=w valeur="220"
prop cle=h valeur="40"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=textOn valeur="Ligne en marche"
prop cle=textOff valeur="Ligne arrêtée"
prop cle=state valeur=""
prop cle=font valeur="Sans"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#E6EAF0"
prop cle=colorOn valeur="#2ECC71"
prop cle=colorOff valeur="#4A5261"
prop cle=knobColor valeur="#F4F6FA"
prop cle=variable valeur="Marche_Ligne"
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=318 type=CheckBox nom="Case_Defaut_2" calque=308 parent=0 verrou=0 cache=0
prop cle=x valeur="760"
prop cle=y valeur="440"
prop cle=w valeur="260"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Simuler un défaut"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=state valeur=""
prop cle=accent valeur="#2F6FD6"
prop cle=stroke valeur="#8A9BB0"
prop cle=variable valeur="Defaut_Filtre"
prop cle=refresh valeur="500"
prop cle=access valeur="0"
fin
