# XpgAnalyzer - vue IHM (format 19)
vue id=330 nom="Carte_Armoire" description="" largeur=280 hauteur=300 fond="#20242B" calque_actif=331 role=symbole
parametre nom="Armoire" defaut="Armoires[0]" description=""
parametre nom="Nom" defaut="'A'" description=""
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=331 nom="Calque 1" visible=1 verrou=0
objet id=332 type=Rectangle nom="Cadre_A" calque=331 parent=0 verrou=0 cache=0
prop cle=x valeur="0"
prop cle=y valeur="0"
prop cle=w valeur="280"
prop cle=h valeur="300"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#232A35"
prop cle=stroke valeur="#4A5568"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="10"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=333 type=Text nom="Titre_A" calque=331 parent=0 verrou=0 cache=0
prop cle=x valeur="10"
prop cle=y valeur="10"
prop cle=w valeur="260"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoire {Nom}"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="22"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=334 type=GasBottle nom="Bouteille_A" calque=331 parent=0 verrou=0 cache=0
prop cle=x valeur="26"
prop cle=y valeur="60"
prop cle=w valeur="70"
prop cle=h valeur="200"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="150" expr="Armoire.ana.PT1.mes"
prop cle=fault valeur="FALSE" expr="Armoire.bouteille_vide"
prop cle=colorFault valeur="#E5534B"
prop cle=stroke valeur="#C8D0DC"
prop cle=strokeWidth valeur="2"
prop cle=label valeur=""
prop cle=labelPosition valeur="dessous"
prop cle=fontSize valeur="13"
prop cle=textColor valeur="#C8D0DC"
prop cle=fill valeur="#1F252E"
prop cle=fillColor valeur="#8FB3D9"
prop cle=min valeur="0"
prop cle=max valeur="10"
prop cle=showValue valeur="TRUE"
prop cle=unit valeur="bar"
prop cle=format valeur="0"
prop cle=lowAlarm valeur=""
prop cle=low valeur=""
prop cle=high valeur=""
prop cle=highAlarm valeur=""
prop cle=colorWarning valeur="#F2C94C"
prop cle=colorAlarm valeur="#E5534B"
prop cle=gasColor valeur="#1E6B3A"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=335 type=NumericDisplay nom="Pression_A" calque=331 parent=0 verrou=0 cache=0
prop cle=x valeur="116"
prop cle=y valeur="60"
prop cle=w valeur="150"
prop cle=h valeur="56"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="0" expr="Armoire.ana.PT1.mes"
prop cle=format valeur="0.0"
prop cle=unit valeur="bar"
prop cle=label valeur="Pression"
prop cle=lowAlarm valeur=""
prop cle=low valeur=""
prop cle=high valeur=""
prop cle=highAlarm valeur=""
prop cle=font valeur="Sans"
prop cle=fontSize valeur="24"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="droite"
prop cle=colorWarning valeur="#F2C94C"
prop cle=colorAlarm valeur="#E5534B"
prop cle=fill valeur="#141820"
prop cle=stroke valeur="#3A4556"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=336 type=Indicator nom="Voyant_A" calque=331 parent=0 verrou=0 cache=0
prop cle=x valeur="120"
prop cle=y valeur="136"
prop cle=w valeur="30"
prop cle=h valeur="30"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="FALSE" expr="Armoire.active"
prop cle=colorOn valeur="#2ECC71"
prop cle=colorOff valeur="#4A5261"
prop cle=stroke valeur="#1B1F26"
prop cle=strokeWidth valeur="1"
prop cle=shape valeur="rond"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=337 type=MultiStateText nom="Etat_A" calque=331 parent=0 verrou=0 cache=0
prop cle=x valeur="158"
prop cle=y valeur="136"
prop cle=w valeur="112"
prop cle=h valeur="30"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="0" expr="Armoire.active"
prop cle=stateList valeur="0 = Arrêtée | #9AA6B8; 1 = Active | #2ECC71"
prop cle=unknownText valeur="État inconnu"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="centre"
prop cle=fill valeur=""
prop cle=stroke valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=338 type=NumericDisplay nom="Cycles_A" calque=331 parent=0 verrou=0 cache=0
prop cle=x valeur="116"
prop cle=y valeur="176"
prop cle=w valeur="150"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="0" expr="Armoire.compteur_cycle_pompage"
prop cle=format valeur="0"
prop cle=unit valeur=""
prop cle=label valeur="Cycles de pompage"
prop cle=lowAlarm valeur=""
prop cle=low valeur=""
prop cle=high valeur=""
prop cle=highAlarm valeur=""
prop cle=font valeur="Sans"
prop cle=fontSize valeur="24"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="droite"
prop cle=colorWarning valeur="#F2C94C"
prop cle=colorAlarm valeur="#E5534B"
prop cle=fill valeur="#141820"
prop cle=stroke valeur="#3A4556"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=339 type=Button nom="Bouton_A" calque=331 parent=0 verrou=0 cache=0
prop cle=x valeur="120"
prop cle=y valeur="230"
prop cle=w valeur="140"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Détails"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
action objet=339 declencheur="Clic" operation="Ouvrir une popup" cible="Popup_Armoire" valeur="Armoire := Armoire; Nom := Nom" position="objet" transition="Fondu" duree=300 direction="gauche" courbe="douce"
fin
