# XpgAnalyzer - vue IHM (format 19)
vue id=362 nom="Vue_Alarmes" description="Bandeau, compteurs, résumé par zone, consigne, listes et statistiques" largeur=1280 hauteur=800 fond="#20242B" calque_actif=363
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=363 nom="Calque 1" visible=1 verrou=0
objet id=364 type=AlarmBanner nom="Bandeau" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="0"
prop cle=y valeur="0"
prop cle=w valeur="1280"
prop cle=h valeur="50"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=group valeur=""
prop cle=show valeur="la plus grave"
prop cle=period valeur="4000"
prop cle=ackButton valeur="TRUE"
prop cle=showCount valeur="TRUE"
prop cle=blinkUnacked valeur="TRUE"
prop cle=empty valeur="Aucune alarme en cours"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#E6EAF0"
prop cle=fill valeur="#1F252E"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=365 type=AlarmCounter nom="Compteur_A_Acquitter" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="66"
prop cle=w valeur="170"
prop cle=h valeur="72"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=group valeur=""
prop cle=count valeur="à acquitter"
prop cle=label valeur="À acquitter"
prop cle=icon valeur="TRUE"
prop cle=blinkUnacked valeur="TRUE"
prop cle=fontSize valeur="22"
prop cle=textColor valeur="#FFFFFF"
prop cle=fill valeur="#2A313C"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=366 type=AlarmCounter nom="Compteur_Actives" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="200"
prop cle=y valeur="66"
prop cle=w valeur="170"
prop cle=h valeur="72"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=group valeur=""
prop cle=count valeur="actives"
prop cle=label valeur="Actives"
prop cle=icon valeur="TRUE"
prop cle=blinkUnacked valeur="TRUE"
prop cle=fontSize valeur="22"
prop cle=textColor valeur="#FFFFFF"
prop cle=fill valeur="#2A313C"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=367 type=AlarmCounter nom="Compteur_De_Cote" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="380"
prop cle=y valeur="66"
prop cle=w valeur="170"
prop cle=h valeur="72"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=group valeur=""
prop cle=count valeur="mises de côté"
prop cle=label valeur="De côté"
prop cle=icon valeur="TRUE"
prop cle=blinkUnacked valeur="TRUE"
prop cle=fontSize valeur="22"
prop cle=textColor valeur="#FFFFFF"
prop cle=fill valeur="#2A313C"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=368 type=AlarmSummary nom="Resume_Zones" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="570"
prop cle=y valeur="66"
prop cle=w valeur="690"
prop cle=h valeur="150"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=groups valeur=""
prop cle=perRow valeur="3"
prop cle=variable valeur="Zone_Choisie"
prop cle=blinkUnacked valeur="TRUE"
prop cle=colorOk valeur="#2E6B45"
prop cle=fontSize valeur="14"
prop cle=textColor valeur="#FFFFFF"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=369 type=AlarmInstruction nom="Consigne_Alarme" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="156"
prop cle=w valeur="530"
prop cle=h valeur="200"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=alarm valeur=""
prop cle=showMessage valeur="TRUE"
prop cle=empty valeur="Aucune alarme choisie : cliquer une alarme (bandeau, liste, résumé)"
prop cle=fontSize valeur="14"
prop cle=textColor valeur="#E6EAF0"
prop cle=fill valeur="#1F252E"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=370 type=History nom="Liste_Alarmes" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="372"
prop cle=w valeur="820"
prop cle=h valeur="200"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=source valeur="alarmes"
prop cle=group valeur=""
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=371 type=History nom="Liste_De_Cote" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="588"
prop cle=w valeur="820"
prop cle=h valeur="150"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=source valeur="mises de côté"
prop cle=group valeur=""
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=372 type=AlarmStats nom="Stats_Alarmes" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="860"
prop cle=y valeur="232"
prop cle=w valeur="400"
prop cle=h valeur="300"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=range valeur="tout l'historique"
prop cle=top valeur="6"
prop cle=sort valeur="nombre"
prop cle=group valeur=""
prop cle=colors valeur="#F2994A"
prop cle=fontSize valeur="13"
prop cle=textColor valeur="#DDE3EA"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=373 type=Button nom="Btn_Mettre_De_Cote" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="860"
prop cle=y valeur="552"
prop cle=w valeur="195"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Mettre de côté 30 min"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=374 type=Button nom="Btn_Remettre" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="1065"
prop cle=y valeur="552"
prop cle=w valeur="195"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Tout remettre en service"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=375 type=Button nom="Btn_Taire" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="860"
prop cle=y valeur="606"
prop cle=w valeur="195"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Faire taire"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=376 type=Button nom="Btn_Maintenance" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="1065"
prop cle=y valeur="606"
prop cle=w valeur="195"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Maintenance oui / non"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=377 type=Text nom="Info_Alarmes" calque=363 parent=0 verrou=0 cache=0
prop cle=x valeur="860"
prop cle=y valeur="664"
prop cle=w valeur="400"
prop cle=h valeur="80"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Alarme choisie : {SYS.AlarmSelected}\\nZone : {SYS.AlarmZoneSelected}   son coupé : {SYS.AlarmSilenced:oui|non}"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="14"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="TRUE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
action objet=373 declencheur="Clic" operation="Mettre de côté une alarme" valeur="30;Capteur en essai ({SYS.UserName})"
action objet=374 declencheur="Clic" operation="Remettre une alarme en service" cible="*"
action objet=375 declencheur="Clic" operation="Faire taire les alarmes"
action objet=376 declencheur="Clic" operation="Basculer" cible="Mode_Maintenance"
fin
