# XpgAnalyzer - vue IHM (format 19)
vue id=417 nom="Vue_Poste_Gaz" description="Le poste de gaz, pose en glissant ses variables" largeur=1280 hauteur=800 fond="#20242B" calque_actif=418
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=418 nom="Calque 1" visible=1 verrou=0
objet id=419 type=Indicator nom="Voyant_AUTOMATE_EN_RUN" calque=418 parent=0 verrou=0 cache=0
prop cle=x valeur="80"
prop cle=y valeur="140"
prop cle=w valeur="32"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="FALSE" expr="AUTOMATE_EN_RUN"
prop cle=colorOn valeur="#2ECC71"
prop cle=colorOff valeur="#4A5261"
prop cle=stroke valeur="#1B1F26"
prop cle=strokeWidth valeur="1"
prop cle=shape valeur="rond"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=420 type=NumericDisplay nom="Afficheur_Pression_Ligne" calque=418 parent=0 verrou=0 cache=0
prop cle=x valeur="80"
prop cle=y valeur="230"
prop cle=w valeur="200"
prop cle=h valeur="56"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="0" expr="Pression_Ligne"
prop cle=format valeur="0.00"
prop cle=unit valeur=""
prop cle=label valeur="Pression de la ligne (bar)"
prop cle=lowAlarm valeur=""
prop cle=low valeur=""
prop cle=high valeur=""
prop cle=highAlarm valeur=""
prop cle=font valeur="Sans"
prop cle=fontSize valeur="24"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="droite"
prop cle=colorWarning valeur="#F2C94C"
prop cle=colorAlarm valeur="#E5534B"
prop cle=fill valeur="#141820"
prop cle=stroke valeur="#3A4556"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=448 type=Button nom="Btn_PT1_A" calque=418 parent=0 verrou=0 cache=0
prop cle=x valeur="80"
prop cle=y valeur="380"
prop cle=w valeur="200"
prop cle=h valeur="48"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="PT1_A …"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="18"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#1F8A5A"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="10"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
prop cle=namedStyle valeur="Bouton_Equipement"
objet id=449 type=Button nom="Btn_PT1_B" calque=418 parent=0 verrou=0 cache=0
prop cle=x valeur="320"
prop cle=y valeur="380"
prop cle=w valeur="200"
prop cle=h valeur="48"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="PT1_B …"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="18"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#1F8A5A"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="10"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
prop cle=namedStyle valeur="Bouton_Equipement"
objet id=566 type=Button nom="Btn_PT3_A" calque=418 parent=0 verrou=0 cache=0
prop cle=x valeur="560"
prop cle=y valeur="380"
prop cle=w valeur="200"
prop cle=h valeur="48"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="PT3_A …"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
action objet=448 declencheur="Clic" operation="Ouvrir une popup" cible="Popup_CAPTEUR" valeur="Equipement := PT1_A" transition="Instantanée" duree=400 direction="gauche" courbe="douce"
action objet=449 declencheur="Clic" operation="Ouvrir une popup" cible="Popup_CAPTEUR" valeur="Equipement := PT1_B" transition="Instantanée" duree=400 direction="gauche" courbe="douce"
action objet=566 declencheur="Clic" operation="Ouvrir une popup" cible="Popup_CAPTEUR" valeur="Equipement := PT3_A" transition="Instantanée" duree=400 direction="gauche" courbe="douce"
fin
