# XpgAnalyzer - vue IHM (format 19)
vue id=521 nom="Vue_Armoire_B" description="Synoptique de l'armoire de gaz A" largeur=1280 hauteur=800 fond="#20242B" calque_actif=526
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=522 nom="Fond" visible=1 verrou=1
calque id=523 nom="Equipements" visible=1 verrou=0
calque id=524 nom="Instrumentation" visible=1 verrou=0
calque id=525 nom="Alarmes" visible=1 verrou=0
calque id=526 nom="Navigation" visible=1 verrou=0
objet id=527 type=Rectangle nom="Cadre_Armoire" calque=522 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="90"
prop cle=w valeur="700"
prop cle=h valeur="620"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#26303D"
prop cle=stroke valeur="#46546B"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="12"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=528 type=Text nom="Titre" calque=522 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="20"
prop cle=w valeur="700"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoire A - supervision gaz"
prop cle=font valeur="industrie_bold.ttf"
prop cle=fontSize valeur="26"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=529 type=Group nom="Groupe_Bouteille" calque=523 parent=0 verrou=0 cache=0
prop cle=x valeur="100"
prop cle=y valeur="190"
prop cle=w valeur="120"
prop cle=h valeur="400"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
objet id=530 type=Rectangle nom="Bouteille" calque=523 parent=529 verrou=0 cache=0
prop cle=x valeur="100"
prop cle=y valeur="190"
prop cle=w valeur="120"
prop cle=h valeur="400"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#3B4D63"
prop cle=stroke valeur="#7F93AD"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="40"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=531 type=ProgressBar nom="Niveau_Bouteille" calque=523 parent=529 verrou=0 cache=0
prop cle=x valeur="140"
prop cle=y valeur="240"
prop cle=w valeur="40"
prop cle=h valeur="300"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="40" expr="Armoires[1].seuil_poids_saisi"
prop cle=min valeur="0"
prop cle=max valeur="100"
prop cle=fill valeur="#2F6FD6"
prop cle=background valeur="#2A313C"
prop cle=orientation valeur="verticale"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=532 type=Line nom="Tuyau_Entree" calque=523 parent=0 verrou=0 cache=0
prop cle=x valeur="220"
prop cle=y valeur="370"
prop cle=w valeur="110"
prop cle=h valeur="0"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=points valeur="0,0 110,0"
prop cle=stroke valeur="#D0D8E4"
prop cle=strokeWidth valeur="6"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=533 type=Polygon nom="Vanne_Entree" calque=523 parent=0 verrou=0 cache=0
prop cle=x valeur="330"
prop cle=y valeur="340"
prop cle=w valeur="60"
prop cle=h valeur="60"
prop cle=rot valeur="90"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=points valeur="30,0 60,60 0,60"
prop cle=fill valeur="#3A4556"
prop cle=stroke valeur="#8A9BB0"
prop cle=strokeWidth valeur="1"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=534 type=Line nom="Tuyau_Pompe" calque=523 parent=0 verrou=0 cache=0
prop cle=x valeur="390"
prop cle=y valeur="370"
prop cle=w valeur="90"
prop cle=h valeur="0"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=points valeur="0,0 90,0"
prop cle=stroke valeur="#D0D8E4"
prop cle=strokeWidth valeur="6"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=535 type=Polygon nom="Vanne_Sortie" calque=523 parent=0 verrou=0 cache=0
prop cle=x valeur="480"
prop cle=y valeur="340"
prop cle=w valeur="60"
prop cle=h valeur="60"
prop cle=rot valeur="270"
prop cle=flipH valeur="TRUE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=points valeur="30,0 60,60 0,60"
prop cle=fill valeur="#3A4556"
prop cle=stroke valeur="#8A9BB0"
prop cle=strokeWidth valeur="1"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=536 type=Ellipse nom="Pompe_Vide" calque=523 parent=0 verrou=0 cache=0
prop cle=x valeur="570"
prop cle=y valeur="310"
prop cle=w valeur="110"
prop cle=h valeur="110"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#2F6FD6" expr="SEL(Armoires[1].active, '#4A5261', '#2ECC71')"
prop cle=stroke valeur="#8A9BB0"
prop cle=strokeWidth valeur="1"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=537 type=Gauge nom="Pression_PT1" calque=524 parent=0 verrou=0 cache=0
prop cle=x valeur="820"
prop cle=y valeur="100"
prop cle=w valeur="220"
prop cle=h valeur="220"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="40" expr="Armoires[1].ana.PT1.mes"
prop cle=min valeur="0"
prop cle=max valeur="10"
prop cle=unit valeur="bar"
prop cle=fill valeur="#2F6FD6"
prop cle=background valeur="#2A313C"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=538 type=Text nom="Texte_Cycles" calque=524 parent=0 verrou=0 cache=0
prop cle=x valeur="820"
prop cle=y valeur="340"
prop cle=w valeur="420"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE" expr="Armoires[1].etat = 5 AND AUTOMATE_EN_RUN"
prop cle=opacity valeur="100"
prop cle=text valeur="Cycles de pompage : {Armoires[1].compteur_cycle_pompage}"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=539 type=Indicator nom="Voyant_Active" calque=524 parent=0 verrou=0 cache=0
prop cle=x valeur="820"
prop cle=y valeur="400"
prop cle=w valeur="32"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="FALSE" expr="Armoires[1].active"
prop cle=colorOn valeur="#2ECC71"
prop cle=colorOff valeur="#4A5261"
prop cle=stroke valeur="#1B1F26"
prop cle=strokeWidth valeur="1"
prop cle=shape valeur="rond"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=540 type=Text nom="Libelle_Active" calque=524 parent=0 verrou=0 cache=0
prop cle=x valeur="870"
prop cle=y valeur="400"
prop cle=w valeur="360"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoire active"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=541 type=Indicator nom="Voyant_Config" calque=524 parent=0 verrou=0 cache=0
prop cle=x valeur="820"
prop cle=y valeur="450"
prop cle=w valeur="32"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="FALSE" expr="ConfigsGaz[(i + 15 + j * 2) MOD 20].Utilise"
prop cle=colorOn valeur="#2ECC71"
prop cle=colorOff valeur="#4A5261"
prop cle=stroke valeur="#1B1F26"
prop cle=strokeWidth valeur="1"
prop cle=shape valeur="rond"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=542 type=Text nom="Libelle_Config" calque=524 parent=0 verrou=0 cache=0
prop cle=x valeur="870"
prop cle=y valeur="450"
prop cle=w valeur="380"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Config. gaz n° {(i + 15 + j * 2) MOD 20} utilisée"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=543 type=Text nom="Texte_Debit" calque=524 parent=0 verrou=0 cache=0
prop cle=x valeur="820"
prop cle=y valeur="560"
prop cle=w valeur="380"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Débit entrée : {Debit_Entree:0.0} m3/h"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=544 type=Indicator nom="Alarme_Bouteille_Vide" calque=525 parent=0 verrou=0 cache=0
prop cle=x valeur="820"
prop cle=y valeur="500"
prop cle=w valeur="32"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="FALSE" expr="Armoires[1].bouteille_vide"
prop cle=colorOn valeur="#E74C3C"
prop cle=colorOff valeur="#4A5261"
prop cle=stroke valeur="#1B1F26"
prop cle=strokeWidth valeur="1"
prop cle=shape valeur="rond"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
prop cle=blink valeur="" expr="Armoires[1].bouteille_vide"
objet id=545 type=Text nom="Libelle_Alarme" calque=525 parent=0 verrou=0 cache=0
prop cle=x valeur="870"
prop cle=y valeur="500"
prop cle=w valeur="300"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE" expr="Armoires[1].etat <> 0"
prop cle=opacity valeur="100"
prop cle=text valeur="Bouteille vide"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=546 type=Image nom="Logo_Site" calque=525 parent=0 verrou=0 cache=0
prop cle=x valeur="1090"
prop cle=y valeur="610"
prop cle=w valeur="150"
prop cle=h valeur="100"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="logo_site.png"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur=""
prop cle=recolorMode valeur="tout"
prop cle=recolorFrom valeur="#000000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=547 type=Button nom="Btn_Accueil" calque=526 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="730"
prop cle=w valeur="140"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Accueil"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=548 type=Button nom="Btn_Armoire_B" calque=526 parent=0 verrou=0 cache=0
prop cle=x valeur="320"
prop cle=y valeur="730"
prop cle=w valeur="140"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoire B"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=549 type=Button nom="Btn_Alarmes" calque=526 parent=0 verrou=0 cache=0
prop cle=x valeur="600"
prop cle=y valeur="730"
prop cle=w valeur="140"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Alarmes"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=550 type=Image nom="Etat_Vanne_Entree" calque=523 parent=0 verrou=0 cache=0
prop cle=x valeur="320"
prop cle=y valeur="450"
prop cle=w valeur="80"
prop cle=h valeur="80"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=image valeur="vanne_fermee.png" expr="SEL(Armoires[1].active, 'vanne_fermee.png', 'vanne_v1_ouverte.png')"
prop cle=stretch valeur="ajuster"
prop cle=recolor valeur=""
prop cle=recolorMode valeur="tout"
prop cle=recolorFrom valeur="#000000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=551 type=Text nom="Libelle_Etat_Vanne" calque=523 parent=0 verrou=0 cache=0
prop cle=x valeur="290"
prop cle=y valeur="540"
prop cle=w valeur="140"
prop cle=h valeur="32"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Vanne d'entrée"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=552 type=Button nom="Btn_Aide" calque=526 parent=0 verrou=0 cache=0
prop cle=x valeur="1000"
prop cle=y valeur="740"
prop cle=w valeur="140"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Aide"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=confirmMode valeur="aucune"
prop cle=holdMs valeur="2000"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
script id=553 nom="Vue_Armoire_A_OnOpen" langage=ST evenement=OnOpen corps="Compteur_Clics := Compteur_Clics + 1;\nIHM_JOURNAL('Armoire A ouverte ({Compteur_Clics} fois)');\n"
script id=554 nom="Vue_Armoire_A_OnCycle" langage=ST evenement=OnCycle corps="(* chaque cycle IHM : le bandeau suit l'armoire *)\nIF NOT Mode_Maintenance AND Armoires[1].bouteille_vide THEN\n    Message_Operateur := 'Bouteille vide';\nEND_IF;\n"
script id=555 nom="Vue_Armoire_A_OnClose" langage=ST evenement=OnClose corps="IF Compteur_Clics > 100 THEN\n    Compteur_Clics := 0;\nEND_IF;\n"
action objet=0 declencheur="Timer" delai=5000 operation="Journaliser" valeur="Pression PT1 : {Armoires[1].ana.PT1.mes:0.0} bar ; {Message_Operateur}"
action objet=547 declencheur="Clic" operation="Incrémenter" cible="Compteur_Clics"
action objet=547 declencheur="Clic" operation="Naviguer" cible="Vue_Accueil" transition="Glissement" duree=500 direction="droite" courbe="douce"
action objet=548 declencheur="Appui long" delai=800 operation="Basculer" cible="Mode_Maintenance"
action objet=549 declencheur="Double clic" garde="Mode_Maintenance" operation="Script général" cible="Remise_A_Zero"
action objet=549 declencheur="Clic" operation="Exécuter un script" valeur="IHM_JOURNAL('Alarmes : au lot 4 ; PT1 = {Armoires[1].ana.PT1.mes:0.0} bar');\nIHM_SON('bip_alarme.wav');"
action objet=549 declencheur="Clic" operation="Naviguer" cible="Vue_Supervision" transition="Glissement" duree=400 direction="gauche" courbe="douce"
action objet=552 declencheur="Clic" operation="Ouvrir une popup" cible="Popup_Aide" transition="Zoom" duree=450 direction="avant" courbe="rebond"
fin
