# XpgAnalyzer - vue IHM (format 19)
vue id=653 nom="Vue_Armoires_Nord" description="Les armoires en cartes : un symbole, une instance par armoire" largeur=1280 hauteur=800 fond="#20242B" calque_actif=654
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=654 nom="Calque 1" visible=1 verrou=0
objet id=655 type=Text nom="Titre_Cartes" calque=654 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="24"
prop cle=w valeur="1100"
prop cle=h valeur="44"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoires de gaz  -  une carte par armoire (un symbole, trois instances)"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="26"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=656 type=SymbolInstance nom="Carte_Armoire_1" calque=654 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="100"
prop cle=w valeur="280"
prop cle=h valeur="300"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=symbol valeur="Carte_Armoire"
prop cle=params valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=657 type=SymbolInstance nom="Carte_Armoire_2" calque=654 parent=0 verrou=0 cache=0
prop cle=x valeur="360"
prop cle=y valeur="100"
prop cle=w valeur="280"
prop cle=h valeur="300"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=symbol valeur="Carte_Armoire"
prop cle=params valeur="Armoire := Armoires[1]; Nom := 'B'"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=658 type=SymbolInstance nom="Carte_Armoire_3" calque=654 parent=0 verrou=0 cache=0
prop cle=x valeur="680"
prop cle=y valeur="100"
prop cle=w valeur="187"
prop cle=h valeur="200"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=symbol valeur="Carte_Armoire"
prop cle=params valeur="Armoire := Armoires[0]; Nom := 'A (réduite)'"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=659 type=Text nom="Legende_Cartes" calque=654 parent=0 verrou=0 cache=0
prop cle=x valeur="40"
prop cle=y valeur="440"
prop cle=w valeur="1100"
prop cle=h valeur="60"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Carte_Armoire est dessinée une fois ; chaque instance relie Armoire et Nom (Armoire := Armoires[1]; Nom := 'B').\\nModifier le symbole modifie les trois cartes."
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#9AA6B8"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
fin
