# XpgAnalyzer - vue IHM (format 19)
vue id=718 nom="Carte_Didacticiel" description="" largeur=330 hauteur=236 fond="#20242B" calque_actif=719 role=symbole
parametre nom="Armoire" defaut="Armoires[0]" description=""
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=719 nom="Calque 1" visible=1 verrou=0
objet id=720 type=Rectangle nom="Cadre_1" calque=719 parent=0 verrou=0 cache=0
prop cle=x valeur="0"
prop cle=y valeur="0"
prop cle=w valeur="330"
prop cle=h valeur="236"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=fill valeur="#1F3A5F"
prop cle=stroke valeur="#4A5568"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="10"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=721 type=Text nom="Titre_1" calque=719 parent=0 verrou=0 cache=0
prop cle=x valeur="12"
prop cle=y valeur="10"
prop cle=w valeur="306"
prop cle=h valeur="36"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Armoire"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="22"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="FALSE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=722 type=NumericDisplay nom="Pression_1" calque=719 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="58"
prop cle=w valeur="210"
prop cle=h valeur="56"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="0" expr="Armoire.ana.PT1.mes"
prop cle=format valeur="0.0"
prop cle=unit valeur="bar"
prop cle=label valeur="Pression"
prop cle=lowAlarm valeur=""
prop cle=low valeur=""
prop cle=high valeur=""
prop cle=highAlarm valeur=""
prop cle=font valeur="Sans"
prop cle=fontSize valeur="24"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="droite"
prop cle=colorWarning valeur="#F2C94C"
prop cle=colorAlarm valeur="#E5534B"
prop cle=fill valeur="#141820"
prop cle=stroke valeur="#3A4556"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=723 type=NumericDisplay nom="Cycles_1" calque=719 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="130"
prop cle=w valeur="210"
prop cle=h valeur="50"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="0" expr="Armoire.compteur_cycle_pompage"
prop cle=format valeur="0"
prop cle=unit valeur=""
prop cle=label valeur="Cycles"
prop cle=lowAlarm valeur=""
prop cle=low valeur=""
prop cle=high valeur=""
prop cle=highAlarm valeur=""
prop cle=font valeur="Sans"
prop cle=fontSize valeur="24"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="droite"
prop cle=colorWarning valeur="#F2C94C"
prop cle=colorAlarm valeur="#E5534B"
prop cle=fill valeur="#141820"
prop cle=stroke valeur="#3A4556"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=724 type=Indicator nom="Voyant_1" calque=719 parent=0 verrou=0 cache=0
prop cle=x valeur="258"
prop cle=y valeur="72"
prop cle=w valeur="34"
prop cle=h valeur="34"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=value valeur="FALSE" expr="Armoire.active"
prop cle=colorOn valeur="#2ECC71"
prop cle=colorOff valeur="#4A5261"
prop cle=stroke valeur="#1B1F26"
prop cle=strokeWidth valeur="1"
prop cle=shape valeur="rond"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
fin
