// =============================================================================
//  hmi/HmiNativesData.cpp - 1.12.0 : LE CATALOGUE DES NATIVES (GENERE)
// -----------------------------------------------------------------------------
//  Ecrit par outils/natives/generer.py depuis outils/natives/catalogue.py : ne pas
//  le modifier a la main, changer le catalogue et relancer le generateur.
// =============================================================================
#include "HmiNatives.hpp"

namespace hmi::natives {

const std::vector<Category>& categories() {
    static const std::vector<Category> k = {
        {"math", "Math\xC3\xA9matiques", "Valeur absolue, racine, puissances, logarithmes, trigonom\xC3\xA9trie, arrondis.", "Fonctions standard"},
        {"select", "S\xC3\xA9lection et bornes", "Choisir une valeur, la plus petite, la plus grande, borner.", "Fonctions standard"},
        {"texte", "Cha\xC3\xAEnes de caract\xC3\xA8res", "Longueur, extraits, recherche, assemblage, majuscules.", "Fonctions standard"},
        {"bits", "Bits et d\xC3\xA9" "calages", "D\xC3\xA9" "caler et faire tourner les bits d'un mot.", "Fonctions standard"},
        {"conv", "Conversions", "Passer d'un type \xC3\xA0 l'autre : TO_xxx et X_TO_Y.", "Fonctions standard"},
        {"tab", "Tableaux", "Taille et bornes d'un tableau.", "Le dialecte de l'IHM"},
        {"map", "MAP et it\xC3\xA9rateurs", "Les tables associatives (cl\xC3\xA9 \xE2\x86\x92 valeur) et leur parcours.", "Le dialecte de l'IHM"},
        {"ref", "R\xC3\xA9" "f\xC3\xA9rences et pointeurs", "D\xC3\xA9signer une variable sans la copier.", "Le dialecte de l'IHM"},
        {"nav", "Navigation et vues", "Changer de vue, revenir, l'accueil.", "Fonctions IHM_"},
        {"popup", "Popups", "Ouvrir, remplacer, centrer, fermer une popup.", "Fonctions IHM_"},
        {"journal", "Journal et Console", "\xC3\x89" "crire une ligne dans le journal ou la Console.", "Fonctions IHM_"},
        {"script", "Scripts et temps", "Appeler un script, le temps de l'IHM.", "Fonctions IHM_"},
        {"user", "Utilisateurs", "Qui est connect\xC3\xA9, son groupe, son niveau ; d\xC3\xA9" "connecter.", "Fonctions IHM_"},
        {"alarme", "Alarmes", "Mettre de c\xC3\xB4t\xC3\xA9, remettre, faire taire.", "Fonctions IHM_"},
        {"affichage", "Affichage et son", "Langue, th\xC3\xA8me, param\xC3\xA8tres syst\xC3\xA8me, sons.", "Fonctions IHM_"},
        {"gif", "GIF anim\xC3\xA9s", "Jouer, mettre en pause, arr\xC3\xAAter, rejouer.", "Fonctions IHM_"},
        {"equip", "\xC3\x89quipements et r\xC3\xA9seau", "\xC3\x89tat, ping, esclave simul\xC3\xA9.", "Fonctions IHM_"},
        {"export", "Exports", "Exporter des donn\xC3\xA9" "es en CSV, XLSX ou PDF.", "Fonctions IHM_"},
        {"couleur", "Couleurs", "Composer, m\xC3\xA9langer, \xC3\xA9" "claircir une couleur ; une couleur selon une valeur.", "Couleurs et al\xC3\xA9" "atoire"},
        {"alea", "Al\xC3\xA9" "atoire", "Des nombres au hasard, et une suite qu'on peut rejouer.", "Couleurs et al\xC3\xA9" "atoire"},
        {"date", "Dates et heures", "Maintenant, la date ou l'heure d'une date et heure, les assembler.", "Couleurs et al\xC3\xA9" "atoire"},
        {"op", "Op\xC3\xA9rateurs", "Calculer, comparer, combiner : + - * / MOD ** AND OR...", "Le langage"},
        {"instr", "Instructions", "IF, CASE, FOR, FOR EACH, WHILE, REPEAT, EXIT, CONTINUE, RETURN, TRY, ASSERT.", "Le langage"},
    };
    return k;
}

const std::vector<Function>& functions() {
    static const std::vector<Function> k = {
        {"ABS", "math", {{"IN", "ANY_NUM", "un nombre", false}}, "comme IN", "La valeur absolue : le nombre sans son signe.",
         "Ecart := ABS(Consigne - Mesure);",
         "Ecart = fabsf(Consigne - Mesure);   /* abs() pour un entier */",
         "Ecart = std::abs(Consigne - Mesure);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "ABS(-2.5)", "2.5", ""}, {}},
        {"SQRT", "math", {{"IN", "REAL", "un nombre positif ou nul", false}}, "REAL", "La racine carr\xC3\xA9" "e.",
         "Norme := SQRT(X * X + Y * Y);",
         "Norme = sqrtf(X * X + Y * Y);",
         "Norme = std::sqrt(X * X + Y * Y);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "SQRT(16.0)", "4", ""}, {"Un nombre n\xC3\xA9gatif ne donne pas de racine : le r\xC3\xA9sultat n'est pas un nombre (NaN)."}},
        {"LN", "math", {{"IN", "REAL", "un nombre strictement positif", false}}, "REAL", "Le logarithme n\xC3\xA9p\xC3\xA9rien (base e).",
         "T := LN(Rapport) / K;",
         "T = logf(Rapport) / K;",
         "T = std::log(Rapport) / K;",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "LN(1.0)", "0", ""}, {}},
        {"LOG", "math", {{"IN", "REAL", "un nombre strictement positif", false}}, "REAL", "Le logarithme d\xC3\xA9" "cimal (base 10).",
         "Decibels := 20.0 * LOG(Gain);",
         "Decibels = 20.0f * log10f(Gain);",
         "Decibels = 20.0f * std::log10(Gain);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "LOG(1000.0)", "3", ""}, {}},
        {"EXP", "math", {{"IN", "REAL", "l'exposant", false}}, "REAL", "L'exponentielle : e puissance IN.",
         "Decharge := EXP(-T / Tau);",
         "Decharge = expf(-T / Tau);",
         "Decharge = std::exp(-T / Tau);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "EXP(0.0)", "1", ""}, {}},
        {"EXPT", "math", {{"IN1", "REAL", "la base", false}, {"IN2", "ANY_NUM", "l'exposant", false}}, "REAL", "IN1 puissance IN2.",
         "Surface := 3.14159 * EXPT(Rayon, 2);",
         "Surface = 3.14159f * powf(Rayon, 2);",
         "Surface = 3.14159f * std::pow(Rayon, 2);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "EXPT(2.0, 3)", "8", ""}, {"S'\xC3\xA9" "crit aussi avec l'op\xC3\xA9rateur ** : 2.0 ** 3."}},
        {"SIN", "math", {{"IN", "REAL", "un angle en radians", false}}, "REAL", "Le sinus d'un angle en radians.",
         "Y := SIN(Angle);",
         "Y = sinf(Angle);",
         "Y = std::sin(Angle);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "SIN(0.0)", "0", ""}, {"Un angle en degr\xC3\xA9s se convertit : Angle * 3.14159 / 180.0."}},
        {"COS", "math", {{"IN", "REAL", "un angle en radians", false}}, "REAL", "Le cosinus d'un angle en radians.",
         "Y := COS(Angle);",
         "Y = cosf(Angle);",
         "Y = std::cos(Angle);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "COS(0.0)", "1", ""}, {"Un angle en degr\xC3\xA9s se convertit : Angle * 3.14159 / 180.0."}},
        {"TAN", "math", {{"IN", "REAL", "un angle en radians", false}}, "REAL", "La tangente d'un angle en radians.",
         "Y := TAN(Angle);",
         "Y = tanf(Angle);",
         "Y = std::tan(Angle);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "TAN(0.0)", "0", ""}, {"Un angle en degr\xC3\xA9s se convertit : Angle * 3.14159 / 180.0."}},
        {"ASIN", "math", {{"IN", "REAL", "un nombre", false}}, "REAL", "L'arc sinus, en radians (de -\xCF\x80/2 \xC3\xA0 \xCF\x80/2).",
         "Y := ASIN(Angle);",
         "Y = asinf(Angle);",
         "Y = std::asin(Angle);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "ASIN(1.0)", "1.5707963", ""}, {}},
        {"ACOS", "math", {{"IN", "REAL", "un nombre", false}}, "REAL", "L'arc cosinus, en radians (de 0 \xC3\xA0 \xCF\x80).",
         "Y := ACOS(Angle);",
         "Y = acosf(Angle);",
         "Y = std::acos(Angle);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "ACOS(1.0)", "0", ""}, {}},
        {"ATAN", "math", {{"IN", "REAL", "un nombre", false}}, "REAL", "L'arc tangente, en radians (de -\xCF\x80/2 \xC3\xA0 \xCF\x80/2).",
         "Y := ATAN(Angle);",
         "Y = atanf(Angle);",
         "Y = std::atan(Angle);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "ATAN(1.0)", "0.7853981", ""}, {}},
        {"TRUNC", "math", {{"IN", "REAL", "un r\xC3\xA9" "el", false}}, "DINT", "La partie enti\xC3\xA8re, vers z\xC3\xA9ro : TRUNC(2.7) = 2, TRUNC(-2.7) = -2.",
         "Entier := TRUNC(Niveau);",
         "Entier = (int32_t)truncf(Niveau);",
         "Entier = static_cast<DINT>(std::trunc(Niveau));",
         Avail::Equivalent, Avail::Equivalent, true, false, {"DINT", "TRUNC(2.7)", "2", ""}, {"Pour arrondir au plus proche, REAL_TO_INT ou ROUND."}},
        {"ROUND", "math", {{"IN", "REAL", "un r\xC3\xA9" "el", false}, {"N", "INT", "le nombre de d\xC3\xA9" "cimales", true}}, "REAL", "L'arrondi au plus proche : \xC3\xA0 l'entier, ou \xC3\xA0 N d\xC3\xA9" "cimales.",
         "Affiche := ROUND(Niveau, 1);",
         "Affiche = roundf(Niveau * 10.0f) / 10.0f;",
         "Affiche = std::round(Niveau * 10.0f) / 10.0f;",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "ROUND(2.47, 1)", "2.5", ""}, {}},
        {"NEG", "math", {{"IN", "ANY_NUM", "un nombre", false}}, "comme IN", "L'oppos\xC3\xA9 : NEG(x) = -x.",
         "Oppose := NEG(Vitesse);",
         "Oppose = -Vitesse;",
         "Oppose = -Vitesse;",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "NEG(4.0)", "-4", ""}, {}},
        {"SEL", "select", {{"G", "BOOL", "la condition", false}, {"IN0", "ANY", "si G est faux", false}, {"IN1", "ANY", "si G est vrai", false}}, "comme IN0", "IN0 si G est faux, IN1 si G est vrai.",
         "Couleur := SEL(Marche, '#808080', '#2ECC71');",
         "Couleur = Marche ? \"#2ECC71\" : \"#808080\";   /* SEL(G, si faux, si vrai) */",
         "Couleur = Marche ? \"#2ECC71\"s : \"#808080\"s;",
         Avail::Same, Avail::Equivalent, true, false, {"STRING", "SEL(Marche, 'Arr\xC3\xAAt', 'Marche')", "Marche", ""}, {"Attention \xC3\xA0 l'ordre : la valeur \xC2\xAB faux \xC2\xBB vient d'abord."}},
        {"MUX", "select", {{"K", "INT", "le rang (0 : IN0)", false}, {"IN0\xE2\x80\xA6INn", "ANY", "les valeurs", false}}, "comme IN0", "La valeur de rang K : IN0 pour 0, IN1 pour 1...",
         "Libelle := MUX(Etape, 'Arr\xC3\xAAt', 'D\xC3\xA9marrage', 'Production');",
         "static const char* libelles[] = {\"Arr\xC3\xAAt\", \"D\xC3\xA9marrage\", \"Production\"};\nLibelle = libelles[Etape];",
         "Libelle = std::array{\"Arr\xC3\xAAt\"s, \"D\xC3\xA9marrage\"s, \"Production\"s}.at(Etape);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"STRING", "MUX(1, 'A', 'B', 'C')", "B", ""}, {"Hors des bornes (K n\xC3\xA9gatif ou trop grand), MUX rend IN0."}},
        {"MIN", "select", {{"IN1\xE2\x80\xA6INn", "ANY", "deux valeurs ou plus", false}}, "comme IN1", "La plus petite des valeurs.",
         "Bas := MIN(Mesure_1, Mesure_2, Mesure_3);",
         "Bas = fminf(fminf(Mesure_1, Mesure_2), Mesure_3);",
         "Bas = std::min({Mesure_1, Mesure_2, Mesure_3});",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "MIN(3.0, 1.5, 2.0)", "1.5", ""}, {}},
        {"MAX", "select", {{"IN1\xE2\x80\xA6INn", "ANY", "deux valeurs ou plus", false}}, "comme IN1", "La plus grande des valeurs.",
         "Haut := MAX(Mesure_1, Mesure_2);",
         "Haut = fmaxf(Mesure_1, Mesure_2);",
         "Haut = std::max(Mesure_1, Mesure_2);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "MAX(3.0, 1.5)", "3", ""}, {}},
        {"LIMIT", "select", {{"MN", "ANY", "la borne basse", false}, {"IN", "ANY", "la valeur", false}, {"MX", "ANY", "la borne haute", false}}, "comme IN", "IN born\xC3\xA9 entre MN et MX.",
         "Consigne := LIMIT(0.0, Saisie, 100.0);",
         "Consigne = fminf(fmaxf(Saisie, 0.0f), 100.0f);",
         "Consigne = std::clamp(Saisie, 0.0f, 100.0f);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "LIMIT(0.0, 150.0, 100.0)", "100", ""}, {"L'ordre est celui de la norme : la borne basse d'abord."}},
        {"LEN", "texte", {{"IN", "STRING", "le texte", false}}, "INT", "Le nombre de caract\xC3\xA8res.",
         "Longueur := LEN(Texte);",
         "Longueur = strlen(Texte);",
         "Longueur = Texte.size();",
         Avail::Equivalent, Avail::Equivalent, true, false, {"INT", "LEN(Texte)", "7", ""}, {}},
        {"LEFT", "texte", {{"IN", "STRING", "le texte", false}, {"L", "INT", "le nombre de caract\xC3\xA8res", false}}, "STRING", "Les L premiers caract\xC3\xA8res.",
         "Prefixe := LEFT(Texte, 5);",
         "strncpy(Prefixe, Texte, 5); Prefixe[5] = '\\0';",
         "Prefixe = Texte.substr(0, 5);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"STRING", "LEFT(Texte, 5)", "Pompe", ""}, {}},
        {"RIGHT", "texte", {{"IN", "STRING", "le texte", false}, {"L", "INT", "le nombre de caract\xC3\xA8res", false}}, "STRING", "Les L derniers caract\xC3\xA8res.",
         "Suffixe := RIGHT(Texte, 1);",
         "strcpy(Suffixe, Texte + strlen(Texte) - 1);",
         "Suffixe = Texte.substr(Texte.size() - 1);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"STRING", "RIGHT(Texte, 1)", "3", ""}, {}},
        {"MID", "texte", {{"IN", "STRING", "le texte", false}, {"L", "INT", "le nombre de caract\xC3\xA8res", false}, {"P", "INT", "la position du premier (1 : le d\xC3\xA9" "but)", false}}, "STRING", "L caract\xC3\xA8res \xC3\xA0 partir de la position P.",
         "Milieu := MID(Texte, 3, 2);",
         "strncpy(Milieu, Texte + 1, 3); Milieu[3] = '\\0';",
         "Milieu = Texte.substr(1, 3);   // P - 1",
         Avail::Equivalent, Avail::Equivalent, true, false, {"STRING", "MID(Texte, 3, 2)", "omp", ""}, {"Les positions commencent \xC3\xA0 1, comme dans l'automate."}},
        {"CONCAT", "texte", {{"IN1\xE2\x80\xA6INn", "STRING", "deux textes ou plus", false}}, "STRING", "Les textes mis bout \xC3\xA0 bout.",
         "Titre := CONCAT('Vanne ', Nom, ' : ', Etat);",
         "snprintf(Titre, sizeof Titre, \"Vanne %s : %s\", Nom, Etat);",
         "Titre = \"Vanne \" + Nom + \" : \" + Etat;",
         Avail::Equivalent, Avail::Equivalent, true, false, {"STRING", "CONCAT('Vanne ', 'V-201')", "Vanne V-201", ""}, {"+ ne colle pas deux textes en ST : CONCAT le fait."}},
        {"INSERT", "texte", {{"IN1", "STRING", "le texte", false}, {"IN2", "STRING", "ce qu'on ins\xC3\xA8re", false}, {"P", "INT", "apr\xC3\xA8s ce caract\xC3\xA8re", false}}, "STRING", "IN2 ins\xC3\xA9r\xC3\xA9 dans IN1 apr\xC3\xA8s la position P.",
         "Code := INSERT('AB', '-', 1);",
         "/* pas de fonction en C : memmove puis memcpy */",
         "Code = std::string(\"AB\").insert(1, \"-\");",
         Avail::None, Avail::Equivalent, true, false, {"STRING", "INSERT('AB', '-', 1)", "A-B", ""}, {}},
        {"DELETE", "texte", {{"IN", "STRING", "le texte", false}, {"L", "INT", "le nombre de caract\xC3\xA8res", false}, {"P", "INT", "la position du premier", false}}, "STRING", "Le texte sans ses L caract\xC3\xA8res \xC3\xA0 partir de P.",
         "Court := DELETE(Texte, 2, 1);",
         "/* pas de fonction en C : memmove */",
         "Court = std::string(Texte).erase(0, 2);   // P - 1",
         Avail::None, Avail::Equivalent, true, false, {"STRING", "DELETE(Texte, 2, 1)", "mpe 3", ""}, {}},
        {"REPLACE", "texte", {{"IN1", "STRING", "le texte", false}, {"IN2", "STRING", "le rempla\xC3\xA7" "ant", false}, {"L", "INT", "le nombre de caract\xC3\xA8res remplac\xC3\xA9s", false}, {"P", "INT", "la position du premier", false}}, "STRING", "L caract\xC3\xA8res de IN1, \xC3\xA0 partir de P, remplac\xC3\xA9s par IN2.",
         "Nouveau := REPLACE(Texte, 'Vanne', 5, 1);",
         "/* pas de fonction en C */",
         "Nouveau = std::string(Texte).replace(0, 5, \"Vanne\");   // P - 1",
         Avail::None, Avail::Equivalent, true, false, {"STRING", "REPLACE(Texte, 'Vanne', 5, 1)", "Vanne 3", ""}, {}},
        {"FIND", "texte", {{"IN1", "STRING", "le texte", false}, {"IN2", "STRING", "ce qu'on cherche", false}}, "INT", "La position de IN2 dans IN1 (1 : au d\xC3\xA9" "but), 0 s'il n'y est pas.",
         "IF FIND(Message, 'D\xC3\xA9" "faut') > 0 THEN Alerte := TRUE; END_IF",
         "const char* p = strstr(Message, \"D\xC3\xA9" "faut\");\nPosition = p ? (int)(p - Message) + 1 : 0;",
         "Position = Message.find(\"D\xC3\xA9" "faut\") + 1;   // npos + 1 = 0",
         Avail::Equivalent, Avail::Equivalent, true, false, {"INT", "FIND(Texte, '3')", "7", ""}, {}},
        {"TO_UPPER", "texte", {{"IN", "STRING", "le texte", false}}, "STRING", "Le texte en majuscules.",
         "Code := TO_UPPER(Saisie);",
         "for (char* q = Code; *q; ++q) *q = toupper(*q);",
         "std::transform(Code.begin(), Code.end(), Code.begin(), ::toupper);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"STRING", "TO_UPPER('vanne')", "VANNE", ""}, {}},
        {"TO_LOWER", "texte", {{"IN", "STRING", "le texte", false}}, "STRING", "Le texte en minuscules.",
         "Cle := TO_LOWER(Saisie);",
         "for (char* q = Cle; *q; ++q) *q = tolower(*q);",
         "std::transform(Cle.begin(), Cle.end(), Cle.begin(), ::tolower);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"STRING", "TO_LOWER('VANNE')", "vanne", ""}, {}},
        {"SHL", "bits", {{"IN", "ANY_BIT", "le mot", false}, {"N", "INT", "le nombre de bits", false}}, "comme IN", "Les bits d\xC3\xA9" "cal\xC3\xA9s de N vers la gauche (des z\xC3\xA9ros entrent \xC3\xA0 droite).",
         "Masque := SHL(Mot, 4);",
         "Masque = (uint16_t)(Mot << 4);",
         "Masque = static_cast<WORD>(Mot << 4);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"WORD", "SHL(Mot, 4)", "3840", ""}, {}},
        {"SHR", "bits", {{"IN", "ANY_BIT", "le mot", false}, {"N", "INT", "le nombre de bits", false}}, "comme IN", "Les bits d\xC3\xA9" "cal\xC3\xA9s de N vers la droite (des z\xC3\xA9ros entrent \xC3\xA0 gauche).",
         "Haut := SHR(Mot, 4);",
         "Haut = Mot >> 4;",
         "Haut = Mot >> 4;",
         Avail::Equivalent, Avail::Equivalent, true, false, {"WORD", "SHR(Mot, 4)", "15", ""}, {}},
        {"ROL", "bits", {{"IN", "ANY_BIT", "le mot", false}, {"N", "INT", "le nombre de bits", false}}, "comme IN", "Les bits tourn\xC3\xA9s de N vers la gauche (ceux qui sortent reviennent \xC3\xA0 droite).",
         "Tourne := ROL(Mot, 8);",
         "Tourne = (uint16_t)((Mot << 8) | (Mot >> 8));",
         "Tourne = std::rotl(Mot, 8);   // C++20, <bit>",
         Avail::Equivalent, Avail::Equivalent, true, false, {"WORD", "ROL(Mot, 8)", "61440", ""}, {}},
        {"ROR", "bits", {{"IN", "ANY_BIT", "le mot", false}, {"N", "INT", "le nombre de bits", false}}, "comme IN", "Les bits tourn\xC3\xA9s de N vers la droite.",
         "Tourne := ROR(Mot, 4);",
         "Tourne = (uint16_t)((Mot >> 4) | (Mot << 12));",
         "Tourne = std::rotr(Mot, 4);   // C++20, <bit>",
         Avail::Equivalent, Avail::Equivalent, true, false, {"WORD", "ROR(Mot, 4)", "15", ""}, {}},
        {"TO_STRING", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "STRING", "La valeur convertie en STRING, quel que soit son type.",
         "Resultat := TO_STRING(Valeur);",
         "snprintf(Resultat, sizeof Resultat, \"%d\", Valeur);",
         "Resultat = std::to_string(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"STRING", "TO_STRING(42)", "42", ""}, {"Sur une \xC3\xA9num\xC3\xA9ration IHM, TO_STRING rend le texte de sa valeur (son op\xC3\xA9rateur toString, s'il en a un)."}},
        {"TO_REAL", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "REAL", "La valeur convertie en REAL, quel que soit son type.",
         "Resultat := TO_REAL(Valeur);",
         "Resultat = (float)Valeur;",
         "Resultat = static_cast<float>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "TO_REAL(Compteur)", "7", ""}, {}},
        {"TO_LREAL", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "LREAL", "La valeur convertie en LREAL, quel que soit son type.",
         "Resultat := TO_LREAL(Valeur);",
         "Resultat = (double)Valeur;",
         "Resultat = static_cast<double>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"LREAL", "TO_LREAL(Compteur)", "7", ""}, {}},
        {"TO_BOOL", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "BOOL", "La valeur convertie en BOOL, quel que soit son type.",
         "Resultat := TO_BOOL(Valeur);",
         "Resultat = (bool)Valeur;",
         "Resultat = static_cast<bool>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"BOOL", "TO_BOOL(1)", "TRUE", ""}, {}},
        {"TO_INT", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "INT", "La valeur convertie en INT, quel que soit son type.",
         "Resultat := TO_INT(Valeur);",
         "Resultat = (int16_t)Valeur;",
         "Resultat = static_cast<int16_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"INT", "TO_INT(2.6)", "3", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_DINT", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "DINT", "La valeur convertie en DINT, quel que soit son type.",
         "Resultat := TO_DINT(Valeur);",
         "Resultat = (int32_t)Valeur;",
         "Resultat = static_cast<int32_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"DINT", "TO_DINT(Niveau)", "43", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_UINT", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "UINT", "La valeur convertie en UINT, quel que soit son type.",
         "Resultat := TO_UINT(Valeur);",
         "Resultat = (uint16_t)Valeur;",
         "Resultat = static_cast<uint16_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"UINT", "TO_UINT(Compteur)", "7", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_UDINT", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "UDINT", "La valeur convertie en UDINT, quel que soit son type.",
         "Resultat := TO_UDINT(Valeur);",
         "Resultat = (uint32_t)Valeur;",
         "Resultat = static_cast<uint32_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"UDINT", "TO_UDINT(Compteur)", "7", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_SINT", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "SINT", "La valeur convertie en SINT, quel que soit son type.",
         "Resultat := TO_SINT(Valeur);",
         "Resultat = (int8_t)Valeur;",
         "Resultat = static_cast<int8_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"INT", "TO_SINT(100)", "100", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_USINT", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "USINT", "La valeur convertie en USINT, quel que soit son type.",
         "Resultat := TO_USINT(Valeur);",
         "Resultat = (uint8_t)Valeur;",
         "Resultat = static_cast<uint8_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"INT", "TO_USINT(200)", "200", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_LINT", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "LINT", "La valeur convertie en LINT, quel que soit son type.",
         "Resultat := TO_LINT(Valeur);",
         "Resultat = (int64_t)Valeur;",
         "Resultat = static_cast<int64_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"DINT", "TO_LINT(Compteur)", "7", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_ULINT", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "ULINT", "La valeur convertie en ULINT, quel que soit son type.",
         "Resultat := TO_ULINT(Valeur);",
         "Resultat = (uint64_t)Valeur;",
         "Resultat = static_cast<uint64_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"UDINT", "TO_ULINT(Compteur)", "7", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_WORD", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "WORD", "La valeur convertie en WORD, quel que soit son type.",
         "Resultat := TO_WORD(Valeur);",
         "Resultat = (uint16_t)Valeur;",
         "Resultat = static_cast<uint16_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"WORD", "TO_WORD(255)", "255", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_DWORD", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "DWORD", "La valeur convertie en DWORD, quel que soit son type.",
         "Resultat := TO_DWORD(Valeur);",
         "Resultat = (uint32_t)Valeur;",
         "Resultat = static_cast<uint32_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"DWORD", "TO_DWORD(Compteur)", "7", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_BYTE", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "BYTE", "La valeur convertie en BYTE, quel que soit son type.",
         "Resultat := TO_BYTE(Valeur);",
         "Resultat = (uint8_t)Valeur;",
         "Resultat = static_cast<uint8_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"INT", "TO_BYTE(65)", "65", ""}, {"Un r\xC3\xA9" "el vers un entier s'arrondit au plus proche (comme REAL_TO_INT)."}},
        {"TO_TIME", "conv", {{"IN", "ANY", "la valeur \xC3\xA0 convertir", false}}, "TIME", "La valeur convertie en TIME, quel que soit son type.",
         "Resultat := TO_TIME(Valeur);",
         "Resultat = (uint32_t)Valeur;",
         "Resultat = static_cast<uint32_t>(Valeur);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"TIME", "TO_TIME(1500)", "T#1500ms", ""}, {}},
        {"SIZEOF", "tab", {{"IN", "ARRAY ou MAP", "un tableau, une MAP", false}}, "DINT", "Le nombre de cases d'un tableau (toutes dimensions), ou de cl\xC3\xA9s d'une MAP.",
         "FOR i := 1 TO SIZEOF(Tab) DO Somme := Somme + Tab[i]; END_FOR",
         "n = sizeof Tab / sizeof Tab[0];",
         "n = std::size(Tab);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"DINT", "SIZEOF(Tab)", "5", ""}, {"Ici, SIZEOF compte des cases, pas des octets (dans Control Expert, des octets)."}},
        {"LOWER_BOUND", "tab", {{"IN", "ARRAY", "le tableau", false}, {"DIM", "INT", "la dimension (1 : la premi\xC3\xA8re)", true}}, "DINT", "Le premier indice d'une dimension.",
         "FOR i := LOWER_BOUND(Tab, 1) TO UPPER_BOUND(Tab, 1) DO ... END_FOR",
         "/* une constante en C : les tableaux commencent \xC3\xA0 0 */",
         "// 0 en C++ ; Tab.front()",
         Avail::Equivalent, Avail::Equivalent, true, false, {"DINT", "LOWER_BOUND(Tab, 1)", "1", ""}, {}},
        {"UPPER_BOUND", "tab", {{"IN", "ARRAY", "le tableau", false}, {"DIM", "INT", "la dimension (1 : la premi\xC3\xA8re)", true}}, "DINT", "Le dernier indice d'une dimension.",
         "Dernier := Tab[UPPER_BOUND(Tab, 1)];",
         "Dernier = Tab[sizeof Tab / sizeof Tab[0] - 1];",
         "Dernier = Tab.back();",
         Avail::Equivalent, Avail::Equivalent, true, false, {"DINT", "UPPER_BOUND(Tab, 1)", "5", ""}, {}},
        {"MAP_HAS", "map", {{"M", "MAP", "la MAP", false}, {"CLE", "comme la cl\xC3\xA9", "la cl\xC3\xA9 cherch\xC3\xA9" "e", false}}, "BOOL", "Vrai si la cl\xC3\xA9 est dans la MAP.",
         "IF MAP_HAS(Stock, 'vis') THEN Stock['vis'] := Stock['vis'] - 1.0; END_IF",
         "/* pas de MAP en C */",
         "if (stock.count(\"vis\")) stock[\"vis\"] -= 1.0f;",
         Avail::None, Avail::Equivalent, false, false, {"BOOL", "MAP_HAS(m, 'vis')", "TRUE", "VAR m : MAP[STRING] OF REAL; END_VAR\nm['vis'] := 120.0;\nm['ecrou'] := 80.0;"}, {}},
        {"MAP_GET", "map", {{"M", "MAP", "la MAP", false}, {"CLE", "comme la cl\xC3\xA9", "la cl\xC3\xA9", false}, {"DEFAUT", "comme les valeurs", "la valeur si la cl\xC3\xA9 manque", true}}, "comme les valeurs", "La valeur d'une cl\xC3\xA9, sans la cr\xC3\xA9" "er (DEFAUT si elle manque).",
         "Qte := MAP_GET(Stock, 'vis', 0.0);",
         "/* pas de MAP en C */",
         "auto it = stock.find(\"vis\");\nQte = it != stock.end() ? it->second : 0.0f;",
         Avail::None, Avail::Equivalent, false, false, {"REAL", "MAP_GET(m, 'ecrou', 0.0)", "80", "VAR m : MAP[STRING] OF REAL; END_VAR\nm['vis'] := 120.0;\nm['ecrou'] := 80.0;"}, {"m['cle'] en lecture cr\xC3\xA9" "e la cl\xC3\xA9 ; MAP_GET ne cr\xC3\xA9" "e rien."}},
        {"MAP_REMOVE", "map", {{"M", "MAP", "la MAP", false}, {"CLE", "comme la cl\xC3\xA9", "la cl\xC3\xA9 \xC3\xA0 retirer", false}}, "BOOL", "Retire une cl\xC3\xA9 ; vrai si elle y \xC3\xA9tait.",
         "MAP_REMOVE(Stock, 'ecrou');",
         "/* pas de MAP en C */",
         "stock.erase(\"ecrou\");",
         Avail::None, Avail::Equivalent, false, false, {"BOOL", "MAP_REMOVE(m, 'vis')", "TRUE", "VAR m : MAP[STRING] OF REAL; END_VAR\nm['vis'] := 120.0;\nm['ecrou'] := 80.0;"}, {}},
        {"MAP_SIZE", "map", {{"M", "MAP", "la MAP", false}}, "DINT", "Le nombre de cl\xC3\xA9s.",
         "Nb := MAP_SIZE(Stock);",
         "/* pas de MAP en C */",
         "Nb = stock.size();",
         Avail::None, Avail::Equivalent, false, false, {"DINT", "MAP_SIZE(m)", "2", "VAR m : MAP[STRING] OF REAL; END_VAR\nm['vis'] := 120.0;\nm['ecrou'] := 80.0;"}, {}},
        {"MAP_CLEAR", "map", {{"M", "MAP", "la MAP", false}}, "BOOL", "Retire toutes les cl\xC3\xA9s.",
         "MAP_CLEAR(Stock);",
         "/* pas de MAP en C */",
         "stock.clear();",
         Avail::None, Avail::Equivalent, false, false, {}, {}},
        {"MAP_KEYS", "map", {{"M", "MAP", "la MAP", false}}, "ARRAY OF cl\xC3\xA9", "Les cl\xC3\xA9s, dans l'ordre (un tableau).",
         "Cles := MAP_KEYS(Stock);",
         "/* pas de MAP en C */",
         "for (const auto& [cle, v] : stock) cles.push_back(cle);",
         Avail::None, Avail::Equivalent, false, false, {}, {}},
        {"MAP_BEGIN", "map", {{"M", "MAP", "la MAP", false}}, "MAP_ITERATOR", "Un it\xC3\xA9rateur sur la premi\xC3\xA8re cl\xC3\xA9.",
         "it := MAP_BEGIN(Stock);\nWHILE NOT MAP_END(it) DO\n    Total := Total + it.Value;\n    MAP_NEXT(it);\nEND_WHILE",
         "/* pas de MAP en C */",
         "for (auto it = stock.begin(); it != stock.end(); ++it) total += it->second;",
         Avail::None, Avail::Equivalent, false, false, {}, {"FOR EACH cle, valeur IN m DO ... END_FOR fait le m\xC3\xAAme parcours, plus simplement."}},
        {"MAP_NEXT", "map", {{"IT", "MAP_ITERATOR", "l'it\xC3\xA9rateur", false}}, "BOOL", "Passe \xC3\xA0 la cl\xC3\xA9 suivante ; faux \xC3\xA0 la fin.",
         "MAP_NEXT(it);",
         "/* pas de MAP en C */",
         "++it;",
         Avail::None, Avail::Equivalent, false, false, {}, {}},
        {"MAP_END", "map", {{"IT", "MAP_ITERATOR", "l'it\xC3\xA9rateur", false}}, "BOOL", "Vrai quand l'it\xC3\xA9rateur a pass\xC3\xA9 la derni\xC3\xA8re cl\xC3\xA9.",
         "WHILE NOT MAP_END(it) DO ... END_WHILE",
         "/* pas de MAP en C */",
         "it != stock.end()",
         Avail::None, Avail::Equivalent, false, false, {}, {}},
        {"REF", "ref", {{"X", "une variable", "pas une valeur calcul\xC3\xA9" "e", false}}, "REF_TO type de X", "Une r\xC3\xA9" "f\xC3\xA9rence vers une variable : l'\xC3\xA9" "crire par la r\xC3\xA9" "f\xC3\xA9rence \xC3\xA9" "crit la variable.",
         "VAR r : REF_TO REAL; END_VAR\nr := REF(Niveau);\nr^ := 50.0;   (* Niveau vaut 50 *)",
         "float* r = &Niveau;\n*r = 50.0f;",
         "float& r = Niveau;\nr = 50.0f;",
         Avail::Equivalent, Avail::Equivalent, false, false, {}, {}},
        {"ADR", "ref", {{"X", "une variable", "pas une valeur calcul\xC3\xA9" "e", false}}, "POINTER TO type de X", "Un pointeur vers une variable (comme REF, pour POINTER TO).",
         "VAR p : POINTER TO INT; END_VAR\np := ADR(Compteur);\np^ := p^ + 1;",
         "int16_t* p = &Compteur;\n*p += 1;",
         "auto* p = &Compteur;\n*p += 1;",
         Avail::Equivalent, Avail::Equivalent, false, false, {}, {}},
        {"IHM_NAVIGUER", "nav", {{"VUE", "STRING", "le nom de la vue", false}, {"TRANSITION", "STRING", "Fondu, Glissement, Zoom, Rotation...", true}, {"PARAMETRES", "STRING", "'Moteur := Pompes[3]'", true}}, "BOOL", "Affiche une autre vue, avec une transition et des param\xC3\xA8tres.",
         "IHM_NAVIGUER('Vue_Armoire_A', 'Glissement');",
         "IHM_NAVIGUER(\"Vue_Armoire_A\", \"Glissement\");",
         "IHM_NAVIGUER(\"Vue_Armoire_A\", \"Glissement\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_PRECEDENTE", "nav", {}, "BOOL", "Revient \xC3\xA0 la vue d'avant (l'historique) ; vrai si la vue a chang\xC3\xA9.",
         "IHM_PRECEDENTE();",
         "IHM_PRECEDENTE();",
         "IHM_PRECEDENTE();",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_SUIVANTE", "nav", {}, "BOOL", "Repart vers la vue quitt\xC3\xA9" "e par Pr\xC3\xA9" "c\xC3\xA9" "dente.",
         "IHM_SUIVANTE();",
         "IHM_SUIVANTE();",
         "IHM_SUIVANTE();",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_ACCUEIL", "nav", {}, "BOOL", "Ouvre la vue d'accueil : celle du groupe de l'utilisateur, sinon la vue de d\xC3\xA9marrage.",
         "IHM_ACCUEIL();",
         "IHM_ACCUEIL();",
         "IHM_ACCUEIL();",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_VUE", "nav", {}, "STRING", "Le nom de la vue affich\xC3\xA9" "e.",
         "IF IHM_VUE() = 'Vue_Accueil' THEN ... END_IF",
         "if (strcmp(IHM_VUE(), \"Vue_Accueil\") == 0) { /* ... */ }",
         "if (IHM_VUE() == \"Vue_Accueil\") { /* ... */ }",
         Avail::Same, Avail::Same, true, true, {"STRING", "IHM_VUE()", "Vue_Essai", ""}, {"Dans une expression (fx) ou un texte \xC3\xA0 trous : oui, elle ne fait que lire."}},
        {"IHM_POPUP", "popup", {{"VUE", "STRING", "la popup", false}, {"PARAMETRES", "STRING", "'Moteur := Pompes[3]'", true}, {"POSITION", "STRING", "centre, objet, haut-droite, derniere, x,y", true}}, "BOOL", "Ouvre une popup, avec ses param\xC3\xA8tres et sa place ; d\xC3\xA9j\xC3\xA0 ouverte, elle revient devant.",
         "IHM_POPUP('Popup_Pompe', 'Moteur := Pompes[3]', 'objet');",
         "IHM_POPUP(\"Popup_Pompe\", \"Moteur = Pompes[3]\", \"objet\");",
         "IHM_POPUP(\"Popup_Pompe\", \"Moteur = Pompes[3]\", \"objet\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_CHANGER_POPUP", "popup", {{"VUE", "STRING", "la popup", false}, {"PARAMETRES", "STRING", "ses param\xC3\xA8tres", true}}, "BOOL", "Remplace la popup du dessus par une autre (ou la m\xC3\xAAme, avec d'autres param\xC3\xA8tres), au m\xC3\xAAme endroit.",
         "IHM_CHANGER_POPUP('Popup_Pompe', 'Moteur := Pompes[4]');",
         "IHM_CHANGER_POPUP(\"Popup_Pompe\", \"Moteur = Pompes[4]\");",
         "IHM_CHANGER_POPUP(\"Popup_Pompe\", \"Moteur = Pompes[4]\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_POPUP_PRECEDENTE", "popup", {}, "BOOL", "Revient \xC3\xA0 la popup d'avant le changement, \xC3\xA0 sa place.",
         "IHM_POPUP_PRECEDENTE();",
         "IHM_POPUP_PRECEDENTE();",
         "IHM_POPUP_PRECEDENTE();",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_CENTRER_POPUP", "popup", {{"VUE", "STRING", "la popup (sans : celle du dessus)", true}}, "BOOL", "Ram\xC3\xA8ne une popup au milieu de la vue.",
         "IHM_CENTRER_POPUP();",
         "IHM_CENTRER_POPUP(NULL);",
         "IHM_CENTRER_POPUP();",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_FERMER_POPUP", "popup", {{"VUE", "STRING", "la popup (sans : celle du dessus)", true}}, "BOOL", "Ferme la popup du dessus (ou celle-ci).",
         "IHM_FERMER_POPUP();",
         "IHM_FERMER_POPUP(NULL);",
         "IHM_FERMER_POPUP();",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_FERMER_POPUPS", "popup", {}, "BOOL", "Ferme toutes les popups.",
         "IHM_FERMER_POPUPS();",
         "IHM_FERMER_POPUPS();",
         "IHM_FERMER_POPUPS();",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_POPUP_OUVERTE", "popup", {{"VUE", "STRING", "la popup", false}}, "BOOL", "Vrai si cette popup est ouverte.",
         "IF NOT IHM_POPUP_OUVERTE('Popup_Aide') THEN IHM_POPUP('Popup_Aide'); END_IF",
         "if (!IHM_POPUP_OUVERTE(\"Popup_Aide\")) IHM_POPUP(\"Popup_Aide\", NULL, NULL);",
         "if (!IHM_POPUP_OUVERTE(\"Popup_Aide\")) IHM_POPUP(\"Popup_Aide\");",
         Avail::Same, Avail::Same, true, true, {"BOOL", "IHM_POPUP_OUVERTE('Popup_Aide')", "FALSE", ""}, {"Dans une expression (fx) ou un texte \xC3\xA0 trous : oui, elle ne fait que lire."}},
        {"IHM_JOURNAL", "journal", {{"MESSAGE", "STRING", "{Variable} ou {Variable:0.0} y met sa valeur", false}}, "BOOL", "\xC3\x89" "crit une ligne dans le journal de la s\xC3\xA9" "ance.",
         "IHM_JOURNAL('Passage en maintenance \xC3\xA0 {IHM_TEMPS():t}');",
         "IHM_JOURNAL(\"Passage en maintenance \xC3\xA0 {IHM_TEMPS():t}\");",
         "IHM_JOURNAL(\"Passage en maintenance \xC3\xA0 {IHM_TEMPS():t}\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_LOG", "journal", {{"NIVEAU", "NIVEAU_LOG", "TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL", false}, {"MESSAGE", "STRING", "{Variable} y met sa valeur", false}}, "BOOL", "\xC3\x89" "crit une ligne dans la Console : l'heure, le niveau, la source et la ligne du code.",
         "IHM_LOG(WARNING, 'Pression haute : {Pression:0.00} bar');",
         "IHM_LOG(LOG_WARNING, \"Pression haute : {Pression:0.00} bar\");",
         "IHM_LOG(NiveauLog::WARNING, \"Pression haute : {Pression:0.00} bar\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_APPELER", "script", {{"SCRIPT", "STRING", "un script g\xC3\xA9n\xC3\xA9ral", false}}, "BOOL", "Ex\xC3\xA9" "cute tout de suite un script g\xC3\xA9n\xC3\xA9ral.",
         "IHM_APPELER('Recalcul');",
         "IHM_APPELER(\"Recalcul\");",
         "IHM_APPELER(\"Recalcul\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_TEMPS", "script", {}, "TIME", "Le temps \xC3\xA9" "coul\xC3\xA9 depuis le lancement de l'IHM.",
         "IF IHM_TEMPS() > T#10s THEN ... END_IF",
         "if (IHM_TEMPS() > 10000) { /* ... */ }   /* TIME : des ms */",
         "if (IHM_TEMPS() > 10s) { /* ... */ }   // <chrono>",
         Avail::Same, Avail::Same, true, true, {}, {"Dans une expression (fx) ou un texte \xC3\xA0 trous : oui, elle ne fait que lire."}},
        {"IHM_UTILISATEUR", "user", {}, "STRING", "L'identifiant de l'utilisateur connect\xC3\xA9 ('' sans).",
         "IF IHM_UTILISATEUR() = '' THEN IHM_MENU_CONNEXION(); END_IF",
         "if (strcmp(IHM_UTILISATEUR(), \"\") == 0) IHM_MENU_CONNEXION(NULL);",
         "if (IHM_UTILISATEUR().empty()) IHM_MENU_CONNEXION();",
         Avail::Same, Avail::Same, true, true, {"STRING", "IHM_UTILISATEUR()", "", ""}, {"Dans une expression (fx) ou un texte \xC3\xA0 trous : oui, elle ne fait que lire."}},
        {"IHM_NOM_UTILISATEUR", "user", {}, "STRING", "Le nom de l'utilisateur connect\xC3\xA9.",
         "Bienvenue := CONCAT('Bonjour ', IHM_NOM_UTILISATEUR());",
         "snprintf(Bienvenue, sizeof Bienvenue, \"Bonjour %s\", IHM_NOM_UTILISATEUR());",
         "Bienvenue = \"Bonjour \" + IHM_NOM_UTILISATEUR();",
         Avail::Same, Avail::Same, true, true, {}, {"Dans une expression (fx) ou un texte \xC3\xA0 trous : oui, elle ne fait que lire."}},
        {"IHM_GROUPE", "user", {}, "STRING", "Le groupe de l'utilisateur connect\xC3\xA9.",
         "Admin := IHM_GROUPE() = 'Maintenance';",
         "Admin = strcmp(IHM_GROUPE(), \"Maintenance\") == 0;",
         "Admin = IHM_GROUPE() == \"Maintenance\";",
         Avail::Same, Avail::Same, true, true, {}, {"Dans une expression (fx) ou un texte \xC3\xA0 trous : oui, elle ne fait que lire."}},
        {"IHM_NIVEAU", "user", {}, "INT", "Le niveau d'acc\xC3\xA8s de l'utilisateur connect\xC3\xA9 : 0 si personne ne l'est ; sans gestion des utilisateurs, 99 (tous les droits).",
         "Reglage_Permis := IHM_NIVEAU() >= 2;",
         "Reglage_Permis = IHM_NIVEAU() >= 2;",
         "Reglage_Permis = IHM_NIVEAU() >= 2;",
         Avail::Same, Avail::Same, true, true, {"INT", "IHM_NIVEAU()", "99", ""}, {"Dans une expression (fx) ou un texte \xC3\xA0 trous : oui, elle ne fait que lire."}},
        {"IHM_DECONNECTER", "user", {}, "BOOL", "D\xC3\xA9" "connecte l'utilisateur.",
         "IHM_DECONNECTER();",
         "IHM_DECONNECTER();",
         "IHM_DECONNECTER();",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_MENU_CONNEXION", "user", {{"ONGLET", "STRING", "Comptes, Acc\xC3\xA8s, Journal, Mon compte", true}}, "BOOL", "Ouvre le menu natif de connexion (sur cet onglet, s'il se voit).",
         "IHM_MENU_CONNEXION('Mon compte');",
         "IHM_MENU_CONNEXION(\"Mon compte\");",
         "IHM_MENU_CONNEXION(\"Mon compte\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_METTRE_DE_COTE", "alarme", {{"ALARME", "STRING", "une alarme, ou 'groupe:Zone'", false}, {"MINUTES", "REAL", "0 : sans limite", true}, {"RAISON", "STRING", "pour le journal", true}}, "INT", "Met une alarme de c\xC3\xB4t\xC3\xA9 : elle n'appara\xC3\xAEt plus jusqu'\xC3\xA0 la fin du d\xC3\xA9lai ; rend le nombre mis de c\xC3\xB4t\xC3\xA9.",
         "IHM_METTRE_DE_COTE('Pression_Haute', 30.0, 'Capteur en r\xC3\xA9paration');",
         "IHM_METTRE_DE_COTE(\"Pression_Haute\", 30.0, \"Capteur en r\xC3\xA9paration\");",
         "IHM_METTRE_DE_COTE(\"Pression_Haute\", 30.0, \"Capteur en r\xC3\xA9paration\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_REMETTRE", "alarme", {{"ALARME", "STRING", "'*' : toutes", false}}, "INT", "Remet en service une alarme mise de c\xC3\xB4t\xC3\xA9.",
         "IHM_REMETTRE('*');",
         "IHM_REMETTRE(\"*\");",
         "IHM_REMETTRE(\"*\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_FAIRE_TAIRE", "alarme", {}, "BOOL", "Coupe le son des alarmes jusqu'\xC3\xA0 la prochaine apparition.",
         "IHM_FAIRE_TAIRE();",
         "IHM_FAIRE_TAIRE();",
         "IHM_FAIRE_TAIRE();",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_LANGUE", "affichage", {{"LANGUE", "STRING", "un code ('en'), un nom ('English') ou 'suivante'", false}}, "BOOL", "Change la langue de l'IHM ; vrai si elle est connue (Configuration \xE2\x80\xBA Langues).",
         "IHM_LANGUE('en');",
         "IHM_LANGUE(\"en\");",
         "IHM_LANGUE(\"en\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_THEME", "affichage", {{"THEME", "STRING", "'jour', 'nuit' ; sans : l'autre", true}}, "BOOL", "Change le th\xC3\xA8me de l'IHM.",
         "IHM_THEME('nuit');",
         "IHM_THEME(\"nuit\");",
         "IHM_THEME(\"nuit\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_PARAMETRES_SYSTEME", "affichage", {{"ONGLET", "STRING", "'Diagnostic' ; sinon R\xC3\xA9glages", true}}, "BOOL", "Ouvre le menu natif Param\xC3\xA8tres syst\xC3\xA8me.",
         "IHM_PARAMETRES_SYSTEME('Diagnostic');",
         "IHM_PARAMETRES_SYSTEME(\"Diagnostic\");",
         "IHM_PARAMETRES_SYSTEME(\"Diagnostic\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_SON", "affichage", {{"SON", "STRING", "un son des ressources (WAV, MP3, OGG)", false}}, "BOOL", "Joue un son des ressources.",
         "IHM_SON('Bip.wav');",
         "IHM_SON(\"Bip.wav\");",
         "IHM_SON(\"Bip.wav\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_GIF_JOUER", "gif", {{"OBJET", "STRING", "le GIF de la vue (ou d'une popup ouverte)", false}, {"TOURS", "INT", "0 : sans fin", true}}, "BOOL", "Joue un GIF anim\xC3\xA9 ; en pause, il reprend l\xC3\xA0 o\xC3\xB9 il s'\xC3\xA9tait arr\xC3\xAAt\xC3\xA9.",
         "IHM_GIF_JOUER('Vue_Ligne.Gif_Convoyeur');",
         "IHM_GIF_JOUER(\"Vue_Ligne.Gif_Convoyeur\");",
         "IHM_GIF_JOUER(\"Vue_Ligne.Gif_Convoyeur\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_GIF_PAUSE", "gif", {{"OBJET", "STRING", "le GIF", false}}, "BOOL", "Fige un GIF anim\xC3\xA9 sur l'image montr\xC3\xA9" "e.",
         "IHM_GIF_PAUSE('Vue_Ligne.Gif_Convoyeur');",
         "IHM_GIF_PAUSE(\"Vue_Ligne.Gif_Convoyeur\");",
         "IHM_GIF_PAUSE(\"Vue_Ligne.Gif_Convoyeur\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_GIF_ARRETER", "gif", {{"OBJET", "STRING", "le GIF", false}}, "BOOL", "Ram\xC3\xA8ne un GIF \xC3\xA0 sa premi\xC3\xA8re image ; il attend.",
         "IHM_GIF_ARRETER('Vue_Ligne.Gif_Convoyeur');",
         "IHM_GIF_ARRETER(\"Vue_Ligne.Gif_Convoyeur\");",
         "IHM_GIF_ARRETER(\"Vue_Ligne.Gif_Convoyeur\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_GIF_REJOUER", "gif", {{"OBJET", "STRING", "le GIF", false}, {"TOURS", "INT", "0 : sans fin", false}}, "BOOL", "Rejoue un GIF depuis le d\xC3\xA9" "but, pour ce nombre de tours.",
         "IHM_GIF_REJOUER('Vue_Ligne.Gif_Convoyeur', 3);",
         "IHM_GIF_REJOUER(\"Vue_Ligne.Gif_Convoyeur\", 3);",
         "IHM_GIF_REJOUER(\"Vue_Ligne.Gif_Convoyeur\", 3);",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"IHM_EQUIPEMENT_OK", "equip", {{"EQUIPEMENT", "STRING", "Configuration \xE2\x80\xBA \xC3\x89quipements", false}}, "BOOL", "Vrai si l'\xC3\xA9quipement est actif et r\xC3\xA9pond.",
         "Voyant_Reseau := IHM_EQUIPEMENT_OK('Variateur_ATV320');",
         "Voyant_Reseau = IHM_EQUIPEMENT_OK(\"Variateur_ATV320\");",
         "Voyant_Reseau = IHM_EQUIPEMENT_OK(\"Variateur_ATV320\");",
         Avail::Same, Avail::Same, true, true, {}, {"Dans une expression (fx) ou un texte \xC3\xA0 trous : oui, elle ne fait que lire."}},
        {"IHM_EQUIPEMENT_PING", "equip", {{"EQUIPEMENT", "STRING", "l'\xC3\xA9quipement", false}}, "REAL", "Le dernier ping de l'\xC3\xA9quipement, en ms (-1 : pas de r\xC3\xA9ponse).",
         "Latence := IHM_EQUIPEMENT_PING('Variateur_ATV320');",
         "Latence = IHM_EQUIPEMENT_PING(\"Variateur_ATV320\");",
         "Latence = IHM_EQUIPEMENT_PING(\"Variateur_ATV320\");",
         Avail::Same, Avail::Same, true, true, {}, {"Dans une expression (fx) ou un texte \xC3\xA0 trous : oui, elle ne fait que lire."}},
        {"IHM_ESCLAVE_SIMULE", "equip", {{"EQUIPEMENT", "STRING", "l'\xC3\xA9quipement", false}}, "BOOL", "Vrai si l'IHM lit cet \xC3\xA9quipement sur son esclave simul\xC3\xA9.",
         "Bandeau_Simule := IHM_ESCLAVE_SIMULE('Centrale_PM5560');",
         "Bandeau_Simule = IHM_ESCLAVE_SIMULE(\"Centrale_PM5560\");",
         "Bandeau_Simule = IHM_ESCLAVE_SIMULE(\"Centrale_PM5560\");",
         Avail::Same, Avail::Same, true, true, {}, {"Dans une expression (fx) ou un texte \xC3\xA0 trous : oui, elle ne fait que lire."}},
        {"IHM_EXPORTER", "export", {{"SOURCE", "STRING", "alarmes, historique, evenements, systeme, mesures, recette:Nom, objet:Nom", false}, {"FICHIER", "STRING", "l'extension choisit le format (.csv, .xlsx, .pdf)", true}, {"DEMANDER", "BOOL", "FALSE : ne jamais demander o\xC3\xB9 enregistrer", true}}, "BOOL", "Exporte des donn\xC3\xA9" "es dans exports/ du projet.",
         "IHM_EXPORTER('alarmes', 'alarmes_du_jour.xlsx');",
         "IHM_EXPORTER(\"alarmes\", \"alarmes_du_jour.xlsx\");",
         "IHM_EXPORTER(\"alarmes\", \"alarmes_du_jour.xlsx\");",
         Avail::Same, Avail::Same, false, false, {}, {"Elle agit : un script ou une fonction l'appelle, pas une expression (fx)."}},
        {"RGB", "couleur", {{"R", "INT", "le rouge, 0 \xC3\xA0 255", false}, {"G", "INT", "le vert, 0 \xC3\xA0 255", false}, {"B", "INT", "le bleu, 0 \xC3\xA0 255", false}}, "STRING", "La couleur de ces trois composantes : '#RRGGBB'.",
         "Fond := RGB(46, 204, 113);",
         "snprintf(Fond, sizeof Fond, \"#%02X%02X%02X\", 46, 204, 113);",
         "Fond = std::format(\"#{:02X}{:02X}{:02X}\", 46, 204, 113);   // C++20",
         Avail::Equivalent, Avail::Equivalent, true, false, {"STRING", "RGB(46, 204, 113)", "#2ECC71", ""}, {"Hors de 0 \xC3\xA0 255, une composante est ramen\xC3\xA9" "e \xC3\xA0 la borne ; un r\xC3\xA9" "el est arrondi."}},
        {"RGBA", "couleur", {{"R", "INT", "le rouge, 0 \xC3\xA0 255", false}, {"G", "INT", "le vert", false}, {"B", "INT", "le bleu", false}, {"A", "INT", "l'opacit\xC3\xA9, 0 (transparent) \xC3\xA0 255", false}}, "STRING", "La couleur et son opacit\xC3\xA9 : '#RRGGBBAA'.",
         "Voile := RGBA(0, 0, 0, 128);",
         "snprintf(Voile, sizeof Voile, \"#%02X%02X%02X%02X\", 0, 0, 0, 128);",
         "Voile = std::format(\"#{:02X}{:02X}{:02X}{:02X}\", 0, 0, 0, 128);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"STRING", "RGBA(46, 204, 113, 128)", "#2ECC7180", ""}, {}},
        {"HSL", "couleur", {{"H", "REAL", "la teinte, 0 \xC3\xA0 360\xC2\xB0", false}, {"S", "REAL", "la saturation, 0 \xC3\xA0 100 %", false}, {"L", "REAL", "la luminosit\xC3\xA9, 0 \xC3\xA0 100 %", false}}, "STRING", "La couleur d'une teinte, d'une saturation et d'une luminosit\xC3\xA9.",
         "Teinte := HSL(Niveau * 1.2, 80.0, 50.0);",
         "/* pas de fonction en C : la conversion TSL vers RVB est \xC3\xA0 \xC3\xA9" "crire */",
         "/* pas dans la biblioth\xC3\xA8que standard */",
         Avail::None, Avail::None, true, false, {"STRING", "HSL(120.0, 100.0, 50.0)", "#00FF00", ""}, {"0\xC2\xB0 : rouge ; 120\xC2\xB0 : vert ; 240\xC2\xB0 : bleu. Une teinte qui suit une mesure fait un arc-en-ciel."}},
        {"COULEUR_MELANGER", "couleur", {{"C1", "STRING", "la premi\xC3\xA8re couleur", false}, {"C2", "STRING", "la seconde", false}, {"T", "REAL", "0 : C1 ; 1 : C2 ; 0.5 : \xC3\xA0 mi-chemin", false}}, "STRING", "Le m\xC3\xA9lange de deux couleurs (opacit\xC3\xA9 comprise).",
         "Milieu := COULEUR_MELANGER('#000000', '#FFFFFF', 0.5);",
         "/* pas de fonction en C : composante par composante, c1 + (c2 - c1) * t */",
         "/* composante par composante : std::lerp(c1, c2, t) */",
         Avail::None, Avail::Equivalent, true, false, {"STRING", "COULEUR_MELANGER('#000000', '#FFFFFF', 0.5)", "#808080", ""}, {}},
        {"COULEUR_DEGRADE", "couleur", {{"V", "REAL", "la valeur", false}, {"MIN", "REAL", "la valeur de C1", false}, {"MAX", "REAL", "la valeur de C2", false}, {"C1", "STRING", "la couleur \xC3\xA0 MIN", false}, {"C2", "STRING", "la couleur \xC3\xA0 MAX", false}}, "STRING", "La couleur d'une valeur sur un d\xC3\xA9grad\xC3\xA9 : C1 \xC3\xA0 MIN, C2 \xC3\xA0 MAX, entre les deux au prorata.",
         "Couleur_Barre := COULEUR_DEGRADE(Niveau, 0.0, 100.0, '#2ECC71', '#E74C3C');",
         "/* pas de fonction en C */",
         "/* pas dans la biblioth\xC3\xA8que standard */",
         Avail::None, Avail::None, true, false, {"STRING", "COULEUR_DEGRADE(Niveau, 0.0, 100.0, '#2ECC71', '#E74C3C')", "#7D965A", ""}, {"Hors de MIN..MAX, la couleur du bout le plus proche. Pour une barre qui passe du vert au rouge quand elle se remplit."}},
        {"COULEUR_ECLAIRCIR", "couleur", {{"C", "STRING", "la couleur", false}, {"P", "REAL", "de combien, 0 \xC3\xA0 100 %", false}}, "STRING", "La couleur m\xC3\xAAl\xC3\xA9" "e de blanc : 100 % donne du blanc.",
         "Survol := COULEUR_ECLAIRCIR(Fond, 20.0);",
         "/* pas de fonction en C */",
         "/* pas dans la biblioth\xC3\xA8que standard */",
         Avail::None, Avail::None, true, false, {"STRING", "COULEUR_ECLAIRCIR('#2ECC71', 50.0)", "#97E6B8", ""}, {}},
        {"COULEUR_ASSOMBRIR", "couleur", {{"C", "STRING", "la couleur", false}, {"P", "REAL", "de combien, 0 \xC3\xA0 100 %", false}}, "STRING", "La couleur m\xC3\xAAl\xC3\xA9" "e de noir : 100 % donne du noir.",
         "Appui := COULEUR_ASSOMBRIR(Fond, 20.0);",
         "/* pas de fonction en C */",
         "/* pas dans la biblioth\xC3\xA8que standard */",
         Avail::None, Avail::None, true, false, {"STRING", "COULEUR_ASSOMBRIR('#2ECC71', 50.0)", "#176639", ""}, {}},
        {"COULEUR_OPACITE", "couleur", {{"C", "STRING", "la couleur", false}, {"P", "REAL", "l'opacit\xC3\xA9, 0 (transparent) \xC3\xA0 100 %", false}}, "STRING", "La m\xC3\xAAme couleur, avec cette opacit\xC3\xA9 : '#RRGGBBAA'.",
         "Voile := COULEUR_OPACITE('#000000', 40.0);",
         "/* pas de fonction en C */",
         "/* pas dans la biblioth\xC3\xA8que standard */",
         Avail::None, Avail::None, true, false, {"STRING", "COULEUR_OPACITE('#2ECC71', 50.0)", "#2ECC7180", ""}, {}},
        {"COULEUR_CONTRASTE", "couleur", {{"C", "STRING", "la couleur du fond", false}}, "STRING", "Le noir ou le blanc, celui qui se lit le mieux sur ce fond.",
         "Couleur_Texte := COULEUR_CONTRASTE(Fond);",
         "/* pas de fonction en C : la luminance 0.299 R + 0.587 G + 0.114 B */",
         "/* pas dans la biblioth\xC3\xA8que standard */",
         Avail::None, Avail::None, true, false, {"STRING", "COULEUR_CONTRASTE('#2ECC71')", "#000000", ""}, {}},
        {"COULEUR_ROUGE", "couleur", {{"C", "STRING", "la couleur", false}}, "INT", "Le rouge d'une couleur, 0 \xC3\xA0 255.",
         "R := COULEUR_ROUGE(Fond);",
         "/* pas de fonction en C : strtoul sur deux chiffres hexad\xC3\xA9" "cimaux */",
         "/* pas dans la biblioth\xC3\xA8que standard */",
         Avail::None, Avail::None, true, false, {"INT", "COULEUR_ROUGE('#2ECC71')", "46", ""}, {}},
        {"COULEUR_VERT", "couleur", {{"C", "STRING", "la couleur", false}}, "INT", "Le vert d'une couleur, 0 \xC3\xA0 255.",
         "G := COULEUR_VERT(Fond);",
         "/* pas de fonction en C : strtoul sur deux chiffres hexad\xC3\xA9" "cimaux */",
         "/* pas dans la biblioth\xC3\xA8que standard */",
         Avail::None, Avail::None, true, false, {"INT", "COULEUR_VERT('#2ECC71')", "204", ""}, {}},
        {"COULEUR_BLEU", "couleur", {{"C", "STRING", "la couleur", false}}, "INT", "Le bleu d'une couleur, 0 \xC3\xA0 255.",
         "B := COULEUR_BLEU(Fond);",
         "/* pas de fonction en C : strtoul sur deux chiffres hexad\xC3\xA9" "cimaux */",
         "/* pas dans la biblioth\xC3\xA8que standard */",
         Avail::None, Avail::None, true, false, {"INT", "COULEUR_BLEU('#2ECC71')", "113", ""}, {}},
        {"COULEUR_ALPHA", "couleur", {{"C", "STRING", "la couleur", false}}, "INT", "L'opacit\xC3\xA9 d'une couleur, 0 (transparent) \xC3\xA0 255 ; 255 sans opacit\xC3\xA9 \xC3\xA9" "crite.",
         "A := COULEUR_ALPHA(Fond);",
         "/* pas de fonction en C : strtoul sur deux chiffres hexad\xC3\xA9" "cimaux */",
         "/* pas dans la biblioth\xC3\xA8que standard */",
         Avail::None, Avail::None, true, false, {"INT", "COULEUR_ALPHA('#2ECC7180')", "128", ""}, {}},
        {"RANDOM", "alea", {}, "REAL", "Un r\xC3\xA9" "el au hasard, de 0 (compris) \xC3\xA0 1 (exclu).",
         "IF RANDOM() < 0.1 THEN Panne := TRUE; END_IF   (* une fois sur dix *)",
         "if (rand() / (RAND_MAX + 1.0) < 0.1) Panne = 1;",
         "std::mt19937 gen{std::random_device{}()};\nif (std::uniform_real_distribution<>(0.0, 1.0)(gen) < 0.1) Panne = true;",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "RANDOM()", "0.37454", "RANDOM_SEED(42);"}, {"Dans une expression fx, la valeur change \xC3\xA0 chaque cycle d'affichage : un script la tire plut\xC3\xB4t une fois."}},
        {"RANDOM_INT", "alea", {{"MIN", "DINT", "le plus petit", false}, {"MAX", "DINT", "le plus grand (compris)", false}}, "DINT", "Un entier au hasard, de MIN \xC3\xA0 MAX compris.",
         "De := RANDOM_INT(1, 6);",
         "De = 1 + rand() % 6;",
         "De = std::uniform_int_distribution<int>(1, 6)(gen);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"DINT", "RANDOM_INT(1, 6)", "1", "RANDOM_SEED(42);"}, {}},
        {"RANDOM_REAL", "alea", {{"MIN", "REAL", "le plus petit", false}, {"MAX", "REAL", "la borne haute (exclue)", false}}, "REAL", "Un r\xC3\xA9" "el au hasard, de MIN (compris) \xC3\xA0 MAX (exclu).",
         "Mesure_Simulee := RANDOM_REAL(18.0, 22.0);",
         "Mesure_Simulee = 18.0f + 4.0f * (rand() / (RAND_MAX + 1.0f));",
         "Mesure_Simulee = std::uniform_real_distribution<float>(18.0f, 22.0f)(gen);",
         Avail::Equivalent, Avail::Equivalent, true, false, {"REAL", "RANDOM_REAL(18.0, 22.0)", "19.4982", "RANDOM_SEED(42);"}, {}},
        {"RANDOM_SEED", "alea", {{"N", "DINT", "la graine", false}}, "BOOL", "Fait repartir la suite : la m\xC3\xAAme graine donne les m\xC3\xAAmes nombres (pour rejouer un essai).",
         "RANDOM_SEED(42);",
         "srand(42);",
         "gen.seed(42);",
         Avail::Equivalent, Avail::Equivalent, true, false, {}, {}},
        {"MAINTENANT", "date", {}, "DATE_AND_TIME", "La date et l'heure du poste (en simulation : celles du PC), \xC3\xA0 la milliseconde.",
         "Debut := MAINTENANT();",
         "time_t debut = time(NULL);   /* localtime() pour la date */",
         "auto debut = std::chrono::system_clock::now();",
         Avail::Equivalent, Avail::Equivalent, true, false, {"BOOL", "MAINTENANT() > DT#2020-01-01-00:00:00", "TRUE", ""}, {"L'heure du mur, sans fuseau : DT#2026-10-09-14:30:00 est 14 h 30 l\xC3\xA0 o\xC3\xB9 tourne l'IHM."}},
        {"DT_TO_DATE", "date", {{"IN", "DATE_AND_TIME", "une date et heure", false}}, "DATE", "La date d'une date et heure (\xC3\xA0 minuit).",
         "Jour := DT_TO_DATE(MAINTENANT());",
         "/* pas d'\xC3\xA9quivalent : localtime(), puis tm_year, tm_mon, tm_mday */",
         "auto jour = std::chrono::floor<std::chrono::days>(maintenant);",
         Avail::None, Avail::Equivalent, true, false, {"BOOL", "DT_TO_DATE(DT#2026-10-09-14:30:00) = D#2026-10-09", "TRUE", ""}, {}},
        {"DT_TO_TOD", "date", {{"IN", "DATE_AND_TIME", "une date et heure", false}}, "TIME_OF_DAY", "L'heure du jour d'une date et heure.",
         "Heure := DT_TO_TOD(MAINTENANT());",
         "/* pas d'\xC3\xA9quivalent : localtime(), puis tm_hour, tm_min, tm_sec */",
         "auto heure = maintenant - std::chrono::floor<std::chrono::days>(maintenant);",
         Avail::None, Avail::Equivalent, true, false, {"BOOL", "DT_TO_TOD(DT#2026-10-09-14:30:00) = TOD#14:30:00", "TRUE", ""}, {}},
        {"CONCAT_DATE_TOD", "date", {{"D", "DATE", "la date", false}, {"TOD", "TIME_OF_DAY", "l'heure", false}}, "DATE_AND_TIME", "Une date et une heure du jour assembl\xC3\xA9" "es en une date et heure.",
         "Rendez_vous := CONCAT_DATE_TOD(D#2026-10-09, TOD#14:30:00);",
         "/* pas d'\xC3\xA9quivalent : mktime() sur un struct tm rempli */",
         "auto rdv = jour + heure;   // std::chrono",
         Avail::None, Avail::Equivalent, true, false, {"BOOL", "CONCAT_DATE_TOD(D#2026-10-09, TOD#14:30:00) = DT#2026-10-09-14:30:00", "TRUE", ""}, {}},
    };
    return k;
}

const std::vector<Operator>& operators() {
    static const std::vector<Operator> k = {
        {":=", "Affectation", "Donne une valeur \xC3\xA0 une variable.", "Vitesse := 1500.0;", "Vitesse = 1500.0f;", "Vitesse = 1500.0f;", {}},
        {"+ - * /", "Arithm\xC3\xA9tique", "Les quatre op\xC3\xA9rations ; entre entiers, / est la division enti\xC3\xA8re (7 / 2 = 3).", "Moyenne := (A + B) / 2.0;", "Moyenne = (A + B) / 2.0f;", "Moyenne = (A + B) / 2.0f;", {"INT", "7 / 2", "3", ""}},
        {"MOD", "Reste", "Le reste de la division enti\xC3\xA8re.", "Pair := (Compteur MOD 2) = 0;", "Pair = (Compteur % 2) == 0;", "Pair = (Compteur % 2) == 0;", {"INT", "7 MOD 2", "1", ""}},
        {"**", "Puissance", "La puissance (comme EXPT).", "Carre := X ** 2;", "Carre = powf(X, 2);", "Carre = std::pow(X, 2);", {"REAL", "2.0 ** 3", "8", ""}},
        {"= <>", "\xC3\x89gal, diff\xC3\xA9rent", "Comparer deux valeurs du m\xC3\xAAme genre.", "Arret := Etat = 0;", "Arret = Etat == 0;", "Arret = Etat == 0;", {"BOOL", "Compteur <> 7", "FALSE", ""}},
        {"< <= > >=", "Comparaisons", "Comparer deux nombres, deux dur\xC3\xA9" "es, deux textes.", "Alerte := Pression > 3.5;", "Alerte = Pression > 3.5f;", "Alerte = Pression > 3.5f;", {"BOOL", "Niveau >= 42.5", "TRUE", ""}},
        {"AND OR XOR", "Logique et bits", "Sur des BOOL : et, ou, ou exclusif ; sur des mots : bit \xC3\xA0 bit.", "Pret := Marche AND NOT Defaut;", "Pret = Marche && !Defaut;   /* & | ^ sur des mots */", "Pret = Marche && !Defaut;", {"BOOL", "Marche AND NOT FALSE", "TRUE", ""}},
        {"NOT", "N\xC3\xA9gation", "Le contraire d'un BOOL ; sur un mot, tous ses bits invers\xC3\xA9s.", "Arret := NOT Marche;", "Arret = !Marche;   /* ~Mot pour un mot */", "Arret = !Marche;", {"BOOL", "NOT Marche", "FALSE", ""}},
        {"&", "Et (autre \xC3\xA9" "criture)", "AND, \xC3\xA9" "crit &.", "Pret := Marche & Ok;", "Pret = Marche && Ok;", "Pret = Marche && Ok;", {"BOOL", "Marche & (Compteur = 7)", "TRUE", ""}},
        {"^", "D\xC3\xA9r\xC3\xA9" "f\xC3\xA9rence", "La variable d\xC3\xA9sign\xC3\xA9" "e par une r\xC3\xA9" "f\xC3\xA9rence ou un pointeur.", "r^ := 0.0;", "*r = 0.0f;", "r = 0.0f;   // une r\xC3\xA9" "f\xC3\xA9rence C++", {}},
        {"+= -= *= /=", "Affectation combin\xC3\xA9" "e (op\xC3\xA9rateurs de type)", "Un op\xC3\xA9rateur \xC3\xA9" "crit pour un type IHM (Programmation g\xC3\xA9n\xC3\xA9rale \xE2\x80\xBA Types).", "Total += Mesure;", "Total += Mesure;", "Total += Mesure;", {}},
        {"? :", "Conditionnel", "c ? a : b vaut a si c est vrai, b sinon. Seul le c\xC3\xB4t\xC3\xA9 choisi est lu : x <> 0 ? 100 / x : 0 ne divise jamais par z\xC3\xA9ro. Le plus faible des op\xC3\xA9rateurs ; c ? a : d ? e : f se lit de droite \xC3\xA0 gauche.", "Vitesse := Marche ? 1500.0 : 0.0;", "Vitesse = Marche ? 1500.0f : 0.0f;", "Vitesse = Marche ? 1500.0f : 0.0f;", {"REAL", "Compteur > 5 ? Niveau * 2.0 : 0.0", "85", ""}},
        {"??", "Valeur de secours", "a ?? b vaut a, ou b quand a ne se lit pas : un nom inconnu, une case hors du tableau, une cl\xC3\xA9 absente d'une MAP, une division par z\xC3\xA9ro, NULL. Plus fort que ? :, plus faible que OR.", "Texte := Recettes['B'] ?? 'aucune';", "/* pas d'\xC3\xA9quivalent : tester avant de lire */", "Texte = recettes.count(\"B\") ? recettes[\"B\"] : \"aucune\";", {"INT", "(100 / (Compteur - 7)) ?? -1", "-1", ""}},
        {"IN [ ]", "Dans la liste", "x IN [a, b, c..d] : vrai si x vaut une des valeurs ou tombe dans une des plages (bornes comprises). Des nombres, des textes, des valeurs d'une \xC3\xA9num\xC3\xA9ration (Mode IN [Auto, Manu]).", "Arret := Etat IN [0, 3, 7..9];", "Arret = Etat == 0 || Etat == 3 || (Etat >= 7 && Etat <= 9);", "Arret = Etat == 0 || Etat == 3 || (Etat >= 7 && Etat <= 9);", {"BOOL", "Compteur IN [1, 3, 5..8]", "TRUE", ""}},
        {"ENTRE \xE2\x80\xA6 ET", "Entre deux bornes", "x ENTRE a ET b : vrai si a <= x <= b (bornes comprises). Au rang des comparaisons : Niveau ENTRE 10 ET 90 AND Marche.", "Normal := Pression ENTRE 0.5 ET 3.5;", "Normal = Pression >= 0.5f && Pression <= 3.5f;", "Normal = Pression >= 0.5f && Pression <= 3.5f;", {"BOOL", "Niveau ENTRE 40 ET 50", "TRUE", ""}},
    };
    return k;
}

const std::vector<Instruction>& instructions() {
    static const std::vector<Instruction> k = {
        {"IF", "Si", "IF cond THEN ... ELSIF cond THEN ... ELSE ... END_IF", "IF Pression > 3.5 THEN\n    Alarme := TRUE;\nELSIF Pression < 0.5 THEN\n    Vide := TRUE;\nELSE\n    Alarme := FALSE;\nEND_IF", "if (Pression > 3.5f) {\n    Alarme = 1;\n} else if (Pression < 0.5f) {\n    Vide = 1;\n} else {\n    Alarme = 0;\n}", "if (Pression > 3.5f) {\n    Alarme = true;\n} else if (Pression < 0.5f) {\n    Vide = true;\n} else {\n    Alarme = false;\n}"},
        {"CASE", "Selon", "CASE x OF 1: ... 2, 3: ... 4..9: ... -5..-1: ... ELSE ... END_CASE ; sur un texte : 'Auto': ... ; sur une \xC3\xA9num\xC3\xA9ration : T_MODE#Auto: ...", "CASE Mode OF\n    T_MODE#Auto: Texte := 'Automatique';\n    T_MODE#Manu: Texte := 'Manuel';\nELSE\n    Texte := '?';\nEND_CASE", "switch (Mode) {\n    case MODE_AUTO: strcpy(Texte, \"Automatique\"); break;\n    case MODE_MANU: strcpy(Texte, \"Manuel\"); break;\n    default: strcpy(Texte, \"?\");\n}", "switch (Mode) {\n    case T_MODE::Auto: Texte = \"Automatique\"; break;\n    case T_MODE::Manu: Texte = \"Manuel\"; break;\n    default: Texte = \"?\";\n}"},
        {"FOR", "Pour", "FOR i := d\xC3\xA9" "but TO fin BY pas DO ... END_FOR", "FOR i := 1 TO 5 DO\n    Somme := Somme + Tab[i];\nEND_FOR", "for (i = 1; i <= 5; ++i)\n    Somme += Tab[i];", "for (int i = 1; i <= 5; ++i)\n    Somme += Tab[i];"},
        {"FOR EACH", "Pour chaque", "FOR EACH v IN tableau DO ... ; FOR EACH cle, valeur IN map DO ...", "FOR EACH cle, qte IN Stock DO\n    Total := Total + qte;\nEND_FOR", "/* pas d'\xC3\xA9quivalent : une boucle sur les indices */", "for (auto& [cle, qte] : stock)\n    total += qte;"},
        {"WHILE", "Tant que", "WHILE cond DO ... END_WHILE", "WHILE i < 10 AND Tab[i] <> 0 DO\n    i := i + 1;\nEND_WHILE", "while (i < 10 && Tab[i] != 0)\n    ++i;", "while (i < 10 && Tab[i] != 0)\n    ++i;"},
        {"REPEAT", "R\xC3\xA9p\xC3\xA9ter", "REPEAT ... UNTIL cond END_REPEAT", "REPEAT\n    i := i + 1;\nUNTIL Tab[i] = 0 END_REPEAT", "do {\n    ++i;\n} while (Tab[i] != 0);", "do {\n    ++i;\n} while (Tab[i] != 0);"},
        {"EXIT", "Sortir", "Quitte la boucle en cours.", "FOR i := 1 TO 5 DO\n    IF Tab[i] = 0 THEN EXIT; END_IF\nEND_FOR", "if (Tab[i] == 0) break;", "if (Tab[i] == 0) break;"},
        {"CONTINUE", "Continuer", "Passe au tour suivant de la boucle en cours (FOR, FOR EACH, WHILE, REPEAT).", "FOR i := 1 TO 5 DO\n    IF Tab[i] = 0 THEN CONTINUE; END_IF\n    Compteur := Compteur + 100 / Tab[i];\nEND_FOR", "for (i = 1; i <= 5; ++i) {\n    if (Tab[i] == 0) continue;\n    Compteur += 100 / Tab[i];\n}", "for (int i = 1; i <= 5; ++i) {\n    if (Tab[i] == 0) continue;\n    Compteur += 100 / Tab[i];\n}"},
        {"TRY", "Essayer", "TRY ... CATCH Erreur ... END_TRY : une erreur du bloc (division par z\xC3\xA9ro, nom inconnu, case hors du tableau, ASSERT faux) n'arr\xC3\xAAte plus le script ; le CATCH s'ex\xC3\xA9" "cute, son message dans la variable STRING nomm\xC3\xA9" "e apr\xC3\xA8s CATCH (facultative).", "TRY\n    Compteur := 100 / Compteur;\nCATCH Texte\n    Compteur := 0;\n    IHM_LOG(NIVEAU_LOG#WARNING, Texte);\nEND_TRY", "/* pas d'\xC3\xA9quivalent en C : tester avant */\nif (Compteur != 0) Compteur = 100 / Compteur; else Compteur = 0;", "try {\n    Compteur = 100 / Compteur;   // une division enti\xC3\xA8re par z\xC3\xA9ro ne l\xC3\xA8ve rien en C++ : tester avant\n} catch (const std::exception& e) {\n    Compteur = 0;\n}"},
        {"ASSERT", "V\xC3\xA9rifier", "ASSERT(condition, 'message') : faux, une erreur - le script s'arr\xC3\xAAte, la Console et les Diagnostics disent le message (dans un TRY : son CATCH) ; vrai, rien.", "ASSERT(Niveau ENTRE 0 ET 100, 'niveau hors de 0..100');", "assert(Niveau >= 0.0f && Niveau <= 100.0f);   /* <assert.h> */", "assert(Niveau >= 0.0f && Niveau <= 100.0f);   // <cassert>"},
        {"RETURN", "Retour", "Quitte le script ou la fonction.", "IF NOT Marche THEN RETURN; END_IF", "if (!Marche) return;", "if (!Marche) return;"},
        {"VAR \xE2\x80\xA6 END_VAR", "D\xC3\xA9" "clarations", "VAR, VAR_TEMP, VAR CONSTANT ; dans une fonction aussi VAR_INPUT, VAR_IN_OUT, VAR_OUTPUT.", "VAR\n    Total : REAL;       (* gard\xC3\xA9" "e d'un appel \xC3\xA0 l'autre *)\nEND_VAR\nVAR_TEMP\n    i : INT;\nEND_VAR", "static float Total;   /* gard\xC3\xA9" "e */\nint16_t i;", "static float Total;   // gard\xC3\xA9" "e\nint16_t i;"},
    };
    return k;
}

const std::vector<NativeEnum>& enums() {
    static const std::vector<NativeEnum> k = {
        {"NIVEAU_LOG", "Le niveau d'une ligne de la Console.", "IHM_LOG", 0, {{"TRACE", 0, "Trace : le d\xC3\xA9tail, pas \xC3\xA0 pas", "TRACE"}, {"DEBUG", 1, "D\xC3\xA9" "bogage", "DEBUG"}, {"INFO", 2, "Information", "INFO"}, {"SUCCESS", 3, "Succ\xC3\xA8s", "SUCCESS"}, {"WARNING", 4, "Avertissement", "WARNING"}, {"ERROR", 5, "Erreur", "ERROR"}, {"CRITICAL", 6, "Critique", "CRITICAL"}}, {}},
        {"TRANSITION", "Le passage d'une vue \xC3\xA0 la suivante.", "IHM_NAVIGUER", 1, {{"Instantanee", 0, "Instantan\xC3\xA9" "e", "Instantan\xC3\xA9" "e"}, {"Fondu", 1, "Fondu", "Fondu"}, {"Glissement", 2, "Glissement", "Glissement"}, {"Zoom", 3, "Zoom", "Zoom"}, {"Rotation", 4, "Rotation", "Rotation"}}, {{"NavBar", "transition"}}},
        {"POSITION_POPUP", "La place d'une popup \xC3\xA0 son ouverture.", "IHM_POPUP", 2, {{"Centre", 0, "Au centre de la vue", "centre"}, {"Objet", 1, "Sous l'objet qui l'ouvre", "objet"}, {"HautGauche", 2, "En haut \xC3\xA0 gauche", "haut-gauche"}, {"HautDroite", 3, "En haut \xC3\xA0 droite", "haut-droite"}, {"BasGauche", 4, "En bas \xC3\xA0 gauche", "bas-gauche"}, {"BasDroite", 5, "En bas \xC3\xA0 droite", "bas-droite"}, {"Derniere", 6, "\xC3\x80 sa derni\xC3\xA8re place", "derniere"}}, {}},
        {"THEME_IHM", "Le th\xC3\xA8me de l'IHM (SYS.Theme).", "IHM_THEME", 0, {{"Jour", 0, "Jour : clair", "jour"}, {"Nuit", 1, "Nuit : les couleurs de la conception", "nuit"}}, {}},
        {"SOURCE_EXPORT", "Ce qu'IHM_EXPORTER exporte (et le bouton d'export).", "IHM_EXPORTER", 0, {{"Alarmes", 0, "Les alarmes", "alarmes"}, {"Historique", 1, "L'historique des alarmes", "historique"}, {"Evenements", 2, "Les \xC3\xA9v\xC3\xA9nements", "\xC3\xA9v\xC3\xA9nements"}, {"Systeme", 3, "Le journal syst\xC3\xA8me", "syst\xC3\xA8me"}, {"Mesures", 4, "Les mesures archiv\xC3\xA9" "es", "mesures"}, {"Audit", 5, "Le journal d'audit", "audit"}}, {{"ExportButton", "exportSource"}}},
        {"ONGLET_CONNEXION", "L'onglet du menu de connexion.", "IHM_MENU_CONNEXION", 0, {{"Comptes", 0, "Comptes", "Comptes"}, {"Acces", 1, "Acc\xC3\xA8s", "Acc\xC3\xA8s"}, {"Journal", 2, "Journal", "Journal"}, {"MonCompte", 3, "Mon compte", "Mon compte"}, {"Connexion", 4, "Connexion", "Connexion"}}, {{"LoginMenuButton", "tab"}}},
        {"PRIORITE_ALARME", "La priorit\xC3\xA9 d'une alarme : 1 la plus forte.", "", -1, {{"Critique", 1, "Critique", "1"}, {"Haute", 2, "Haute", "2"}, {"Moyenne", 3, "Moyenne", "3"}, {"Basse", 4, "Basse", "4"}}, {}},
        {"POLICE", "La police d'un texte.", "", -1, {{"Sans", 0, "Sans : la police de l'interface", "Sans"}, {"Mono", 1, "Mono : \xC3\xA0 chasse fixe", "Mono"}}, {{"*", "font"}}},
        {"ALIGNEMENT", "L'alignement d'un texte, la place d'un titre.", "", -1, {{"Gauche", 0, "\xC3\x80 gauche", "gauche"}, {"Centre", 1, "Au centre", "centre"}, {"Droite", 2, "\xC3\x80 droite", "droite"}}, {{"*", "align"}, {"*", "titleAlign"}}},
        {"FORME_VOYANT", "La forme d'un voyant.", "", -1, {{"Rond", 0, "Rond", "rond"}, {"Carre", 1, "Carr\xC3\xA9", "carr\xC3\xA9"}}, {{"*", "shape"}}},
        {"ORIENTATION", "Le sens d'une barre, d'un curseur, d'une liste de boutons.", "", -1, {{"Horizontale", 0, "Horizontale", "horizontale"}, {"Verticale", 1, "Verticale", "verticale"}}, {{"*", "orientation"}}},
        {"ETIREMENT", "Comment une image remplit son cadre.", "", -1, {{"Ajuster", 0, "Ajuster : enti\xC3\xA8re, ses proportions gard\xC3\xA9" "es", "ajuster"}, {"Etirer", 1, "\xC3\x89tirer : tout le cadre", "\xC3\xA9tirer"}, {"Aucun", 2, "Aucun : sa taille", "aucun"}}, {{"*", "stretch"}}},
        {"RECOLORATION", "Ce qu'une image recolori\xC3\xA9" "e change.", "", -1, {{"Tout", 0, "Tout", "tout"}, {"Remplissages", 1, "Les remplissages", "remplissages"}, {"Contours", 2, "Les contours", "contours"}, {"UneCouleur", 3, "Une couleur", "une couleur"}}, {{"*", "recolorMode"}}},
        {"SENS_DEFILEMENT", "Le sens d'un texte d\xC3\xA9" "filant.", "", -1, {{"Gauche", 0, "Vers la gauche", "gauche"}, {"Droite", 1, "Vers la droite", "droite"}}, {{"Marquee", "direction"}}},
        {"CORRECTION_QR", "Le niveau de correction d'erreurs d'un code QR.", "", -1, {{"L", 0, "L : 7 %", "L"}, {"M", 1, "M : 15 %", "M"}, {"Q", 2, "Q : 25 %", "Q"}, {"H", 3, "H : 30 %", "H"}}, {{"*", "ecLevel"}}},
        {"TYPE_SAISIE", "Ce qu'un champ de saisie accepte.", "", -1, {{"Numerique", 0, "Un nombre", "num\xC3\xA9rique"}, {"Texte", 1, "Un texte", "texte"}, {"MotDePasse", 2, "Un mot de passe (masqu\xC3\xA9)", "mot de passe"}}, {{"InputField", "mode"}}},
        {"CLAVIER_VIRTUEL", "Le clavier qui s'ouvre sur un champ.", "", -1, {{"Aucun", 0, "Aucun", "aucun"}, {"Numerique", 1, "Num\xC3\xA9rique", "num\xC3\xA9rique"}, {"Complet", 2, "Complet", "complet"}}, {{"*", "keyboard"}}},
        {"CONFIRMATION", "Comment une commande sensible se confirme.", "", -1, {{"Aucune", 0, "Aucune", "aucune"}, {"SecondClic", 1, "Un second clic", "second clic"}, {"Maintien", 2, "Un appui maintenu", "maintien"}}, {{"*", "confirmMode"}}},
        {"OPERATION_BOUTON", "Ce que fait un bouton lumineux sur sa variable.", "", -1, {{"Basculer", 0, "Basculer", "basculer"}, {"Impulsion", 1, "Une impulsion", "impulsion"}, {"MettreA1", 2, "Mettre \xC3\xA0 1", "mettre \xC3\xA0 1"}, {"MettreA0", 3, "Mettre \xC3\xA0 0", "mettre \xC3\xA0 0"}, {"Aucune", 4, "Aucune", "aucune"}}, {{"*", "operation"}}},
        {"STYLE_SELECTEUR", "La forme d'un s\xC3\xA9lecteur.", "", -1, {{"Rotatif", 0, "Rotatif", "rotatif"}, {"Boutons", 1, "Des boutons", "boutons"}}, {{"Selector", "style"}}},
        {"CHAMPS_DATE", "Ce qu'un s\xC3\xA9lecteur de date et heure montre.", "", -1, {{"DateEtHeure", 0, "La date et l'heure", "date et heure"}, {"Date", 1, "La date", "date"}, {"Heure", 2, "L'heure", "heure"}}, {{"*", "fields"}}},
        {"RESOLUTION_PLANNING", "Le pas d'un programmateur horaire.", "", -1, {{"Heure", 0, "1 h", "1 h"}, {"DemiHeure", 1, "30 min", "30 min"}, {"QuartDHeure", 2, "15 min", "15 min"}}, {{"*", "resolution"}}},
        {"NIVEAU_ACCES", "Le niveau d'acc\xC3\xA8s d'un objet (et celui d'un utilisateur, IHM_NIVEAU()).", "", -1, {{"ToutLeMonde", 0, "Tout le monde", "0"}, {"Operateur", 1, "Op\xC3\xA9rateur", "1"}, {"Maintenance", 2, "Maintenance", "2"}, {"Superviseur", 3, "Superviseur", "3"}, {"Administrateur", 4, "Administrateur", "4"}}, {{"*", "access"}}},
        {"SIGNATURE", "La signature \xC3\xA9lectronique d'une commande.", "", -1, {{"Aucune", 0, "Aucune", "aucune"}, {"Simple", 1, "Simple : l'utilisateur", "simple"}, {"Double", 2, "Double : l'utilisateur et un second", "double"}}, {{"*", "signature"}}},
        {"STYLE_HORLOGE", "La forme d'une horloge.", "", -1, {{"Analogique", 0, "Analogique : des aiguilles", "analogique"}, {"Numerique", 1, "Num\xC3\xA9rique", "num\xC3\xA9rique"}}, {{"*", "clockStyle"}}},
        {"FORMAT_DUREE", "L'\xC3\xA9" "criture d'un compteur horaire.", "", -1, {{"HMMSS", 0, "h:mm:ss", "h:mm:ss"}, {"Heures", 1, "En heures", "heures"}, {"Jours", 2, "En jours", "jours"}}, {{"*", "durationFormat"}}},
        {"MODE_COURBE", "D'o\xC3\xB9 une courbe tire ses points.", "", -1, {{"TempsReel", 0, "Temps r\xC3\xA9" "el : \xC3\xA0 chaque cycle", "temps r\xC3\xA9" "el"}, {"Historique", 1, "Historique : les mesures archiv\xC3\xA9" "es", "historique"}}, {{"Trend", "mode"}}},
        {"ECHELLE", "L'axe Y d'une courbe ou d'un graphique.", "", -1, {{"Fixe", 0, "Fixe : min et max donn\xC3\xA9s", "fixe"}, {"Auto", 1, "Auto : suit les valeurs", "auto"}}, {{"*", "scale"}}},
        {"INTERPOLATION", "Comment une courbe relie ses points.", "", -1, {{"Lineaire", 0, "Lin\xC3\xA9" "aire", "lin\xC3\xA9" "aire"}, {"Escalier", 1, "En escalier", "escalier"}, {"Points", 2, "Des points seuls", "points"}}, {{"*", "interpolation"}}},
        {"ETIQUETTES_PARTS", "Ce qu'un camembert \xC3\xA9" "crit sur ses parts.", "", -1, {{"Pourcentage", 0, "Le pourcentage", "pourcentage"}, {"Valeur", 1, "La valeur", "valeur"}, {"LesDeux", 2, "Les deux", "les deux"}, {"Aucune", 3, "Rien", "aucune"}}, {{"*", "labelMode"}}},
        {"SOURCE_HISTORIQUE", "Ce qu'un historique montre.", "", -1, {{"Alarmes", 0, "Les alarmes actives", "alarmes"}, {"Acquittees", 1, "Les alarmes acquitt\xC3\xA9" "es", "acquitt\xC3\xA9" "es"}, {"Historique", 2, "Les alarmes termin\xC3\xA9" "es", "historique"}, {"Evenements", 3, "Les \xC3\xA9v\xC3\xA9nements", "\xC3\xA9v\xC3\xA9nements"}, {"Systeme", 4, "Le journal de l'IHM", "syst\xC3\xA8me"}, {"MisesDeCote", 5, "Les alarmes mises de c\xC3\xB4t\xC3\xA9", "mises de c\xC3\xB4t\xC3\xA9"}, {"Audit", 6, "Le journal d'audit", "audit"}}, {{"History", "source"}}},
        {"ALARME_MONTREE", "L'alarme qu'un bandeau montre.", "", -1, {{"PlusGrave", 0, "La plus grave", "la plus grave"}, {"PlusRecente", 1, "La plus r\xC3\xA9" "cente", "la plus r\xC3\xA9" "cente"}, {"Defilement", 2, "Toutes, en d\xC3\xA9" "filement", "d\xC3\xA9" "filement"}}, {{"AlarmBanner", "show"}}},
        {"ALARMES_COMPTEES", "Ce qu'un compteur d'alarmes compte.", "", -1, {{"AAcquitter", 0, "\xC3\x80 acquitter", "\xC3\xA0 acquitter"}, {"Actives", 1, "Actives", "actives"}, {"EnCours", 2, "En cours", "en cours"}, {"MisesDeCote", 3, "Mises de c\xC3\xB4t\xC3\xA9", "mises de c\xC3\xB4t\xC3\xA9"}}, {{"AlarmCounter", "count"}}},
        {"PERIODE_STATS", "La p\xC3\xA9riode des statistiques d'alarmes.", "", -1, {{"DepuisLancement", 0, "Depuis le lancement", "depuis le lancement"}, {"Jour", 1, "24 h", "24 h"}, {"Semaine", 2, "7 jours", "7 jours"}, {"Tout", 3, "Tout l'historique", "tout l'historique"}}, {{"AlarmStats", "range"}}},
        {"CLASSEMENT", "Le classement des statistiques d'alarmes.", "", -1, {{"Nombre", 0, "Par nombre", "nombre"}, {"Duree", 1, "Par dur\xC3\xA9" "e", "dur\xC3\xA9" "e"}}, {{"AlarmStats", "sort"}}},
        {"FORMAT_FICHIER", "Le format d'un export.", "", -1, {{"CSV", 0, "CSV", "CSV"}, {"Excel", 1, "Excel (XLSX)", "Excel"}, {"PDF", 2, "PDF", "PDF"}}, {{"*", "fileFormat"}}},
        {"PLACE_LIBELLE", "La place du libell\xC3\xA9 d'un symbole de synoptique.", "", -1, {{"Dessous", 0, "Dessous", "dessous"}, {"Dessus", 1, "Dessus", "dessus"}, {"Aucun", 2, "Cach\xC3\xA9", "aucun"}}, {{"*", "labelPosition"}}},
        {"COMMANDE_VANNE", "La commande dessin\xC3\xA9" "e d'une vanne.", "", -1, {{"Manuelle", 0, "Manuelle", "manuelle"}, {"Motorisee", 1, "Motoris\xC3\xA9" "e", "motoris\xC3\xA9" "e"}, {"Pneumatique", 2, "Pneumatique", "pneumatique"}, {"Reglante", 3, "R\xC3\xA9glante", "r\xC3\xA9glante"}}, {{"*", "valveType"}}},
        {"FORME_TUBE", "La forme d'une tuyauterie.", "", -1, {{"Droit", 0, "Droit", "droit"}, {"Coude", 1, "Coude", "coude"}, {"Te", 2, "T\xC3\xA9", "t\xC3\xA9"}, {"Croix", 3, "Croix", "croix"}}, {{"*", "pipeShape"}}},
        {"MONTAGE_ISA", "Le montage d'un instrument ISA.", "", -1, {{"Terrain", 0, "Terrain", "terrain"}, {"Tableau", 1, "Tableau", "tableau"}, {"TableauArriere", 2, "Tableau arri\xC3\xA8re", "tableau arri\xC3\xA8re"}}, {{"*", "mounting"}}},
        {"VANNE3_VARIANTE", "La variante d'une vanne 3 voies.", "", -1, {{"Melangeuse", 0, "M\xC3\xA9langeuse", "m\xC3\xA9langeuse"}, {"Repartitrice", 1, "R\xC3\xA9partitrice", "r\xC3\xA9partitrice"}}, {{"*", "valve3Function"}}},
        {"VANNE3_BOISSEAU", "Le boisseau d'une vanne 3 voies.", "", -1, {{"T", 0, "En T", "T"}, {"L", 1, "En L", "L"}}, {{"*", "valve3Bore"}}},
        {"VANNE3_COMMANDE", "Comment se commande la position d'une vanne 3 voies.", "", -1, {{"Entier", 0, "Un entier", "entier"}, {"DeuxBooleens", 1, "Deux bool\xC3\xA9" "ens", "deux bool\xC3\xA9" "ens"}}, {{"*", "positionMode"}}},
        {"STYLE_NAVIGATION", "La forme d'une barre de navigation.", "", -1, {{"Onglets", 0, "Des onglets", "onglets"}, {"Boutons", 1, "Des boutons", "boutons"}, {"Liens", 2, "Des liens", "liens"}}, {{"*", "tabStyle"}}},
        {"CHEMIN_ARIANE", "Ce qu'un fil d'Ariane suit.", "", -1, {{"Hierarchie", 0, "La hi\xC3\xA9rarchie des vues", "hi\xC3\xA9rarchie"}, {"Historique", 1, "L'historique de navigation", "historique"}}, {{"*", "trail"}}},
        {"PLACE_ONGLETS", "La place des onglets d'un conteneur.", "", -1, {{"Haut", 0, "En haut", "haut"}, {"Bas", 1, "En bas", "bas"}}, {{"*", "tabPosition"}}},
        {"STYLE_TITRE", "Le titre d'un cadre.", "", -1, {{"Bordure", 0, "Dans la bordure", "bordure"}, {"Bandeau", 1, "Un bandeau", "bandeau"}}, {{"*", "titleStyle"}}},
        {"DEFILEMENT", "Le sens de d\xC3\xA9" "filement d'un panneau.", "", -1, {{"Verticale", 0, "Vertical", "verticale"}, {"Horizontale", 1, "Horizontal", "horizontale"}, {"LesDeux", 2, "Les deux", "les deux"}}, {{"*", "scrollDirection"}}},
        {"STYLE_LANGUE", "La forme d'un s\xC3\xA9lecteur de langue.", "", -1, {{"Boutons", 0, "Des boutons", "boutons"}, {"Bascule", 1, "Une bascule", "bascule"}}, {{"*", "languageStyle"}}},
        {"LIBELLE_LANGUE", "Ce qu'un s\xC3\xA9lecteur de langue \xC3\xA9" "crit.", "", -1, {{"CodeEtNom", 0, "Le code et le nom", "code et nom"}, {"Code", 1, "Le code", "code"}, {"Nom", 2, "Le nom", "nom"}}, {{"*", "languageLabel"}}},
        {"ONGLET_PARAMETRES", "L'onglet ouvert des param\xC3\xA8tres syst\xC3\xA8me.", "", -1, {{"Reglages", 0, "R\xC3\xA9glages", "R\xC3\xA9glages"}, {"Diagnostic", 1, "Diagnostic", "Diagnostic"}, {"Simulation", 2, "Simulation", "Simulation"}}, {{"SystemButton", "tab"}}},
        {"LECTURE_GIF", "Comment un GIF anim\xC3\xA9 se joue.", "", -1, {{"EnBoucle", 0, "En boucle", "en boucle"}, {"UneFois", 1, "Une fois", "une fois"}, {"NFois", 2, "N fois", "N fois"}}, {{"AnimatedGif", "play"}}},
        {"DEPART_GIF", "Quand un GIF anim\xC3\xA9 d\xC3\xA9marre.", "", -1, {{"AAffichage", 0, "\xC3\x80 l'affichage", "\xC3\xA0 l'affichage"}, {"SurAction", 1, "Sur action", "sur action"}, {"SurCondition", 2, "Sur condition", "sur condition"}}, {{"AnimatedGif", "start"}}},
        {"FIN_GIF", "Ce qu'un GIF anim\xC3\xA9 montre \xC3\xA0 la fin.", "", -1, {{"DerniereImage", 0, "La derni\xC3\xA8re image", "derni\xC3\xA8re image"}, {"PremiereImage", 1, "La premi\xC3\xA8re image", "premi\xC3\xA8re image"}, {"Cache", 2, "Il se cache", "cach\xC3\xA9"}}, {{"AnimatedGif", "end"}}},
        {"JOUR", "Le jour de la semaine, comme SYS.WeekDay (1 lundi ... 7 dimanche).", "", -1, {{"Lundi", 1, "Lundi", "1"}, {"Mardi", 2, "Mardi", "2"}, {"Mercredi", 3, "Mercredi", "3"}, {"Jeudi", 4, "Jeudi", "4"}, {"Vendredi", 5, "Vendredi", "5"}, {"Samedi", 6, "Samedi", "6"}, {"Dimanche", 7, "Dimanche", "7"}}, {}},
        {"MOIS", "Le mois, comme SYS.Month (1 janvier ... 12 d\xC3\xA9" "cembre).", "", -1, {{"Janvier", 1, "Janvier", "1"}, {"Fevrier", 2, "F\xC3\xA9vrier", "2"}, {"Mars", 3, "Mars", "3"}, {"Avril", 4, "Avril", "4"}, {"Mai", 5, "Mai", "5"}, {"Juin", 6, "Juin", "6"}, {"Juillet", 7, "Juillet", "7"}, {"Aout", 8, "Ao\xC3\xBBt", "8"}, {"Septembre", 9, "Septembre", "9"}, {"Octobre", 10, "Octobre", "10"}, {"Novembre", 11, "Novembre", "11"}, {"Decembre", 12, "D\xC3\xA9" "cembre", "12"}}, {}},
        {"QUALITE", "La qualit\xC3\xA9 d'une valeur lue sur un \xC3\xA9quipement.", "", -1, {{"Bonne", 0, "Bonne", "0"}, {"Ancienne", 1, "Ancienne : la derni\xC3\xA8re lue, trop vieille", "1"}, {"Mauvaise", 2, "Mauvaise : illisible", "2"}}, {}},
        {"ETAT_MOTEUR", "L'\xC3\xA9tat d'un moteur, d'une pompe, d'un convoyeur (\xC3\xA0 donner \xC3\xA0 ses variables).", "", -1, {{"Arret", 0, "\xC3\x80 l'arr\xC3\xAAt", "0"}, {"Marche", 1, "En marche", "1"}, {"Defaut", 2, "En d\xC3\xA9" "faut", "2"}, {"Maintenance", 3, "En maintenance", "3"}}, {}},
        {"MODE_MARCHE", "Le mode de marche d'un \xC3\xA9quipement (\xC3\xA0 donner \xC3\xA0 ses variables).", "", -1, {{"Auto", 0, "Automatique", "0"}, {"Manuel", 1, "Manuel", "1"}, {"Local", 2, "Local", "2"}, {"Distant", 3, "Distant", "3"}}, {}},
    };
    return k;
}

const std::vector<Generic>& generics() {
    static const std::vector<Generic> k = {
        {"ANY", "tous les types", "Un param\xC3\xA8tre de popup ou de symbole qui accepte toute valeur ; LIMIT, SEL, MIN, MAX rendent le type de leur entr\xC3\xA9" "e."},
        {"ANY_ELEMENTARY", "les 22 types de base", "Une valeur simple, ni tableau, ni structure, ni MAP."},
        {"ANY_NUM", "SINT, INT, DINT, LINT, USINT, UINT, UDINT, ULINT, REAL, LREAL", "Un nombre : ABS, les comparaisons, + - * / **."},
        {"ANY_INT", "SINT, INT, DINT, LINT, USINT, UINT, UDINT, ULINT", "Un entier : MOD, les bornes d'un FOR, un indice de tableau, RANDOM_INT."},
        {"ANY_REAL", "REAL, LREAL", "Un r\xC3\xA9" "el : SQRT, LN, LOG, EXP, SIN, COS, TAN..."},
        {"ANY_BIT", "BOOL, BYTE, WORD, DWORD, LWORD", "Des bits : AND, OR, XOR, NOT bit \xC3\xA0 bit, SHL, SHR, ROL, ROR."},
        {"ANY_STRING", "STRING, WSTRING, CHAR", "Un texte : LEN, LEFT, RIGHT, MID, CONCAT, FIND, TO_UPPER..."},
        {"ANY_DATE", "DATE, TIME_OF_DAY, DATE_AND_TIME", "Une date ou une heure : DT_TO_DATE, DT_TO_TOD, CONCAT_DATE_TOD, les comparaisons."},
    };
    return k;
}

const std::vector<TypeExtra>& typeExtras() {
    static const std::vector<TypeExtra> k = {
        {"BOOL", "bool", "BOOL (bool)", "FALSE", "1 bit (16 BOOL \xC3\xA0 la suite par mot), sinon 1 mot", {"TRUE", "FALSE", "BOOL#1"}, {}},
        {"SINT", "int8_t", "SINT (int8_t)", "0", "\xE2\x80\x94", {"-12", "SINT#-12"}, {"Pas une variable IHM (il n'a pas de place Modbus) : une locale, un param\xC3\xA8tre, un op\xC3\xA9rande."}},
        {"INT", "int16_t", "INT (int16_t)", "0", "1 mot (%MW)", {"42", "-7", "INT#42", "16#FF", "2#1010", "8#17"}, {}},
        {"DINT", "int32_t", "DINT (int32_t)", "0", "2 mots (%MD)", {"100000", "DINT#-5", "16#7FFF_FFFF"}, {}},
        {"LINT", "int64_t", "LINT (int64_t)", "0", "\xE2\x80\x94", {"LINT#5"}, {"L'IHM le calcule sur 32 bits, comme un DINT : au-del\xC3\xA0, la valeur est fausse.", "Pas une variable IHM : une locale, un param\xC3\xA8tre, un op\xC3\xA9rande."}},
        {"USINT", "uint8_t", "USINT (uint8_t)", "0", "\xE2\x80\x94", {"200", "USINT#200"}, {"Pas une variable IHM (il n'a pas de place Modbus) : une locale, un param\xC3\xA8tre, un op\xC3\xA9rande."}},
        {"UINT", "uint16_t", "UINT (uint16_t)", "0", "1 mot (%MW)", {"65535", "UINT#7"}, {}},
        {"UDINT", "uint32_t", "UDINT (uint32_t)", "0", "2 mots (%MD)", {"4000000000", "UDINT#7"}, {}},
        {"ULINT", "uint64_t", "ULINT (uint64_t)", "0", "\xE2\x80\x94", {"ULINT#5"}, {"L'IHM le calcule sur 32 bits, comme un UDINT : au-del\xC3\xA0, la valeur est fausse.", "Pas une variable IHM : une locale, un param\xC3\xA8tre, un op\xC3\xA9rande."}},
        {"BYTE", "uint8_t", "BYTE (uint8_t)", "16#00", "\xE2\x80\x94", {"16#FF", "BYTE#65"}, {"Pas une variable IHM (il n'a pas de place Modbus) : une locale, un param\xC3\xA8tre, un op\xC3\xA9rande."}},
        {"WORD", "uint16_t", "WORD (uint16_t)", "16#0000", "1 mot (%MW)", {"16#00F0", "2#0000_1111_0000_0000"}, {}},
        {"DWORD", "uint32_t", "DWORD (uint32_t)", "16#0000_0000", "2 mots (%MD)", {"16#DEAD_BEEF"}, {}},
        {"LWORD", "uint64_t", "LWORD (uint64_t)", "16#0", "\xE2\x80\x94", {"16#FF"}, {"L'IHM le calcule sur 32 bits, comme un DWORD. Un op\xC3\xA9rande d'op\xC3\xA9rateur, un param\xC3\xA8tre."}},
        {"REAL", "float", "REAL (float)", "0.0", "2 mots (%MF)", {"3.14", "-0.5", "1.5E3", "REAL#1"}, {"Environ 7 chiffres significatifs sur 32 bits ; l'IHM calcule en double pr\xC3\xA9" "cision, puis \xC3\xA9" "crit un REAL de 32 bits.", "Le plus petit r\xC3\xA9" "el normalis\xC3\xA9 : 1.175494E-38."}},
        {"LREAL", "double", "LREAL (double)", "0.0", "2 mots (%MF)", {"3.141592653589793", "LREAL#1.5"}, {"Environ 15 chiffres significatifs. Sur Modbus, l'IHM l'\xC3\xA9" "crit en 2 mots, comme un REAL."}},
        {"STRING", "char[33]", "STRING (std::string)", "''", "16 mots (32 caract\xC3\xA8res)", {"'texte'", "''", "'l$'armoire'", "'ligne 1$Nligne 2'", "'5 $$'"}, {"Sur Modbus, une STRING prend 16 mots : 32 caract\xC3\xA8res, deux par mot.", "\xC3\x89" "chappements : $' (apostrophe), $N (ligne), $T (tabulation), $$ (dollar)."}},
        {"TIME", "uint32_t   /* des ms */", "TIME (std::chrono::milliseconds)", "T#0ms", "2 mots (%MD)", {"T#5s", "T#1m30s", "T#250ms", "TIME#1h", "T#1d2h"}, {"Une dur\xC3\xA9" "e en millisecondes sur 32 bits. Pas de dur\xC3\xA9" "e n\xC3\xA9gative : T#-5s est refus\xC3\xA9.", "L'affichage du moteur compte en millisecondes (T#5000ms) ; {d:t} l'\xC3\xA9" "crit lisiblement (2 min 05 s)."}},
        {"CHAR", "char", "CHAR (char)", "''", "\xE2\x80\x94", {"'A'", "'$N'"}, {"Un texte d'un caract\xC3\xA8re pour l'IHM : une STRING le re\xC3\xA7oit ; vers CHAR, le premier caract\xC3\xA8re.", "Pas une variable IHM (pas de place Modbus) : une locale, un param\xC3\xA8tre, un op\xC3\xA9rande."}},
        {"WSTRING", "wchar_t[33]", "WSTRING (std::wstring)", "''", "\xE2\x80\x94", {"'texte'", "'\xC3\xA9t\xC3\xA9'"}, {"L'IHM \xC3\xA9" "crit ses textes en UTF-8 : WSTRING et STRING s'\xC3\xA9" "changent sans conversion.", "Pas une variable IHM (pas de place Modbus) : une locale, un param\xC3\xA8tre, un op\xC3\xA9rande."}},
        {"DATE", "time_t   /* minuit */", "DATE (std::chrono::sys_days)", "D#1970-01-01", "\xE2\x80\x94", {"D#2026-10-09", "DATE#2026-01-01"}, {"DATE - DATE est une dur\xC3\xA9" "e (TIME) ; DT_TO_DATE(dt) en tire la date.", "Pas une variable IHM (pas de place Modbus) : une locale, un param\xC3\xA8tre, un op\xC3\xA9rande."}},
        {"TIME_OF_DAY", "uint32_t   /* ms depuis minuit */", "TIME_OF_DAY (std::chrono::milliseconds)", "TOD#00:00:00", "\xE2\x80\x94", {"TOD#14:30:00", "TOD#06:00", "TIME_OF_DAY#23:59:59.5"}, {"Son nom court : TOD. TOD + TIME tourne sur 24 h (TOD#23:00:00 + T#2h = TOD#01:00:00) ; TOD - TOD est une dur\xC3\xA9" "e.", "Pas une variable IHM (pas de place Modbus) : une locale, un param\xC3\xA8tre, un op\xC3\xA9rande."}},
        {"DATE_AND_TIME", "time_t", "DATE_AND_TIME (std::chrono::system_clock::time_point)", "DT#1970-01-01-00:00:00", "\xE2\x80\x94", {"DT#2026-10-09-14:30:00", "DATE_AND_TIME#2026-01-01-00:00:00"}, {"Son nom court : DT. DT + TIME, DT - TIME, DT - DT (une dur\xC3\xA9" "e) ; MAINTENANT() la donne.", "Pas une variable IHM (pas de place Modbus) : une locale, un param\xC3\xA8tre, un op\xC3\xA9rande."}},
    };
    return k;
}

const std::vector<Constructed>& constructed() {
    static const std::vector<Constructed> k = {
        {"ARRAY", "ARRAY[1..10] OF REAL", "Un tableau, \xC3\xA0 une dimension ou plus : ARRAY[0..3, 0..9] OF REAL. Ses propri\xC3\xA9t\xC3\xA9s : Length, Rows, Columns.", "VAR Mesures : ARRAY[1..10] OF REAL; END_VAR", "float tab[10];", "std::array<REAL, 10> tab;"},
        {"MAP", "MAP[STRING] OF REAL", "Une table associative : une cl\xC3\xA9 (STRING ou entier) donne une valeur. Se parcourt avec FOR EACH.", "VAR Stock : MAP[STRING] OF REAL; END_VAR", "/* pas de MAP en C */", "std::map<std::string, REAL> m;"},
        {"REF_TO", "REF_TO REAL", "Une r\xC3\xA9" "f\xC3\xA9rence : r^ lit et \xC3\xA9" "crit la variable d\xC3\xA9sign\xC3\xA9" "e par REF(x).", "VAR r : REF_TO REAL; END_VAR", "float* r = &x;", "REAL& r = x;"},
        {"POINTER TO", "POINTER TO INT", "Un pointeur : p^ lit et \xC3\xA9" "crit la variable d\xC3\xA9sign\xC3\xA9" "e par ADR(x).", "VAR p : POINTER TO INT; END_VAR", "int16_t* p = &x;", "INT* p = &x;"},
        {"MAP_ITERATOR", "MAP_ITERATOR", "Un it\xC3\xA9rateur sur une MAP : MAP_BEGIN, MAP_NEXT, MAP_END ; it.Key, it.Value.", "VAR it : MAP_ITERATOR; END_VAR", "/* pas de MAP en C */", "auto it = m.begin();"},
        {"STRING[n]", "STRING[20]", "Une cha\xC3\xAEne born\xC3\xA9" "e \xC3\xA0 n caract\xC3\xA8res (STRING seule : sans borne dans l'IHM, 32 caract\xC3\xA8res sur Modbus).", "VAR Nom : STRING[20]; END_VAR", "char texte[21];", "std::string texte;   // borne \xC3\xA0 v\xC3\xA9rifier"},
    };
    return k;
}

} // namespace hmi::natives
