# XpgAnalyzer - vue IHM (format 19)
vue id=382 nom="Vue_Ligne" description="Compteurs de production, réglages, recette, exports" largeur=1280 hauteur=800 fond="#20242B" calque_actif=383
grille visible=1 pas=10 magnetisme_grille=1 magnetisme_objets=1 magnetisme_guides=1
calque id=383 nom="Calque 1" visible=1 verrou=0
objet id=384 type=ProductionCounter nom="Compteurs_Ligne" calque=383 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="20"
prop cle=w valeur="620"
prop cle=h valeur="250"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Ligne 1"
prop cle=fontSize valeur="14"
prop cle=textColor valeur="#9AA6B8"
prop cle=fill valeur="#1B2028"
prop cle=stroke valeur="#3A4556"
prop cle=good valeur="Pieces_Bonnes"
prop cle=bad valeur="Rebuts_Ligne"
prop cle=running valeur="Pompe_Marche"
prop cle=idealRate valeur="10000"
prop cle=target valeur="300"
prop cle=shifts valeur="06:00;14:00;22:00"
prop cle=rateWindow valeur="30"
prop cle=low valeur="30"
prop cle=high valeur="60"
prop cle=showReset valeur="TRUE"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=385 type=VariableTable nom="Reglages_Ligne" calque=383 parent=0 verrou=0 cache=0
prop cle=x valeur="660"
prop cle=y valeur="20"
prop cle=w valeur="600"
prop cle=h valeur="250"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=variables valeur="Consigne_Pression; Vitesse_Pompe; Mode_Pompe; Gaz_Choisi; Pression_Ligne * 1.0"
prop cle=names valeur="Consigne de pression; Vitesse de la pompe; Mode (0 manuel, 1 arrêt, 2 auto); Gaz de la ligne; Pression mesurée"
prop cle=units valeur="bar; %; ; ; bar"
prop cle=writable valeur="TRUE"
prop cle=format valeur="0.0"
prop cle=keyboard valeur="numérique"
prop cle=fontSize valeur="13"
prop cle=textColor valeur="#DDE3EA"
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=386 type=RecipeEditor nom="Editeur_Recette" calque=383 parent=0 verrou=0 cache=0
prop cle=x valeur="20"
prop cle=y valeur="290"
prop cle=w valeur="740"
prop cle=h valeur="290"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=recipe valeur="Reglages_Armoires"
prop cle=buttons valeur="Enregistrer;Appliquer;Lire;Annuler;Nouveau"
prop cle=compare valeur="TRUE"
prop cle=keyboard valeur="numérique"
prop cle=fontSize valeur="13"
prop cle=textColor valeur="#DDE3EA"
prop cle=fill valeur="#262C36"
prop cle=stroke valeur="#3A4556"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=387 type=ExportButton nom="Export_Alarmes" calque=383 parent=0 verrou=0 cache=0
prop cle=x valeur="790"
prop cle=y valeur="300"
prop cle=w valeur="230"
prop cle=h valeur="48"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Alarmes (CSV)"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=exportSource valeur="alarmes"
prop cle=fileFormat valeur="CSV"
prop cle=fileName valeur="alarmes_{SYS.Date}"
prop cle=icon valeur="TRUE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=388 type=ExportButton nom="Export_Historique" calque=383 parent=0 verrou=0 cache=0
prop cle=x valeur="1030"
prop cle=y valeur="300"
prop cle=w valeur="230"
prop cle=h valeur="48"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Historique (Excel)"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=exportSource valeur="historique"
prop cle=fileFormat valeur="Excel"
prop cle=fileName valeur="historique_alarmes_{SYS.Date}"
prop cle=icon valeur="TRUE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=389 type=ExportButton nom="Export_TRS" calque=383 parent=0 verrou=0 cache=0
prop cle=x valeur="790"
prop cle=y valeur="364"
prop cle=w valeur="230"
prop cle=h valeur="48"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="TRS du poste (PDF)"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=exportSource valeur="objet:Compteurs_Ligne"
prop cle=fileFormat valeur="PDF"
prop cle=fileName valeur="trs_{SYS.Date}"
prop cle=icon valeur="TRUE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=390 type=ExportButton nom="Export_Recette" calque=383 parent=0 verrou=0 cache=0
prop cle=x valeur="1030"
prop cle=y valeur="364"
prop cle=w valeur="230"
prop cle=h valeur="48"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Recette (Excel)"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="16"
prop cle=textColor valeur="#FFFFFF"
prop cle=align valeur="centre"
prop cle=wrap valeur="FALSE"
prop cle=exportSource valeur="recette:Reglages_Armoires"
prop cle=fileFormat valeur="Excel"
prop cle=fileName valeur="recette_armoires"
prop cle=icon valeur="TRUE"
prop cle=fill valeur="#2F6FD6"
prop cle=stroke valeur="#1D4FA3"
prop cle=strokeWidth valeur="1"
prop cle=radius valeur="4"
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
objet id=391 type=Text nom="Dernier_Export" calque=383 parent=0 verrou=0 cache=0
prop cle=x valeur="790"
prop cle=y valeur="430"
prop cle=w valeur="470"
prop cle=h valeur="70"
prop cle=rot valeur="0"
prop cle=flipH valeur="FALSE"
prop cle=flipV valeur="FALSE"
prop cle=visible valeur="TRUE"
prop cle=opacity valeur="100"
prop cle=text valeur="Dernier export : {SYS.LastExport}\\n{SYS.ExportCount} fichier(s) écrit(s) dans exports/"
prop cle=font valeur="Sans"
prop cle=fontSize valeur="15"
prop cle=textColor valeur="#E6EAF0"
prop cle=align valeur="gauche"
prop cle=wrap valeur="TRUE"
prop cle=fill valeur=""
prop cle=variable valeur=""
prop cle=refresh valeur="500"
prop cle=access valeur="0"
fin
